### ISSUE TITLE
asyncio:Task exception was never retrieved

### ISSUE THREAD

**Issue by marcaurele** [ronf/asyncssh#101]
Hi,

I started to get this error running my script which uses asyncssh to connect to multiple servers through a bastion. I don't know the cause yet, but searching for an explanation/solution, it seems that something is not correctly handle inside the lib from what I could understand from https://docs.python.org/3/library/asyncio-dev.html#detect-exceptions-never-consumed
If you have a hint or some extra debug trick I could do, let me know. I will post here my findings too, and send a PR if needed.

```
› ./test_asyncssh.py 
DEBUG:asyncio:Using selector: KqueueSelector
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<SSHConnection._run_task() done, defined at /Users/marco/exoscale/toolbox/.venv/lib/python3.6/site-packages/asyncssh/connection.py:366> exception=CancelledError()>
concurrent.futures._base.CancelledError
Traceback (most recent call last):
  File "./test_asyncssh.py", line 63, in <module>
    test()
  File "./test_asyncssh.py", line 58, in test
    asyncio.get_event_loop().run_until_complete(test_async())
  File "/Users/marco/.pyenv/versions/3.6.2/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "./test_asyncssh.py", line 44, in test_async
    agent_forwarding=True) as bastion:
  File "/Users/marco/exoscale/toolbox/.venv/lib/python3.6/site-packages/asyncssh/misc.py", line 163, in __aenter__
    self._result = yield from self._coro
  File "/Users/marco/exoscale/toolbox/.venv/lib/python3.6/site-packages/asyncssh/connection.py", line 4644, in connect
    conn, _ = yield from create_connection(None, host, port, **kwargs)
  File "/Users/marco/exoscale/toolbox/.venv/lib/python3.6/site-packages/asyncssh/connection.py", line 4389, in create_connection
    yield from auth_waiter
asyncssh.misc.DisconnectError: Disconnect Error: Permission denied
```
And the script not working when connecting to some servers, but it works on other:
```python
# test_asyncssh.py
async def test_async():
    # Connect to bastion prior connecting to the host
    async with asyncssh.connect(BASTION_HOST,
                                username=BASTION_USER,
                                port=BASTION_PORT,
                                agent_forwarding=True) as bastion:
        result = await bastion.run('uname -a')
        print(result)


def test():
    asyncio.get_event_loop().run_until_complete(test_async())
    print("Done")
```

**Comment by marcaurele** [comment]
It looks related to the OSX keychain, which does not expose the good key.

**Comment by marcaurele** [comment]
Closing it as it's related to OSX keychain. The lib could be more explicit than `Disconnect Error: Permission denied` as the problem was that not authentication method worked (clientkeyauth did not work, then no password was given).

**Comment by ronf** [comment]
The only time you'll get this "Permission denied" here is actually in the case where all available authentication methods returned failure. I could report something like "All authentication methods failed", but "Permission denied" seemed more direct. The "code" returned in the exception is actually already DISC_NO_MORE_AUTH_METHODS_AVAILABLE in this case, if you were catching the exception and wanted to programmatically test what the failure was.

I don't currently have any explicit support in AsyncSSH for the OS X keychain, but there should be support for ssh-agent. So, if that was able to access keys in the OS X keychain, I would have expected that to work. I don't know if it can or not, though. I think in all the testing I've done with that, I always load keys manually into it. When I log in OS X starts ssh-agent automatically but it doesn't automatically load any keys into it.
