### ISSUE TITLE
asyncssh.misc.DisconnectError: Disconnect Error: Failed to read binary packet data!

### ISSUE THREAD

**Issue by saulcruz** [ronf/asyncssh#105]
I've been trying to find what's wrong with this, when trying to connect to an SFTP server, I've used asyncssh for other sftp servers and they work however I can't identify the problem for this server as I'm only getting this:

"asyncssh.misc.DisconnectError: Disconnect Error: Failed to read binary packet data!"

I'm just trying  to run the following:
```
async with asyncssh.connect(host=self.host,username=self.username, password=self.password, known_hosts=None) 
                async with conn.start_sftp_client() as sftp:
                    # do something
                    await sftp.get( remote_path)
```

Any ideas of what this could be, it might not be an asyncssh issue but there's definitely a use case for this particular server, unfortunately I'm not the admin of that sftp server.

Notes: I'm able to connect to this server using Paramiko, filezilla and pysftp, but I'd like to use asyncssh

**Comment by ronf** [comment]
Hi Saul,

The error here of "Failed to read binary packet data!" seems to be coming from the SFTP server. It's sending a MSG_DISCONNECT for some reason, suggesting it doesn't like something that AsyncSSH is sending it. Is there any way you could enable logging on the server to see if it provides any clue where in the connection setup it is failing?

How far are you getting on the client side? Does the connect() call succeed? What about the start_sftp_client() call? I'm wondering if you are actually able to get the channel open far enough to request the file transfer, or if it is failing before that.

**Comment by saulcruz** [comment]
Hey Ron,

I'll get back to you about the logging on the server as this is a vendor read-only server.

The connect() call does not succeed, so it never gets to start_sftp_client()

**Comment by ronf** [comment]
Ok. If you're able to connect from other tools like the command-line SFTP, you could run that in "verbose" mode and see what algorithms are picked for key exchange, encryption, etc. and try forcing some of those values in AsyncSSH to see if that makes a difference.

**Comment by saulcruz** [comment]
In Putty I got the following:

`2017-08-31 14:30:36	Using SSH protocol version 2
2017-08-31 14:30:36	Doing ECDH key exchange with curve nistp256 and hash SHA-256
2017-08-31 14:30:36	Host key fingerprint is:
2017-08-31 14:30:36	ssh-rsa 1024 xx:xx:................
2017-08-31 14:30:36	Initialised AES-256 SDCTR client->server encryption
2017-08-31 14:30:36	Initialised HMAC-SHA-256 client->server MAC algorithm
2017-08-31 14:30:36	Initialised AES-256 SDCTR server->client encryption
2017-08-31 14:30:36	Initialised HMAC-SHA-256 server->client MAC algorithm
2017-08-31 14:30:45	Attempting keyboard-interactive authentication
2017-08-31 14:30:49	Access granted
`
Looks like the key echange, and the MAC algorithm are supported by asyncssh, what I'm still not clear on is the  AES-256 SDCTR encryption , how can you force these values?

Thanks Ron

**Comment by ronf** [comment]
Ok. The arguments listed there would suggest you'd want to use the following AsyncSSH arguments to get the same values:

kex_algs=['ecdh-sha2-nistp256'], encryption_algs=['aes256-ctr'], mac_algs=['hmac-sha2-256']

Compression isn't mentioned there, so you may also want to specify compression_algs=['none'].

More recently, I also added support for alternate signature algorithms. To force the standard RSA signature algorithm based on SHA-1, you can add signature_algs=['ssh-rsa'].

I'm not really expecting any of this to make a difference, but it's worth a shot. AsyncSSH will attempt to default to chacha20-poly1305 these days, and it's possible that the server in question doesn't handle that right. It also prefers the more secure "ETM" (Encrypt then MAC) flavor of HMAC algorithms which are specific to OpenSSH, and I'm not sure if the server supports that. Any such unsupported algorithms should be ignored in the negotiation, of course, making this all unnecessary, but let's see what happens.

**Comment by saulcruz** [comment]
awesomeness, forcing exactly those arguments made the job! thanks a lot Ron!

**Comment by ronf** [comment]
Interesting! If you happen to have the time, I'd be curious which of the arguments actually made the difference. It could be helpful going forward if others run into a similar issue.

**Comment by saulcruz** [comment]
First I tested all of them:

`     async def get(self,remote_path):
        try:
            async with asyncssh.connect(host=self.host,
                                        username=self.username,
                                        password=self.password,
                                        known_hosts=None,
                                        kex_algs=['ecdh-sha2-nistp256'],
                                        encryption_algs=['aes256-ctr'],
                                        mac_algs=['hmac-sha2-256']) as conn:
                async with conn.start_sftp_client() as sftp:
                    # download file
                    await sftp.get( remote_path)`

Then I started playing with them and I realized that the one that made the difference was kex_algs=['ecdh-sha2-nistp256']

`    async def get(self,remote_path):
        try:
            async with asyncssh.connect(host=self.host,
                                        username=self.username,
                                        password=self.password,
                                        known_hosts=None,
                                        kex_algs=['ecdh-sha2-nistp256']
                                         ) as conn:
                async with conn.start_sftp_client() as sftp:
                    # download file
                    await sftp.get( remote_path)`

Thank you so much again Ron 👍

**Comment by ronf** [comment]
Happy to help - thanks for the additional info!

**Comment by saulcruz** [comment]
a small update, the above code used to work for version 1.10.0, on 1.11.0 it won't, the workaround is easy, add the following to your connect( )
 
` async with asyncssh.connect(host=self.host,

                                    username=self.username,

                                    password=self.password,

                                    known_hosts=None,

                                    kex_algs=['ecdh-sha2-nistp256'],

                                    **x509_trusted_certs=None**
                                     ) as conn:`

**Comment by ronf** [comment]
That's interesting. I guess in addition to the remote system being unable to properly ignore key exchange algorithms it doesn't understand, it might also have an issue with not properly coping with host key algorithms it doesn't understand. Without x509_trusted_certs=None, AsyncSSH would end up advertising something like the following for host-key algorithms:

x509v3-ecdsa-sha2-nistp521,x509v3-ecdsa-sha2-nistp384,x509v3-ecdsa-sha2-nistp256,x509v3-rsa2048-sha256,x509v3-ssh-rsa,x509v3-ssh-dss,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com

With that argument, though, the list drops to:

ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com

(plus possibly a few other non-certificate algorithm names depending on what specific key types you list as trusted for that host in your known_hosts file)
