### ISSUE TITLE
gpg-agent instead of ssh-agent: unable to sign with requested key

### ISSUE THREAD

**Issue by marcaurele** [ronf/asyncssh#115]
Just to inform you that if people are using the gpg-agent in place of the ssh-agent, the authentication with keys is problematic. I get many "Unable to sign with requested key" error (https://github.com/ronf/asyncssh/blob/2d37355f803dc10f018514fad49bb920f4365c43/asyncssh/agent.py#L272). If I use the ssh-agent, it works perfectly.
I don't know if there is something that can be done on asyncssh side, but I would guest the problem is on gpg-agent side.

**Comment by ronf** [comment]
Thanks for the report.

I hadn't previously tested GnuPG/gpg-agent, but I tried it tonight with GnuPG 2.2.2 on the Mac, and everything worked fine. I started up gpg-agent with "enable-ssh-support" in .gnupg/gpg-agent.conf and set SSH_AUTH_SOCK in my environment and then did an ssh-add of a handful of keys. I then went into AsyncSSH and connected to GnuPG's SSH agent socket and asked it to sign some data, and it returned successfully, for both RSA & ECDSA keys.

I also tried using asyncssh.connect() to connect to a server that trusted these keys and I was able to successfully log in, using gpg-agent to do signing. I wasn't able to get it to properly handle SSH certificates, but it seemed to handle plain keys just fine.

What type of key are you trying to use, and what version of GnuPG?

**Comment by marcaurele** [comment]
My setup is on a debian laptop, connecting through a bastion to a serie of hosts. It works fine with the normal SSH agent, but it doesn't with the gpg agent, having a couple of failures.

**Comment by ronf** [comment]
If you are able to reproduce the problem and can share some sample configurations and keys (or types of keys) that trigger the error, I'd be happy to try again to reproduce it. So far, both ssh-agent and gpg-agent work well for me from AsyncSSH with key types of RSA & ECDSA.

**Comment by marcaurele** [comment]
Already with 10 connections in //, I do have about 20-30% of failure in average.

**Comment by marcaurele** [comment]
- gpg-agent v2.2.1
- standard key RSA
- all connections go through a unique bastion (which has MaxSessions bumped to allow enough parallel connection)

Code sample :
```python
#!/usr/bin/env python3

import asyncio

import asyncssh

# To define
BASTION_HOST = ''
BASTION_USER = ''
BASTION_PORT = 
AGENTS = [...]
# Enough to reproduce the problem
THREADS = 10


async def check_agent_version(pre_semaphore, semaphore, bastion, hostname,
                              username):
    async with pre_semaphore, asyncssh.connect(hostname,
                                               username=username,
                                               known_hosts=None,
                                               tunnel=bastion) as conn:
        async with semaphore:
            await conn.run('apt-get update -qq', check=True)
            result = await conn.run('apt-cache policy nginx',
                                    check=True)
            return result.stdout, hostname


async def check_agents_version(hosts, threads):
    semaphore = asyncio.Semaphore(threads)
    pre_semaphore = asyncio.Semaphore(threads * 2)
    # Connect to bastion prior connecting to the host
    async with asyncssh.connect(BASTION_HOST,
                                username=BASTION_USER,
                                port=BASTION_PORT,
                                known_hosts=None,
                                agent_forwarding=True) as bastion:
        tasks = (check_agent_version(pre_semaphore,
                                     semaphore,
                                     bastion,
                                     host,
                                     'root') for host in hosts)
        results = await asyncio.gather(*tasks, return_exceptions=True)
        for result, host in zip(results, hosts):
            print(result)


def run():
    asyncio.get_event_loop().run_until_complete(
        check_agents_version(AGENTS, THREADS))

if __name__ == '__main__':
    run()

```

**Comment by ronf** [comment]
Thanks for the additional information! I've been able to reproduce the problem here, and can confirm what you saw where it works fine with the OpenSSH ssh-agent, but fails when using gpg-agent.

So far, I haven't been able to produce this failure with many parallel tasks making simultaneous gpg-agent requests, even with SSH agent forwarding involved, but I'll continue to try and tweak your test case to see if I can isolate what's causing the failure.

It's hard to say yet whether this is something I'll be able to work around on the AsyncSSH side.

**Comment by ronf** [comment]
Ok - I've managed to reproduce the failure with a much simpler program:

```python
import asyncio, asyncssh

async def run_client():
    async with asyncssh.connect('localhost', known_hosts=None,
                                agent_forwarding=True) as bastion:
        tasks = (bastion.connect_ssh('localhost', known_hosts=None)
                     for _ in range(10))
        results = await asyncio.gather(*tasks, return_exceptions=True)
        print([r for r in results if isinstance(r, Exception)])


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(run_client())
```

I still don't know the exact source of the problem, but turning on debugging on gpg-agent was interesting. The errors it is returning are:

gpg-agent[95514]: failed to unprotect the secret key: Cannot allocate memory
gpg-agent[95514]: failed to read the secret key
gpg-agent[95514]: ssh sign request failed: Cannot allocate memory <Pinentry>
gpg-agent[95514]: Warning: using insecure memory!

I have no idea why it would be having trouble allocating memory here, especially with only 10 simultaneous connections. Searching for this error did show some other folks who have run into similar problems with older GPG versions, but I'm not sure if this is the same problem or not.

In particular, check out https://dev.gnupg.org/T3027. I'm wondering if maybe gpg-agent has a very small pool of "secure" memory, and sending enough parallel requests to it can cause it to exhaust all that memory. If that's the case, your only option might be to slow down the rate of requests being sent to it.

**Comment by marcaurele** [comment]
Thanks @ronf for digging into this. I was suspecting that it wasn't a problem on asyncssh side, but I wanted to leave a trace in case someone happens to have the same issue. I just udpated the gpg-agent to 2.2.2 and will try it, otherwise I'll continue the thread on the GNUpg bug.
Anyway I will give feedback on this thread too.

**Comment by ronf** [comment]
Yeah - I appreciate you reporting this. I'll leave this open for now, so you can follow up later if you hear anything further.

For what it's worth, the testing I did was all against GnuPG 2.2.2 (on macOS), and I still saw the problem.

**Comment by marcaurele** [comment]
Hi @ronf , the issue seems to be resolved now (the GPG issue too). I cannot reproduce it anymore, closing it.

**Comment by ronf** [comment]
That's great, Marc - thanks for following up!

**Comment by slve** [comment]
almost 4 years later, I know, just wanted to note that you may also need to add `auto-expand-secmem` to your gpg-agent.conf

**Comment by ronf** [comment]
Good to know, thanks @slve ! It looks like that option was added to GPG shortly after this issue was opened -- here's a link I was able to find about it: https://dev.gnupg.org/T3530
