### ISSUE TITLE
travis: Run tests on uvloop

### ISSUE THREAD

**Issue by 1st1** [ronf/asyncssh#120]
(Low Priority)

Would be really great if we could make the CI to test asyncssh on top of uvloop, in addition to vanilla asyncio.  Sometimes because something doesn't work on uvloop as expected we find bugs in asyncio, and make adjustments to its APIs.

**Comment by ronf** [comment]
Good idea! I'm traveling at the moment, but will take a look when I get back home.

Do you have any examples I can look at of other projects which are doing this on TravisCI?

**Comment by 1st1** [comment]
Thanks!

asyncpg is one example, but we have a pretty complex CI setup.

aiohttp is testing uvloop IIRC.

**Comment by ronf** [comment]
I've just added support for running unit tests against uvloop by setting the environment variable USE_UVLOOP=1. I also updated the Travis CI config to run these additional builds against Python 3.5 and later on Linux and macOS. I'm just waiting for the builds to finish now, but things look good so far.

**Comment by ronf** [comment]
This appears to be working nicely for both Linux and MacOS builds on TravisCI, so I'm going to close this issue. Thanks for the suggestion!
