### ISSUE TITLE
Add CONTRIBUTING guide

### ISSUE THREAD

**Issue by nchammas** [ronf/asyncssh#13]
Are there basic instructions anywhere on how to run unit tests and other such things for new/aspiring AsyncSSH contributors?

Many projects typically have a CONTRIBUTING doc at the root of the project with this kind of info. Here is [neovim's contributing guide](https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md), for example.

AsyncSSH's guide obviously does not need to be as long, but basic instructions on what to do, for example, when you want to contribute a patch would be useful.

**Comment by ronf** [comment]
I've been busy working on SFTP support, but I will try and add a CONTRIBUTING doc when I get a chance. Thanks for providing such a great example!

Unfortunately, unit testing is one area that this code is weak on at the moment. I do have a collection of unit tests checked in for key import/export which can be run by executing "setup.py test", but I haven't gone in and added unit tests for anything else yet. Contributions are certainly welcome in this area, and new tests can be added by adding new modules to the "tests" directory. I'm currently using the standard "unittest" library for this.

Other contributions are also welcome. I'd suggest opening an issue here first to describe what you'd like to see or would like to add before coding anything, or posting a note about it to the asyncssh-dev or asyncssh-users mailing list (described in the README).

Bug reports are also extremely welcome!

**Comment by nchammas** [comment]
:+1: That all sounds good to me!

By the way, another contributing guide I really like, which you might want to skim over as another example, is the [Phabricator contributing guide](https://secure.phabricator.com/book/phabcontrib/), and specifically the [Contributing Code](https://secure.phabricator.com/book/phabcontrib/article/contributing_code/) guide.

**Comment by ronf** [comment]
I just submitted a first cut at a CONTRIBUTING guide. I haven't mentioned anything about testing yet as I'd like to understand that area a bit better myself before making suggestions about the best way to contribute tests, but other areas such as asking questions, reporting bugs, requesting features, and submitting code are covered.

**Comment by nchammas** [comment]
Contributing guide looks good to me. :+1:
