### ISSUE TITLE
Client direct TCP/IP channels not closing automatically

### ISSUE THREAD

**Issue by b-ryan** [ronf/asyncssh#130]
I originally started writing about this in #129, but since it's a separate issue, wanted to discuss it here.

I am making HTTP requests through a port forwarding client. The client does not appear to close the channels when the HTTP request is done, but only when the connection is closed.

To test that, I added logging into my server to show whenever the `connection_lost` function on my `SSHClientSession` was called (this session class is used for direct TCP/IP channels). My client then sends numerous requests, but each channel is only closed once I close the client connection.

In contrast, I changed my client to use OpenSSH subprocesses. When doing so, the channels are closed roughly when the HTTP request is done.

If it would help, I am happy to put together a sample client/server.

**Comment by ronf** [comment]
The AsyncSSH port forwarding code is designed to only close a channel when both ends have sent EOF. Could it be that in your case the HTTP servers you are contacting are set up to support persistent connections where they will accept more than one request on the connection, and so they aren't actually closing their side of the connection after they finish writing the HTTP response, expecting that you might want to re-use the connection to send another request?

**Comment by b-ryan** [comment]
I had tried to account for that in my testing - that's what I aimed to isolate by switching to the openssh client.

I will put together an minimal code sample to reproduce.

**Comment by ronf** [comment]
Ok, thanks. I'd be happy to take a look that when it's ready.

**Comment by b-ryan** [comment]
I'm not sure what was going on exactly when I originally ran into this. It must be a bug of my own or I was just tired and not thinking clearly. Can't reproduce it currently. Sorry for the bad issue. I will try to have code that does whatever I am claiming in the future before opening anything.
