### ISSUE TITLE
Question about running script "Fire and forget" style

### ISSUE THREAD

**Issue by lux-lth** [ronf/asyncssh#137]
Hello.

First, thank you for the great work! this lib is awesome.

I'm having some trouble running a script without waiting it's output :
```
conn = await asyncio.wait_for(asyncssh.connect('mydomain.com', known_hosts = None, username = 'root'), timeout=3)
await asyncssh.scp('/var/www/probes_driver/probe_deployment', (conn, '/ASD'), recurse=True)
await conn.run("cd /ASD && nohup bash install.sh &", stdout=asyncssh.DEVNULL, stderr=asyncssh.DEVNULL, check=False)
```

The execution hangs on that last line, I've tried many different redirections, and still can't manage to just run the script in the background.

This isn't really an issue I think, I must be doing something wrong.

Do you have any idea ?

Thank you.

**Comment by ronf** [comment]
I noticed you already closed this - did you figure out the problem?

If you use '< /dev/null >/dev/null 2>&1' to do the redirection to /dev/null in the remote shell in addition to using nohup and running the remote command in the background, I think you'll be able to get the command to complete immediately. It really has nothing to do with AsyncSSH itself -- you'll see the same behavior with OpenSSH as a client. It all comes down to how the remote SSH server works.

If you use AsyncSSH's stdin/stdout/stderr redirection, the remote process will still have pipes open to the SSH server. So, even though AsyncSSH will discard any output which is generated and forwarded back over the SSH channel, those pipes are enough to prevent the SSH server from closing the channel right away. It's only when the command finishes and closes the open pipes that the channel will be closed.

**Comment by ronf** [comment]
I agree that create_process() would probably work fine here, but there is a small chance that you could end up closing the channel you opened before the remote system is fully done starting up the shell and asking it to run the command. I don't know if that would ever cause a problem, but when I tried this the other day I was able to get run() to work just fine for this, letting the remote end control when the channel was closed. Here was the test program I used:

```python
import asyncio, asyncssh

async def run_client():
    async with asyncssh.connect('localhost') as conn:
        await conn.run('nohup sleep 10 < /dev/null > /dev/null 2>&1 &')

asyncio.get_event_loop().run_until_complete(run_client())
```

I think this should work ok for your case with stdout and stderr redirected to a file, if you wanted to go back to that.

**Comment by lux-lth** [comment]
Thank you!
I'll keep that in mind in case I have issues with create_process.
For the time being it's working fine.

**Comment by jerrylogansquare** [comment]
I tried both the run with redirect to/from null, and that worked, thanks!!  Saved me.
