### ISSUE TITLE
how to use ControlMaster / ControlPath?

### ISSUE THREAD

**Issue by sixninetynine** [ronf/asyncssh#138]
Hi @ronf!

Great project! I wanted to ask if it's possible to (re)use the sockets created by the ControlMaster / ControlPath options of `ssh`. Ref: https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing

For example, I have a bastion host set up that I proxy through, but it requires special 2 factor authentication, with ControlMaster and ControlPersist I only need to auth once in a while and my subsequent connections re-use the persisted socket. I don't see a way to connect to this same socket via AsyncSSH (doesn't seem to support AF_UNIX?)

Thanks in advance!

**Comment by ronf** [comment]
Sorry, this isn't possible right now with AsyncSSH. I see the value in being able to do what you're hoping to do with it, but  the way the multiplex protocol works doesn't allow AsyncSSH to perform the encryption/decryption or control the SSH messages being sent. Basically, all it can do is to hand over a set of stdin, stdout, and stderr file descriptors to OpenSSH along with some other options associated with the session being opened and have the existing OpenSSH process take over actually doing the SSH encryption/decryption and shuffling of data back and forth. There's really no point in that, though. If all you want to do is tunnel data from existing file descriptors over a multiplexed SSH connection, you might as well initiate that from OpenSSH itself. If you want to do something more programmatic where it's not a simple set of file descriptors you want to use to feed data, that could be interesting, but that's not supported by the current OpenSSH mux protocol. More info on the protocol can be found at:

https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/PROTOCOL.mux?annotate=HEAD

That said, AsyncSSH is capable of tunneling on top of an existing SSH connection (similar to OpenSSH's ProxyJump feature), and it's even possible with a bit of a hack to do this for a connection you establish using other tools (see #104 for more details on that).

I'm not sure if that will work for you here, but it might. You could use AsyncSSH to first open a connection to the bastion host with the two-factor auth and then use forwarded TCP connections to allow AsyncSSH to connect to SSH servers on the remote systems you want to access. This would require authentication for each tunneled connection, but it would be authentication by the remote systems and not the bastion host, so the two-factor auth might not be needed on those.

If you use AsyncSSH to open both sets of connections, you wouldn't need the hack described in #104. You'd be able to just use the create_ssh_connection() or connect_ssh() method on the SSH connection opened to the bastion host to connect to each of the remote systems.

**Comment by sixninetynine** [comment]
Thanks for the reply!

Using the `tunnel=` kwarg for `asyncssh.connect` is working well enough for me!

**Comment by sixninetynine** [comment]
Excellent advice! I'll definitely start using that helper (my code looks a lot like your first example).

Thanks again!
