### ISSUE TITLE
Aborting channel stay forever.

### ISSUE THREAD

**Issue by waqasraz** [ronf/asyncssh#153]
Something is not right here. Sometimes it says Aborting channel and doesn't move forward. I think it's really hard to reproduce. because I am using a VPN to connect to NCM and then using that connection to connect to devices. Since VPN is not stable when it gets disconnected this prompt doesn't move forward. 

[Image](https://ibb.co/gPfp7J)

https://github.com/ronf/asyncssh/blob/a5964964d00fca75aa708516b67bf581850c5cd7/asyncssh/channel.py#L680

**Comment by ronf** [comment]
"Aborting channel" is printed when your application code calls abort() explicitly on a channel. Are you doing that? If so, what behavior are you expecting that you're not seeing? 

From what I can tell, the remote process has already sent an exit status and closed its side of the channel even before you call abort(). So, you should be able to call either close() or abort() at that point and get more or less the same result.

**Comment by ronf** [comment]
As part as some other recent work, I made some changes to the clean up code for channels, particularly when the remote system closes the connection first. I don't know if that will help or not with what you were seeing here, but you might want to try again with the latest code in the "develop" branch and see whether you can still reproduce this issue or not.

Also, if you have any more information on what you were expecting but not seeing after calling abort(), that may help me to track this down. I noticed in the screen shot that you have multiple connections open and multiple channels on each connection. That's fine, but from the screen shot it wasn't clear to me how these connections/channels were related or what else had happened on the channel you called abort() on prior to that call. In my comment above, I talked about getting an exit status and close, but I see now that was on a different connection than what you called abort() on, so my previous wasn't right in that regard.

**Comment by ronf** [comment]
Closing this for now - please re-open if you are still seeing a problem in the latest release. The fix mentioned above is now available in AsyncSSH 1.14.0.
