### ISSUE TITLE
Docs for SSHClientConnection.get_extra_info() need a little elaboration

### ISSUE THREAD

**Issue by nchammas** [ronf/asyncssh#16]
I have an SSH client connection that I reuse and pass around to various methods so as to avoid having to recreate the connection over and over.

Sometimes, I want those methods to print some informational messages about what they are doing and to which server, so I need a way to extract the server IP address from an existing SSH client.

I eventually figured out that the way to do this is as follows:

```python
with (yield from asyncssh.connect('localhost')) as conn:
    (host, port, _, _) = conn.get_extra_info('peername')
```

This is not clear from [the docs for `get_extra_info()`](http://asyncssh.readthedocs.org/en/stable/api.html#asyncssh.SSHClientConnection.get_extra_info). It would be helpful if they linked to the appropriate Python docs (if any) that show all the supported values for the `name` input parameter.

An additional but separate suggestion would be to perhaps allow users to call `get_extra_info()` without any arguments and get back a dictionary of all the available information. That would help with discovery of the available properties.

**Comment by ronf** [comment]
When I first put together the docs, I didn't have the linking to the main Python docs working, but I managed to fix that recently. Including a link directly to asyncio.BaseTransport's get_extra_info() documentation is a good idea. I'll add that to my list and get it in once I check in some other cleanup I'm in the middle of.

By the way, you need to be careful with the 'peername' and 'sockname' keys there. They are only 4-tuples for IPv6. For IPv4, I believe you'll only get back a 2-tuple of host & port. I dealt with this in AsyncSSH by using the following construct:

```python
    host, port = conn.get_extra_info('peername')[:2]
```

Even this is potentially dangerous, though, if for some reason the underlying socket is not about to return a peer name. For safety, you should check if peername is None before you unpack it, or provide a default value in the get_extra_info() call which is a 2-tuple to avoid getting an error in the unpack.

Regarding getting back all of the keys you can query, I don't really know how to do that for the values being returned by the base transport. While the data is stored internally in the transport as a dictionary, there's no public API to access that directly.

**Comment by ronf** [comment]
This change is now checked into the develop branch, and the updated docs are available [here](http://asyncssh.readthedocs.org/en/develop/api.html#sshreader). Thanks for the suggestion!

**Comment by nchammas** [comment]
> By the way, you need to be careful with the 'peername' and 'sockname' keys there. They are only 4-tuples for IPv6. For IPv4, I believe you'll only get back a 2-tuple of host & port.

Thanks for pointing that out.

> This change is now checked into the develop branch, and the updated docs are available [here](http://asyncssh.readthedocs.org/en/develop/api.html#sshreader).

Great! I think you meant to link here: http://asyncssh.readthedocs.org/en/develop/api.html#asyncssh.SSHClientConnection.get_extra_info

**Comment by ronf** [comment]
Actually, the change is in both places (and a couple of others). I linked to the bottom of the tree, so you that you work your way up through the other intermediate places where I added a link, until you finally get to the Python library doc.
