### ISSUE TITLE
asyncssh + Python repl

### ISSUE THREAD

**Issue by jonathanslenders** [ronf/asyncssh#17]
Hi @ronf,

I just wanted to share this with you. This is the ptpython REPL running on top of asyncio-ssh. So, you can run an SSH server, and as soon as you connect, you get a Python REPL to manipulate the running process. The REPL shares the same event loop of asyncio.

https://github.com/jonathanslenders/ptpython/blob/master/examples/asyncio-ssh-python-embed.py

Your library is amazing.

Jonathan

**Comment by ronf** [comment]
Thanks very much for the compliment, Jonathan, and for sharing your example!

PTPython looks like a very cool package, and it's actually very similar to the kind of application that inspired me to write asyncssh in the first place. In my case, I was looking for a way to run a multi-user interactive event loop based application where all of the connections from users shared a single common Python environment.
