### ISSUE TITLE
How do I close an connection on demand?

### ISSUE THREAD

**Issue by pttdev** [ronf/asyncssh#173]
I dive in the docs but did not found an api to terminate a connection. It would be great if it has some sort of handy function to do that.

**Comment by pttdev** [comment]
digging into issues found simple function: close()

**Comment by ronf** [comment]
That's correct.

In the case of SSHServerProcess(), there's also exit() and exit_with_signal() which will set an exit status before closing the channel.

**Comment by ronf** [comment]
Also, if you use the "async with" syntax on the SSH connection object as shown in most of the examples, a close() will be done automatically when you leave the "with" block.
