### ISSUE TITLE
AsyncSSH's dependencies are not visible to pip

### ISSUE THREAD

**Issue by nchammas** [ronf/asyncssh#18]
pip thinks that AsynsSSH does not have any dependencies.

```
$ pip3 show asyncssh
---
Metadata-Version: 1.1
Name: asyncssh
Version: 1.1.1
Summary: AsyncSSH: Asynchronous SSHv2 client and server library
Home-page: http://asyncssh.timeheart.net
Author: Ron Frederick
Author-email: ronf@timeheart.net
License: Eclipse Public License v1.0
Location: /usr/local/lib/python3.4/site-packages
Requires: 
```

This may well be the case, but there are several modules [mentioned in the README](https://github.com/ronf/asyncssh/blob/8ea2dd5ead4a027685c4bc157370a8955d9ca9a5/README.rst#installation) that the user has to install to enable additional functionality.

If you expect a large proportion of the user base to need any of these modules, I suggest capturing them as dependencies in PyPI so that pip will automatically install them when it installs AsyncSSH.

This greatly simplifies things for your users. I would venture that most people would expect things to just work after a single `pip install`.

For comparison, this is what pip sees for Pandas (note the `Requires:` line):

```
$ pip3 show pandas
---
Metadata-Version: 2.0
Name: pandas
Version: 0.16.0
Summary: Powerful data structures for data analysis, time series,and statistics
Home-page: http://pandas.pydata.org
Author: The PyData Development Team
Author-email: pydata@googlegroups.com
License: BSD
Location: /usr/local/lib/python3.4/site-packages
Requires: python-dateutil, pytz, numpy
```

**Comment by nchammas** [comment]
Specifically, I think this requirement at the least

> Install PyCrypto 2.6 or later from http://www.pycrypto.org and/or
   PyCA 0.6.1 or later from https://cryptography.io to provide basic
   crypto support.

should be captured programmatically and struck from the README. (In fact, I'm currently working on a pull request with several proposed refinements to the README. This is one of them.)

And I, for one, wouldn't mind the optional requirements like libsodium and bcrypt also be captured programmatically, given they don't drastically affect the install time of AsyncSSH.

**Comment by ronf** [comment]
I have actually captured all of the dependencies (pycrypto, pyca, bcrypt, and libnacl) already in setup.py. However, I haven't made any of them required dependencies just yet. For now, I have them listed as "extras", and let you decide which ones you want to install. It's easy to choose them if you want, though. You'd just do something like:

pip install 'asyncssh[pycrypto,pyca,bcrypt,libnacl]'

Admittedly, this is a little obscure compared to just "pip install asyncssh", but it does give the user more control over what packages they pull in. The only real "requirement" is that either pycrypto or cryptography is installed, but asyncssh doesn't care which one. For the others, it'll use them if they are installed, but it works fine (minus a few features) without them.

Also, some things like libnacl still require a manual step, as it depends on the C library libsodium and that can't be installed via pip as far as I know.

If the cryptography package continues to add in the functionality I need, I may eventually drop some of these other packages and just depend on it, at which point I would make it a required dependency. In the meantime, though, you can use the above syntax to save some of the effort.

Perhaps I should consider making an 'all' optional extra which grabs the full list of things asyncssh can take advantage of, so you could run "pip install 'asyncssh[all]'". I could then add that into the README file as an alternative.

**Comment by nchammas** [comment]
> If the cryptography package continues to add in the functionality I need, I may eventually drop some of these other packages and just depend on it, at which point I would make it a required dependency.

That would be good, since there is currently a requirement -- though there are 2 choices for fulfilling it -- that is technically not enforced. But now I see why you did it that way.

> Perhaps I should consider making an 'all' optional extra which grabs the full list of things asyncssh can take advantage of, so you could run "pip install 'asyncssh[all]'". I could then add that into the README file as an alternative.

That would be neat. I didn't know you could parameterize installs like that. An `all` option would be convenient, but you could just point out the `pip install 'asyncssh[pycrypto,pyca,bcrypt,libnacl]'` syntax in the README since I don't think it's very common and that would be good enough (for me, at least).

**Comment by ronf** [comment]
The README has been updated as discussed here.
