### ISSUE TITLE
Behaviour of `connection_requested` and `server_requested`

### ISSUE THREAD

**Issue by supriyo-biswas** [ronf/asyncssh#181]
I'm trying to understand the behaviour of asyncssh with respect to various types of port forwarding.

I have the following bit of code, which logs incoming request types and refuses to serve them:

```python
import asyncio
from asyncssh import *

class MySSHServer(SSHServer):
    def connection_made(self, conn):
        print('connection received')

    def connection_lost(self, exc):
        print(f'connection lost {exc}')

    def begin_auth(self, username):
        return True

    def password_auth_supported(self):
        return True

    def validate_password(self, username, password):
        return True

    def session_requested(self):
        print('Session requested')
        return False

    def connection_requested(self, dest_host, dest_port, orig_host, orig_port):
        print(f'Port forwarding requested ({dest_host}, {dest_port}) -> ({orig_host}, {orig_port})')
        return False

    def server_requested(self, listen_host, listen_port):
        print(f'Server requested ({listen_host}, {listen_port})')
        return False

async def start_server():
    await create_server(MySSHServer, '', 5833, server_host_keys=['ssh_host_key'])
```

Now, I tried to make various types of port forwarding requests, and it seems like only reverse port forwarding is handled:

* `ssh ... -NL 5000:localhost:5000` doesn't seem to log the port forwarding attempt.
* `ssh ... -NR 5000:localhost:5000` logs "server requested", which is then refused.

Am I missing something?

**Comment by ronf** [comment]
There's nothing wrong with your SSHServer class here. The difference is that server_requested() is called when the listening socket is requested, which happens as soon as the OpenSSH client starts up when using "-R". However, connection_requested() is not triggered until there's a local connection to forward when using "-L". So, it does not get called when the OpenSSH client starts. Instead, it is called each time a connection to the local port specified in "-L" is opened. In your example, try connecting locally to port 5000 after running the ssh command with "-L". Each time you do, you should see connection_requested() called.

**Comment by supriyo-biswas** [comment]
That explains it, thanks for the help :smile:
