### ISSUE TITLE
Socks UDP Foward

### ISSUE THREAD

**Issue by jmcgrath207** [ronf/asyncssh#184]
I am trying to write a script where can create a connection to a jump server that  would forward SNMP requests from the Client through the jump server to reach the device. 

Client  [SSH Tunnel] ===> JumpServer [SNMP] ===>  Device

If I am correct, this can be done with a SOCKS5 proxy using UDP Associate.

https://tools.ietf.org/html/rfc1928#section-4

The method, I found was `forward_socks()`. Would this be able to do this?

Also if this is not possible, is there any way I can execute python code on the jump server 's remote interpreter using asyncssh?

Thank you,

John

**Comment by ronf** [comment]
Hi John,

It's true that the SOCKS protocol can normally forward UDP. However, the SSH protocol really doesn't provide any way to forward anything but TCP traffic, and so the SOCKS support in both OpenSSH and AsyncSSH is limited to only accepting SOCKS requests that involve TCP.

There are pages out there that describe how to forward UDP over SSH, but this is basically done by using external tools like "nc" or "socat" to convert UDP to TCP. For instance, check out https://stackpointer.io/network/ssh-port-forwarding-tcp-udp/365/. I don't see any reason why AsyncSSH couldn't be used to do the tunneling of TCP traffic over SSH in this case, after something like socat converted the local UDP traffic to TCP on either end.

Also, it should be quite straightforward to use AsyncSSH as an SSH client to send commands to run on the jump server, if the jump server allows such requests. Some jump servers are locked down to only allow SSH tunnels through them, though, so you'd have to try it and see. I'd suggest first getting it working manually with OpenSSH commands from a shell, and then you can convert whatever you got working into calls in AsyncSSH.

**Comment by jmcgrath207** [comment]
Hi Ronf,

Thanks for the quick response. Unfortunately using Socat is not an option for me since the JumpServer in our environment do SNMP monitoring already and I want to avoid messing that up.

As for the commands part, I was thinking more along the lines of what Mitogen does where it forwards python code and modules to the remote server to be interrupted.  Instead of using `conn.run("python -c 'print("hello server")'"`

example:

```
def remote_func():
    return aiosnmp.getOIDs()


async def run_client():
    async with asyncssh.connect('localhost') as conn:
        result = await conn.execute(remote_func) # or partial func
        print(result.stdout, end='')
```
Would this be consider out of scope for the asyncssh project?

**Comment by ronf** [comment]
I have other concerns about the socat solution. It seems to me that converting UDP to TCP like that wouldn't always preserve packet boundaries in some cases if the traffic you were forwarding sent multiple UDP packets in the same direction.

Regarding running Python code on the remote system, SSH doesn't really provide a way to transmit code. You could copy the source file yourself, of course, and then tell the remote system to execute the Python interpreter and have it run the file you copied, but there's no way that a symbol like remote_func in the local environment could be meaningfully resolved into the same function on the remote system. I think you'd be better off just putting the code into a standalone script file, copying that with something like scp or sftp, and then running it as a command. For instance, you could have a file called my_script.py which looked something like:

```python
#!/usr/bin/env python

if __name__ == '__main__':
    """Put the code to run remotely here"""
```

Then, either keep that file on the remote system or copy it there explicitly with something like asyncssh.scp() and then use conn.run('python my_script.py') to execute it.
