### ISSUE TITLE
semi colon in filename sending through asyncssh.scp 

### ISSUE THREAD

**Issue by cuspymd** [ronf/asyncssh#186]
Hi. Thanks for great module.
When I try send a file named "303_2019-01-28T20:09:48.894642_0_15.ep" through asyncssh.scp(),
scp() parse it as the form "host:path".
I understand your parsing concept, But I want you to consider a file name having semi-colon characters.

**Comment by ronf** [comment]
I think you mean a pathname with a colon in it -- semi-colons (';') don't have any special meaning here.

If you want to reference a local file with a colon in its name, you can pass in a tuple of the form `(None, path)` -- the `None` is treated as the connection to use, and `None` there refers to a local file. This can be used as either a source or destination.

Other variations allow for the first element in the tuple to be an SSHConnection object, a hostname to connect to, or a tuple containing a host & port to connect to.

**Comment by cuspymd** [comment]
Yes. colon~.
I will try the tuple form.
Thank for detailed reply.
