### ISSUE TITLE
Get server's host key

### ISSUE THREAD

**Issue by david3352565** [ronf/asyncssh#189]
Is there a way to get server's host keys without authentication?
All I want to do is just iterate between a bunch of hosts and collect their host keys. I might not be authorized to visit all of them so it would be nice to have a function which gets host keys. 
In paramiko there is a method called [get_remote_server_key](http://docs.paramiko.org/en/2.4/api/transport.html?highlight=get_remote_server_key#paramiko.transport.Transport.get_remote_server_key)

**Comment by ronf** [comment]
Servers can have multiple host keys, choosing between them depending on what host key types a client is willing to accept. Is it sufficient here to return a single host key, but give the caller a way to provide a list of host key algs to offer the server, similar to what is done on a real connection?

Also, would you want the known_hosts checking to be done when making this call, if known_hosts is not set to `None` to disable it? Since you can turn it off if you don't want it, I'm thinking it might be best to do this checking when it is enabled (which is would be by default).

In cases where a server responded with a certificate, would you want the certificate returned here or the host key contained within the certificate?

**Comment by ronf** [comment]
After sleeping on this, a few things occurred to me.

First, if you want something which could work in the existing AsyncSSH, you might want to try passing in known_hosts='' to your AsyncSSH.create_connection() with an SSHClient class that defines the recently added validate_host_public_key() method. That will deliver the server's host key to you even if authentication doesn't complete. If the server is using a certificate, though, you'll only get a callback to validate_host_ca_key() and be given the public key of the CA used to sign the server's host key, not the host key in the certificate. So, I don't know if that will work for you in all cases.

If I add something here, I can imagine adding it in a few different ways:

  1. This could be added as a top-level method that makes a connection and tries to return the host key from the server it connects to without attempting to complete authentication. This would only get one of the server's host keys, but an argument could be provided to specify what host key type(s) to ask for and a client could call this multiple times to get all the keys. To be sure the server owns the public key that it claims to own, this would have to complete the handshake up to MSG_NEWKEYS before actually returning any key.
  2. After connecting and authenticating successfully, a method could be added to SSHConnection to return the host key actually used during the initial handshake. I think this may be what the paramiko method mentioned above might do.
  3. I could add support for the OpenSSH hostkeys-00@openssh.com extension for servers that support it, allowing them to provide a list of all their host keys after authentication completes. This would probably need to use the hostkeys-prove-00@openssh.com extension and check that the server actually owns those public keys before they are returned. This could be done via a callback on SSHClient which gets called when the hostkeys-00 extension is received, or it could be provided as a call on SSHClientConnection. For servers that didn't send hostkeys-00, I think this would fall back to returning what (2) does (the host key used to open this connection).

In all of these cases, the host key algorithm would have to be something AsyncSSH understands.

It'd probably make sense to start with (2) here, and then look at (1) as a special-case which uses (2) but stops to return this information after receiving MSG_NEWKEYS and before sending the user auth request. Separately, (3) could be added later as a more efficient way to get all of a server's host keys, but this would only work after authentication was completed successfully.

What do you think?

**Comment by ronf** [comment]
Items 1 and 2 above are now available in the "develop" branch in commit d3237e23. There's now a get_server_host_key() which can be called on SSHClientConnection objects for use when you already have a connection open, and a top-level asyncssh.get_server_host_key() coroutine which can connect to a server and return its host key. The latter works without needing to authenticate to the server, and provides arguments to control the key exchange method and host key types the server is allowed to use in its response, allowing some control over which type of host key you get back.

The returned value is an SSHKey public key object, which can then be converted to whichever format you want using methods like export_public_key().

**Comment by ronf** [comment]
This feature is now available in 1.16.0.
