### ISSUE TITLE
failing tests in 1.16.0 with older openssl

### ISSUE THREAD

**Issue by mimi1vx** [ronf/asyncssh#195]
on system with openssl-1.1.0h and pynacl installed, fix in #194 
```
  391s] ======================================================================
[  391s] ERROR: test_sign (tests.test_agent._TestAPI)
[  391s] Test signing a block of data using the agent
[  391s] ----------------------------------------------------------------------
[  391s] Traceback (most recent call last):
[  391s]   File "/home/abuild/rpmbuild/BUILD/asyncssh-1.16.0/tests/util.py", line 76, in async_wrapper
[  391s]     return self.loop.run_until_complete(wrapped_func)
[  391s]   File "/usr/lib64/python3.7/asyncio/base_events.py", line 584, in run_until_complete
[  391s]     return future.result()
[  391s]   File "/home/abuild/rpmbuild/BUILD/asyncssh-1.16.0/tests/test_agent.py", line 48, in agent_wrapper
[  391s]     yield from asyncio.coroutine(func)(self, agent)
[  391s]   File "/home/abuild/rpmbuild/BUILD/asyncssh-1.16.0/tests/test_agent.py", line 182, in test_sign
[  391s]     key = asyncssh.generate_private_key(alg_name)
[  391s]   File "/home/abuild/rpmbuild/BUILD/asyncssh-1.16.0/asyncssh/public_key.py", line 2548, in generate_private_key
[  391s]     key = handler.generate(algorithm, **kwargs)
[  391s]   File "/home/abuild/rpmbuild/BUILD/asyncssh-1.16.0/asyncssh/eddsa.py", line 52, in generate
[  391s]     return cls(EdDSAPrivateKey.generate(algorithm[4:]))
[  391s]   File "/home/abuild/rpmbuild/BUILD/asyncssh-1.16.0/asyncssh/crypto/ed.py", line 85, in generate
[  391s]     priv_key = priv_cls.generate()
[  391s]   File "/usr/lib64/python3.7/site-packages/cryptography/hazmat/primitives/asymmetric/ed25519.py", line 52, in generate
[  391s]     _Reasons.UNSUPPORTED_PUBLIC_KEY_ALGORITHM
[  391s] cryptography.exceptions.UnsupportedAlgorithm: ed25519 is not supported by this version of OpenSSL.
[  391s] 
[  391s] ======================================================================
[  391s] ERROR: test_curve448dh_errors (tests.test_kex._TestKex)
[  391s] Unit test error conditions in Curve448DH key exchange
[  391s] ----------------------------------------------------------------------
[  391s] Traceback (most recent call last):
[  391s]   File "/usr/lib64/python3.7/unittest/mock.py", line 1195, in patched
[  391s]     return func(*args, **keywargs)
[  391s]   File "/home/abuild/rpmbuild/BUILD/asyncssh-1.16.0/tests/util.py", line 76, in async_wrapper
[  391s]     return self.loop.run_until_complete(wrapped_func)
[  391s]   File "/usr/lib64/python3.7/asyncio/base_events.py", line 584, in run_until_complete
[  391s]     return future.result()
[  391s]   File "/usr/lib64/python3.7/asyncio/coroutines.py", line 120, in coro
[  391s]     res = func(*args, **kw)
[  391s]   File "/home/abuild/rpmbuild/BUILD/asyncssh-1.16.0/tests/test_kex.py", line 527, in test_curve448dh_errors
[  391s]     _KexClientStub.make_pair(b'curve448-sha512')
[  391s]   File "/home/abuild/rpmbuild/BUILD/asyncssh-1.16.0/tests/test_kex.py", line 176, in make_pair
[  391s]     client_conn = cls(alg, gss_host)
[  391s]   File "/home/abuild/rpmbuild/BUILD/asyncssh-1.16.0/tests/test_kex.py", line 180, in __init__
[  391s]     server_conn = _KexServerStub(alg, gss_host, self)
[  391s]   File "/home/abuild/rpmbuild/BUILD/asyncssh-1.16.0/tests/test_kex.py", line 210, in __init__
[  391s]     super().__init__(alg, gss, peer, True)
[  391s]   File "/home/abuild/rpmbuild/BUILD/asyncssh-1.16.0/tests/test_kex.py", line 59, in __init__
[  391s]     self._kex = get_kex(self, alg)
[  391s]   File "/home/abuild/rpmbuild/BUILD/asyncssh-1.16.0/asyncssh/kex.py", line 120, in get_kex
[  391s]     handler, hash_alg, args = _kex_handlers[alg]
[  391s] KeyError: b'curve448-sha512'
[  391s] 
[  391s] ----------------------------------------------------------------------

```

**Comment by ronf** [comment]
Thank you for the report, and the proposed fix. 

I went with a slightly different fix which should catch issues in test_kex if either curve25519 or curve448 isn't available. I also used unittest's "skipUnless" to make the entire test conditional in those cases. Could you try out the latest code in the "develop" branch (commit 2b86e6e) and see if the change works in your environment?

**Comment by mimi1vx** [comment]
your commit works for me :D

**Comment by ronf** [comment]
Terrific - thanks for the confirmation! This change will be rolled into the next release.

**Comment by ronf** [comment]
This fix is now available in 1.16.1.

**Comment by s1ider** [comment]
Still reproduces in 1.16.1 
`  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 412, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 599, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/pi/dpd-tests/venv/lib/python3.7/site-packages/asyncssh/misc.py", line 188, in __await__
    return (yield from self._coro)
  File "/home/pi/dpd-tests/venv/lib/python3.7/site-packages/asyncssh/connection.py", line 5724, in connect
    conn, _ = yield from create_connection(None, host, port, **kwargs)
  File "/home/pi/dpd-tests/venv/lib/python3.7/site-packages/asyncssh/connection.py", line 5339, in create_connection
    yield from conn.wait_kex()
  File "/home/pi/dpd-tests/venv/lib/python3.7/site-packages/asyncssh/connection.py", line 1861, in wait_kex
    yield from self._kex_waiter
  File "/home/pi/dpd-tests/venv/lib/python3.7/site-packages/asyncssh/connection.py", line 707, in data_received
    while self._inpbuf and self._recv_handler():
  File "/home/pi/dpd-tests/venv/lib/python3.7/site-packages/asyncssh/connection.py", line 928, in _recv_packet
    processed = handler.process_packet(pkttype, seq, packet)
  File "/home/pi/dpd-tests/venv/lib/python3.7/site-packages/asyncssh/packet.py", line 215, in process_packet
    self._packet_handlers[pkttype](self, pkttype, pktid, packet)
  File "/home/pi/dpd-tests/venv/lib/python3.7/site-packages/asyncssh/kex_ecdh.py", line 117, in _process_reply
    host_key = self._conn.validate_server_host_key(host_key_data)
  File "/home/pi/dpd-tests/venv/lib/python3.7/site-packages/asyncssh/connection.py", line 2445, in validate_server_host_key
    self._port, key_data)
  File "/home/pi/dpd-tests/venv/lib/python3.7/site-packages/asyncssh/connection.py", line 627, in _validate_host_key
    key = decode_ssh_public_key(key_data)
  File "/home/pi/dpd-tests/venv/lib/python3.7/site-packages/asyncssh/public_key.py", line 2471, in decode_ssh_public_key
    key = handler.make_public(*key_params)
  File "/home/pi/dpd-tests/venv/lib/python3.7/site-packages/asyncssh/eddsa.py", line 70, in make_public
    public_value))
  File "/home/pi/dpd-tests/venv/lib/python3.7/site-packages/asyncssh/crypto/ed.py", line 111, in construct
    pub_key = pub_cls.from_public_bytes(pub)
  File "/home/pi/dpd-tests/venv/lib/python3.7/site-packages/cryptography/hazmat/primitives/asymmetric/ed25519.py", line 26, in from_public_bytes
    _Reasons.UNSUPPORTED_PUBLIC_KEY_ALGORITHM
cryptography.exceptions.UnsupportedAlgorithm: ed25519 is not supported by this version of OpenSSL.`

**Comment by ronf** [comment]
Could you provide a full traceback here? The one above is truncated.

Are you seeing this on a unit test, or in your own code? Also, which version of cryptography and OpenSSL did you see it on?
