### ISSUE TITLE
`conn.start_server()` fails sliencely when port is alrady in use

### ISSUE THREAD

**Issue by JasonXJ** [ronf/asyncssh#197]
Here is some example code, and if you run it twice, they both output "server started", but actually only the first one has the port (can verify with `nc localhost 5555`)
```python3
import asyncio
import asyncssh

async def handle_client(reader, writer):
    print("client connected")
    while True:
        line = await reader.readline()
        if not line:
            break
        print("client says:", line)


async def start_remote_server():
    async with asyncssh.connect('localhost') as conn:
        print("connected")
        listener = await conn.start_server(lambda *args: handle_client, listen_host='localhost', listen_port=5555)
        print("server started")
        
        await asyncio.sleep(100000)


asyncio.get_event_loop().run_until_complete(start_remote_server())
```

I believe this also happens to `start_unix_server()`, which fails silently when, for example, the peer has older version of openssh not supporting unix socket (e.g. ubuntu 14.04 with openssh 6.6)

Expected behavior will be having an exception raised. Like what `asyncio.start_server()` does:
```
In [3]: await asyncio.start_server(handle_client, host='localhost', port=5565)
Out[3]: <Server sockets=[<socket.socket fd=15, family=AddressFamily.AF_INET, t
>, <socket.socket fd=16, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_S

In [4]: await asyncio.start_server(handle_client, host='localhost', port=5565)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
cell_name in async-def-wrapper()

/usr/lib/python3.7/asyncio/streams.py in start_server(client_connected_cb, hos
    112         return protocol
    113
--> 114     return await loop.create_server(factory, host, port, **kwds)
    115
    116

/usr/lib/python3.7/asyncio/base_events.py in create_server(self, protocol_fact
ess, reuse_port, ssl_handshake_timeout, start_serving)
   1376                         raise OSError(err.errno, 'error while attempti
   1377                                       'to bind on address %r: %s'
-> 1378                                       % (sa, err.strerror.lower())) fr
   1379                 completed = True
   1380             finally:

OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 55
```

**Comment by ronf** [comment]
Unfortunately, the nature of the SSH protocol is that you only get back a True/False result about whether a remote listener was opened successfully or not, and no detailed error information is available in the case of a failure.

That said, you can test for success or failure. In AsyncSSH, this is exposed by either returning you a listener object or `None` in the return value of conn.start_server(). So, in this case, if you check if `listener is None`, you should be able to see whether the remote system actually opened the listener or not.

I don't know for sure, but I would expect attempts to open UNIX domain sockets on older versions of OpenSSH that don't support that to also return a failure, and thus get back `None` in the return value of the create_unix_server() call.

**Comment by JasonXJ** [comment]
Oh, right. Apparently I missed the `None` part in the documentation.

Do you think it would be less surprising to have them raise exception instead? I think in python there are not a lot of functions using return values instead of exception to indicate error. This would be a breaking change though, so I understand if the idea is rejected.

Thanks for solving my question. Feel free to close the issue.

**Comment by ronf** [comment]
I see your point about exceptions, even if in this case I wouldn't really be able to return any meaningful error text. This API has been like this for about 5 years now, though, going back to the very first version of the AsyncSSH API built on asyncio (rather than asyncore). So, it'd be difficult to change at this point without disrupting a lot of existing code.
