### ISSUE TITLE
SFTP glob optimization

### ISSUE THREAD

**Issue by termim** [ronf/asyncssh#198]
Currently if pattern contains directories without glob characters then `_glob` uses `fs.listdir` call even if it is not needed. In case of high network latency and/or large number of entries in these
directories it can reduce performance significantly. 
Please take a look at #199 where I try to minimize the number of calls to `fs.listdir`.

**Comment by ronf** [comment]
Thanks very much for the contribution - this sounds quite nice. I'll look it over in the next few days!

**Comment by ronf** [comment]
This is now checked into the "develop" branch and will be part of the next release.

**Comment by ronf** [comment]
This optimization is now available in 1.16.1.
