### ISSUE TITLE
Create sftp client returns 4 values instead of 3

### ISSUE THREAD

**Issue by kpahawa** [ronf/asyncssh#203]
I am using AsyncSSH (v1.15.1) with asyncio (v3.4.3) in a Sanic app (v 18.12.0) and am getting this unexpected error from the library itself:

I have a class with methods like this:
	
    class MyClass:
	    async def connect(self, host, username, password, port):
	        return await asyncssh.connect(host=host, port=port, username=username, password=password, known_hosts=None)

	    async def establish_sftp_client(self, conn):
	        return await conn.start_sftp_client()

	    # This is my invoker:
	    async def create_connection(self, <some args>):
	        conn = await self.connect()
	        sftp_client = await self.establish_sftp_client(conn)
	        ...
	        return conn, sftp_client

I am getting this error when I try to run `create_connection`:

	Traceback (most recent call last):
	File "/tmp/pycharm_projects/<MY SANIC APP>/requests/helpers.py", line 378, in establish_sftp_client
	    return await conn.start_sftp_client()
	  File "<MY SANIC APP>/venv/lib/python3.6/site-packages/asyncssh/misc.py", line 182, in __await__
	    return (yield from self._coro)
	  File "<MY SANIC APP>/venv/lib/python3.6/site-packages/asyncssh/connection.py", line 3503, in start_sftp_client
	    encoding=None)
	ValueError: too many values to unpack (expected 3)

So that was a bit strange...so I put a log statement by running the internal operation that `start_sftp_client` does within the source code:

    async def connect(self, host, username, password, port):
            x = await conn.open_session(subsystem='sftp', encoding=None)
            self.logger.info(x)  # <-- the new log
	        return await asyncssh.connect(host=host, port=port, username=username, password=password, known_hosts=None)

This is what the log shows: 

> (asyncssh.stream.SSHWriter object at 0x7f51bbb29dd8, asyncssh.stream.SSHReader object at 0x7f51bbb29da0, asyncssh.stream.SSHReader object at 0x7f51b99b7978, asyncssh.stream.SSHClientStreamSession object at 0x7f51bbb29f98)

So it actually is returning 4 values...and when I look at the source code for asyncSSH, at what start_sftp_client() actually does, it is looking for only three:

`writer, reader, _ = yield from self.open_session(subsystem='sftp', encoding=None)`

**So it makes sense that this error is thrown...but why?**

But the REALLY strange part (to me) is when I run this method from the python console -- it works just fine with the versions of AsyncSSH and asyncio I have. An SFTP client is created properly from this script:

	import asyncssh, asyncio

	async def x():
	    conn = await asyncssh.connect(host='<host'>, username='some name', password='some pass', port=22, known_hosts=None)
	    sftp = await conn.start_sftp_client()
	    print("sftp {}".format(sftp)) # This works!

	asyncio.get_event_loop().run_until_complete(x())

Any idea on why it is creating 4 values in the Sanic app but creates 3 when run as a standalone method?

**Comment by ronf** [comment]
That is quite strange, assuming you haven't modified the AsyncSSH code at all. The start_sftp_client() method definitely doesn't return the session object. It looks like:

```python
    @asyncio.coroutine
    def open_session(self, *args, **kwargs):
        """Open an SSH client session

           This method is a coroutine wrapper around :meth:`create_session`
           designed to provide a "high-level" stream interface for creating
           an SSH client session. Instead of taking a `session_factory`
           argument for constructing an object which will handle activity
           on the session via callbacks, it returns an :class:`SSHWriter`
           and two :class:`SSHReader` objects representing stdin, stdout,
           and stderr which can be used to perform I/O on the session. With
           the exception of `session_factory`, all of the arguments to
           :meth:`create_session` are supported and have the same meaning.

        """

        chan, session = yield from self.create_session(SSHClientStreamSession,
                                                       *args, **kwargs)

        return (SSHWriter(session, chan), SSHReader(session, chan),
                SSHReader(session, chan, EXTENDED_DATA_STDERR))

```

It's clearly supposed to be returning three values (an SSHWriter for stdin and SSHReaders for stdout & stderr), just as start_sftp_client() is expecting. It makes no sense that the SSHClientStreamSession would be getting returned as a 4th value in the tuple, without some kind of code change.

Can you check to see that your version of open_session() hasn't been modified? Could something in your application be monkey-patching it?

**Comment by kpahawa** [comment]
It looks like the version of open_session has not been modified. I also searched for any references to `open_session` within any other packages in my virtual environment and only asyncssh methods came up (specifically in `asyncssh/scp.py`).  But as they're both part of the asyncssh package, I doubt that is what is causing the issue. 
These are the logs that asyncssh tries to publish as well:


	INFO       | 2019-03-28 02:04:30,676 | asyncssh                  | logging.py          : 79 |             log() | Opening SSH connection to test.rebex.net, port 22
	INFO       | 2019-03-28 02:04:31,350 | asyncssh                  | logging.py          : 79 |             log() | [conn=0] Connection to test.rebex.net, port 22 succeeded
	INFO       | 2019-03-28 02:04:31,350 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]   Local address: 172.20.4.146, port 49228
	INFO       | 2019-03-28 02:04:31,755 | asyncssh                  | logging.py          : 79 |             log() | [conn=0] Beginning auth for user demo
	INFO       | 2019-03-28 02:04:32,027 | asyncssh                  | logging.py          : 79 |             log() | [conn=0] Auth for user demo succeeded
	INFO       | 2019-03-28 02:04:32,029 | asyncssh                  | logging.py          : 79 |             log() | [conn=0, chan=0] Requesting new SSH session
	INFO       | 2019-03-28 02:04:32,159 | asyncssh                  | logging.py          : 79 |             log() | [conn=0, chan=0]   Subsystem: sftp

And then the stacktrace you saw above. 


In other parts of my code, I SSH into devices instead of using SFTP and I use the SSH functionality like this:

        self._conn = await asyncssh.connect(**self._connect_params_dict)  # type: SSHClientConnection
        
        self._stdin, self._stdout, self._stderr, self._session = await self._conn.open_session(
            term_type='Dumb',
            term_size=(200, 24)) 

In this case, is `open_session()` returning 4 values? This works just fine as well. 

If you're curious, here are the same logs with debug enabled:

	INFO       | 2019-03-28 02:16:35,937 | asyncssh                  | logging.py          : 79 |             log() | Opening SSH connection to test.rebex.net, port 22
	INFO       | 2019-03-28 02:16:36,347 | asyncssh                  | logging.py          : 79 |             log() | [conn=0] Connection to test.rebex.net, port 22 succeeded
	INFO       | 2019-03-28 02:16:36,348 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]   Local address: 172.20.4.146, port 59811
	DEBUG      | 2019-03-28 02:16:36,490 | asyncssh                  | logging.py          : 79 |             log() | [conn=0] Requesting key exchange
	DEBUG      | 2019-03-28 02:16:36,491 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]   Key exchange algs: curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,ecdh-sha2-1.3.132.0.10,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,rsa2048-sha256,rsa1024-sha1
	DEBUG      | 2019-03-28 02:16:36,491 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]   Host key algs: ssh-ed25519-cert-v01@openssh.com,ssh-ed448-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-1.3.132.0.10-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ssh-ed448,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,ecdsa-sha2-1.3.132.0.10,rsa-sha2-256,rsa-sha2-512,ssh-rsa,ssh-dss
	DEBUG      | 2019-03-28 02:16:36,492 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]   Encryption algs: aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,arcfour256,arcfour128,arcfour
	DEBUG      | 2019-03-28 02:16:36,493 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]   MAC algs: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-md5-etm@openssh.com,hmac-sha2-256-96-etm@openssh.com,hmac-sha2-512-96-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-md5,hmac-sha2-256-96,hmac-sha2-512-96,hmac-sha1-96,hmac-md5-96
	DEBUG      | 2019-03-28 02:16:36,495 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]   Compression algs: zlib@openssh.com,zlib,none
	DEBUG      | 2019-03-28 02:16:36,500 | asyncssh                  | logging.py          : 79 |             log() | [conn=0] Received key exchange request
	DEBUG      | 2019-03-28 02:16:36,506 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]   Key exchange algs: curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group16-sha512,diffie-hellman-group15-sha512,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256
	DEBUG      | 2019-03-28 02:16:36,506 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]   Host key algs: ssh-ed25519,ecdsa-sha2-nistp256,rsa-sha2-512,ssh-rsa-sha256@ssh.com,rsa-sha2-256,ssh-rsa
	DEBUG      | 2019-03-28 02:16:36,507 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]   Client to server:
	DEBUG      | 2019-03-28 02:16:36,507 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]     Encryption algs: aes256-ctr,aes256-cbc,aes192-ctr,aes192-cbc,aes128-ctr,aes128-cbc,twofish256-ctr,twofish192-ctr,twofish128-ctr
	DEBUG      | 2019-03-28 02:16:36,508 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]     MAC algs: hmac-sha2-512,hmac-sha2-256
	DEBUG      | 2019-03-28 02:16:36,508 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]     Compression algs: none
	DEBUG      | 2019-03-28 02:16:36,508 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]   Server to client:
	DEBUG      | 2019-03-28 02:16:36,509 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]     Encryption algs: aes256-ctr,aes256-cbc,aes192-ctr,aes192-cbc,aes128-ctr,aes128-cbc,twofish256-ctr,twofish192-ctr,twofish128-ctr
	DEBUG      | 2019-03-28 02:16:36,509 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]     MAC algs: hmac-sha2-512,hmac-sha2-256
	DEBUG      | 2019-03-28 02:16:36,509 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]     Compression algs: none
	DEBUG      | 2019-03-28 02:16:36,538 | asyncssh                  | logging.py          : 79 |             log() | [conn=0] Beginning key exchange
	DEBUG      | 2019-03-28 02:16:36,538 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]   Key exchange alg: curve25519-sha256@libssh.org
	DEBUG      | 2019-03-28 02:16:36,740 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]   Client to server:
	DEBUG      | 2019-03-28 02:16:36,740 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]     Encryption alg: aes256-ctr
	DEBUG      | 2019-03-28 02:16:36,740 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]     MAC alg: hmac-sha2-256
	DEBUG      | 2019-03-28 02:16:36,741 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]     Compression alg: none
	DEBUG      | 2019-03-28 02:16:36,741 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]   Server to client:
	DEBUG      | 2019-03-28 02:16:36,741 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]     Encryption alg: aes256-ctr
	DEBUG      | 2019-03-28 02:16:36,741 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]     MAC alg: hmac-sha2-256
	DEBUG      | 2019-03-28 02:16:36,742 | asyncssh                  | logging.py          : 79 |             log() | [conn=0]     Compression alg: none
	DEBUG      | 2019-03-28 02:16:36,742 | asyncssh                  | logging.py          : 79 |             log() | [conn=0] Completed key exchange
	DEBUG      | 2019-03-28 02:16:36,744 | asyncssh                  | logging.py          : 79 |             log() | [conn=0] Requesting service ssh-userauth
	DEBUG      | 2019-03-28 02:16:36,867 | asyncssh                  | logging.py          : 79 |             log() | [conn=0] Request for service ssh-userauth accepted
	INFO       | 2019-03-28 02:16:36,867 | asyncssh                  | logging.py          : 79 |             log() | [conn=0] Beginning auth for user demo
	DEBUG      | 2019-03-28 02:16:36,995 | asyncssh                  | logging.py          : 79 |             log() | [conn=0] Remaining auth methods: password,keyboard-interactive,publickey
	DEBUG      | 2019-03-28 02:16:37,001 | asyncssh                  | logging.py          : 79 |             log() | [conn=0] Trying password auth
	INFO       | 2019-03-28 02:16:37,125 | asyncssh                  | logging.py          : 79 |             log() | [conn=0] Auth for user demo succeeded
	DEBUG      | 2019-03-28 02:16:37,127 | asyncssh                  | logging.py          : 79 |             log() | [conn=0, chan=0] Set write buffer limits: low-water=16384, high-water=65536
	INFO       | 2019-03-28 02:16:37,127 | asyncssh                  | logging.py          : 79 |             log() | [conn=0, chan=0] Requesting new SSH session
	DEBUG      | 2019-03-28 02:16:37,136 | asyncssh                  | logging.py          : 79 |             log() | [conn=0, chan=0]   Initial recv window 2097152, packet size 32768
	DEBUG      | 2019-03-28 02:16:37,258 | asyncssh                  | logging.py          : 79 |             log() | [conn=0, chan=0]   Initial send window 0, packet size 65536
	INFO       | 2019-03-28 02:16:37,258 | asyncssh                  | logging.py          : 79 |             log() | [conn=0, chan=0]   Subsystem: sftp
	DEBUG      | 2019-03-28 02:16:37,381 | asyncssh                  | logging.py          : 79 |             log() | [conn=0, chan=0] Received window adjust of 131072 bytes, new window 131072


I believe your hunch is right in that something is overwriting the open_session method however running the lines in the python console (with the console started within the virtual environment), it works just fine! This is really interesting.....

**Comment by ronf** [comment]
> In other parts of my code, I SSH into devices instead of using SFTP and I use the SSH functionality like this:
> 
> ```python
>     self._conn = await asyncssh.connect(**self._connect_params_dict)  # type: SSHClientConnection
>     
>     self._stdin, self._stdout, self._stderr, self._session = await self._conn.open_session(
>         term_type='Dumb',
>         term_size=(200, 24))
> ```
> 
> In this case, is open_session() returning 4 values? This works just fine as well.

No - from what I can tell, this should never have worked. I checked not only AsyncSSH 1.15.1 but also versions going back multiple years, and SSHClientConnection.open_session() has always returned only three values (an SSHWriter and two SSHReaders). I can't find any case where it would have returned the session object as a fourth value, which is what the code you have here seems to be depending on. Channel and session objects are returned in a call to SSHClientConnection.create_session() from within open_session(), and these are passed as arguments to create the SSHReader/SSHWriter objects, but the session object is not returned directly.

If you move your log message into the AsyncSSH open_session() method itself just before it returns the values, does it still trigger? Can you confirm that the version of the open_session() code that you have looks like what I posted above?

**Comment by kpahawa** [comment]
Your hunch was spot on, deep in the recesses of our code base I found these lines after putting log statements all over the place:
   
    ```python
    @asyncio.coroutine
    def open_session(self, *args, **kwargs):            
        chan, session = yield from self.create_session(CoreSSHClientStreamSession,
                                                       *args, **kwargs)
    
        return (asyncssh.stream.SSHWriter(session, chan), asyncssh.stream.SSHReader(session, chan),
                asyncssh.stream.SSHReader(session, chan, asyncssh.constants.EXTENDED_DATA_STDERR))
    
    
    asyncssh.SSHClientConnection.open_session = open_session
    ```

Looks like that was the monkey patch...for some reason. Thanks again for your help. I think this makes a lot of sense now :)

**Comment by ronf** [comment]
Great - glad you found it!
