### ISSUE TITLE
[enhancement request] adding clear_recv_buf() method to SSHProcess

### ISSUE THREAD

**Issue by Ali-aqrabawi** [ronf/asyncssh#211]
it would be nice to have a  `clear_recv_buf()` method for `SSHProcess`:

    class SSHProcess
        def clear_recv_buf(self, datatype=None):
            self._recv_buf[datatype] = []

use case:
 in interactive shell, sometime you are preparing the session before start executing command,
usually the output that get's generated is not needed, so i would do `process.clear_recv_buf()`  before i start executing the interesting commands.

**Comment by ronf** [comment]
It's a bit more expensive, but you can already get an effect this today by calling collect_output() on the process. It will return all queued output without blocking to wait for more.

One benefit to that is that you get to see exactly what is being discarded, whereas with a clear function like this you'd never know what was cleared, and the other side might not be done sending output at the time the clear() function is called.

One other difference is that collect_output() will preserve any pending exception on the process. You might not want that to be discarded, as the underlying channel would generally not be usable once an exception is delivered and you'd probably want to see what the exception was that caused that.
