### ISSUE TITLE
Is the certificate required to use asyncssh?

### ISSUE THREAD

**Issue by kinow** [ronf/asyncssh#214]
Hi,

I am [testing](https://github.com/cylc/cylc-uiserver/issues/46) a JupyterHub [SSH Spawner](https://github.com/NERSC/sshspawner) which [uses asyncssh](https://github.com/NERSC/sshspawner/blob/07f690249333101c16fa5511426fff6b0a7dd378/requirements.txt#L1).

It does not specify the version, so I believe the version I used this morning was `1.16.1`. While testing it, it failed as my user had `id_rsa`, `id_rsa.pub`, `authorized_keys`, but not `-cert.pub` certificate.

The [readthedocs page](https://asyncssh.readthedocs.io/en/latest/#simple-server) mentions 

> (...) An SSH host certificate
># can optionally be provided in the file ``ssh_host_key-cert.pub``.

But further down also says

>To authenticate with SSH client keys or certificates, the server would look something like the following. Client and certificate authority keys for each user need to be placed in a file matching the username in a directory called authorized_keys.

So it looks like having the certificate is a requirement? If so, I will raise an issue to the SSH Spawner to document that requirement.

Thanks
Bruno

**Comment by ronf** [comment]
No - certificates are never required with AsyncSSH (or other SSH clients/servers). You have the option of authenticating with either a private/public key pair or a private key plus certificate containing a public key. It's up to the server to decide whether it trusts specific client public keys or if it trusts the public key of a certificate authority which signs a client-provided certificate.

Similarly, when evaluating known hosts, clients can be configured to either trust specific server host public keys or to trust the public key of a certificate authority which signs a server-provided certificate.

If you put the text in the client's id_rsa.pub file into an "authorized_keys" file on the server, public key authentication of the client should work without the need of any certificates. This is actually the common case.

**Comment by kinow** [comment]
Brilliant, I will re-run the complete set up from scratch as I had another issue with that spawner, and try to get exactly where I got the error. Then if there is nothing related with asyncssh will close this issue and open a new one in the spawner repository.

Thanks @ronf !

**Comment by kinow** [comment]
Found it. It appears to be a [requirement in the spawner](https://github.com/NERSC/sshspawner/blob/07f690249333101c16fa5511426fff6b0a7dd378/sshspawner/sshspawner.py#L263) to have the certificate. Thanks again, closing issue :+1:

**Comment by ronf** [comment]
You're right. As written, spawner does require a certificate. If the filename of the private key file was passed instead (without calling read_private_key or read_certificate), AsyncSSH would automatically use the cert if present or use just the private/public key pair if not. However, there would also likely be changes required on the other end to explicitly trust individual keys rather than a common certificate authority key, and I don't know if that would be an option here.
