### ISSUE TITLE
Home assistant Issue with asuswrt

### ISSUE THREAD

**Issue by roblandry** [ronf/asyncssh#218]
Im am not sure if this issue is due to asuswrt or not, but figured I would post the traceback incase the error belongs here. On restart of home assistant, this is in the logs:

```
/usr/local/lib/python3.7/site-packages/asyncssh/crypto/ec.py:176: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  return pub.encode_point()
/usr/local/lib/python3.7/site-packages/asyncssh/crypto/ec.py:182: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self._priv_key.curve, peer_public).public_key(backend)
/usr/local/lib/python3.7/site-packages/asyncssh/crypto/ec.py:144: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  public_value)

```

The home assistant issues involving a similar error can be found here:
https://github.com/home-assistant/home-assistant/issues/21626
https://github.com/home-assistant/home-assistant/issues/23982

**Comment by ronf** [comment]
This appears to be an older version of AsyncSSH -- the calls to encode_point were removed earlier this year. I think the change was probably somewhere around version 1.15.1.

Do you know which version of AsyncSSH is installed there?

**Comment by roblandry** [comment]
Looking here:
https://github.com/kennedyshead/aioasuswrt/blob/master/setup.py

Looks like asyncssh==1.15.0

**Comment by ronf** [comment]
Ok - that would explain it. Upgrading to 1.15.1 or later should solve it. The latest version is currently 1.17.0.
