### ISSUE TITLE
conn.run doesn't work

### ISSUE THREAD

**Issue by MarkAntipin** [ronf/asyncssh#223]
I'm trying to check how much space i have on my remote server, so i'm using 'df' command.
But i have no idea why i can't run it with asyncssh.

Only one command witch i can run is 'ls'.
That is what i'm trying to do:

`res = await conn.run('df')
print(res.stdout)`

and i get:
 _Command not found_

But! when i'm trying:
`res = await conn.run('ls')
print(res.stdout)`
I get:
_cache
datasets
dvc-cache
home
..._

Here is full code:

```
import asyncssh

client_key = asyncssh.read_private_key(RSA_KEY)
```

    async with asyncssh.connect(
        client_factory=None,
        host=SERVER_HOST,
        username=SERVER_USERNAME,
        port=SERVER_PORT,
        client_keys=[client_key]
    ) as conn:
        res = await conn.run('df')
        print(res.stdout)`

**Comment by ronf** [comment]
This doesn't appear to be an issue with AsyncSSH. It looks like perhaps you either don't have 'df' installed on the remote system or you have it installed but it isn't in the default path when you connect to the system using SSH.

If you run "ssh SERVER_HOST df" using the OpenSSH client, does it work? If you try specifying the full path to "df" on the remote system in the AsyncSSH call, does that work?

**Comment by MarkAntipin** [comment]
Yes, when i run  "ssh SERVER_HOST df" it works. Actually I still have not figured out the reason for this behavior. And when i try to connect with paramico 'df' works. In that case i thought that it it is asyncssh problem.
Anyway, sorry if it was my problem

**Comment by ronf** [comment]
If OpenSSH and Paramiko work but AsyncSSH doesn't, I'd be happy to try and help you debug it further. The problem still feels like it is something on the server side, but if we can get to the bottom of what AsyncSSH is doing differently when making the request, there might be a workaround, or there might be a default I can change in AsyncSSH to make it more consistent with other clients.

If you replace "df" with "echo $PATH" and run that with OpenSSH, Paramiko, and AsyncSSH, what results do you get? Also, on the remote system, what do you get when you do "which df" or "whereis df"?
