### ISSUE TITLE
SFTP server auth with username and password

### ISSUE THREAD

**Issue by MattiaFailla** [ronf/asyncssh#230]
Hi!
That's [my code](https://gist.github.com/MattiaFailla/dc31bc221468cfded6dfc6b29b4ec66f) for an SFTP server.

when I try to connect via Filezilla raise the following error is raised: 
```
Error:	Disconnected: No supported authentication methods available (server sent: )
Error:	Connection to the server impossible
```

I want to auth the users only via username and password. Where am I wrong?

**Comment by ronf** [comment]
There are a few different problems here. The main one is that you are putting the methods that belong in an SSHServer subclass into your SFTPServer subclass. These are two different classes. While you could in theory have a single class serve both purposes, it would be cleaner to keep them separate and have each inherit from only a single parent class.

Also, you are missing some imports for the "crypt" and "os" modules.

Here's a cleaned up version of your example code:

```python
import asyncio, asyncssh, crypt, os, sys

"""
This will use the same SFTPServer instance when performing file I/O for both SFTP and SCP requests. For instance:
"""

passwords = {
    'guest': '',                 # guest account with no password
    'user123': 'qV2iEadIGV2rw'   # password of 'secretpw'
}

class MySFTPServer(asyncssh.SFTPServer):
    def __init__(self, conn):
        print('begin_auth for new user.')
        root = '/tmp/sftp/' + conn.get_extra_info('username')
        os.makedirs(root, exist_ok=True)
        super().__init__(conn, chroot=root)

class MySSHServer(asyncssh.SSHServer):
    def connection_made(self, conn):
        print('SFTP connection received from %s.' %
                  conn.get_extra_info('peername')[0])

    def connection_lost(self, exc):
        if exc:
            print('SSH connection error: ' + str(exc), file=sys.stderr)
        else:
            print('SSH connection closed.')

    def begin_auth(self, username):
        # If the user's password is the empty string, no auth is required
        return passwords.get(username) != ''

    def password_auth_supported(self):
        return True

    def validate_password(self, username, password):
        pw = passwords.get(username, '*')
        return crypt.crypt(password, pw) == pw

async def start_server():
    await asyncssh.create_server(MySSHServer, '', 8022,
                                 server_host_keys=['ssh_host_key'],
                                 #authorized_client_keys='ssh_user_ca',
                                 sftp_factory=MySFTPServer,
                                 allow_scp=True,
                                 keepalive_interval=10)

loop = asyncio.get_event_loop()

try:
    loop.run_until_complete(start_server())
except (OSError, asyncssh.Error) as exc:
    sys.exit('Error starting server: ' + str(exc))

loop.run_forever()
```

**Comment by MattiaFailla** [comment]
Nice! Thanks!

Is there any way to gather extra information like number of connected users with username, total transfer data, etc.?

**Comment by ronf** [comment]
Yes, there are various ways to do this.  There's a callback on the SSHServer class called auth_completed() which you could use to hook when authentication completes, calling conn.get_extra_info('username') to get the authenticated username. If you want to remove users from the list when they disconnect, you can implement connection_lost() on your SSHServer class.

To track transfers of data, you could add code to your SFTPServer class. More specifically, you could add code to the read() and write() methods to count bytes transferred, using super() to call the original implementation and then incrementing counters for the number of bytes successfully read or written.

On the client side, there's a progress_handler argument which is designed specifically to track transfer progress when you use the high-level functions that take care of doing all the I/O for you. This handler is called after each transfer, so you can track total bytes transferred in real time on a per-file basis.

**Comment by MattiaFailla** [comment]
Many thanks!
