### ISSUE TITLE
Parsing of known_host failed on Debian 10/ OpenSSL 1.1.1c

### ISSUE THREAD

**Issue by rkrell** [ronf/asyncssh#232]
OS: Debian 10 (Buster)
OpenSSL: 1.1.1c
AsyncSSH: 1.17.1

I have a _.ssh/known_hosts_ file with the following contents:
```
|1|Jsx4/c+VDq8Wqa2DozImyg7z7cA=|ifGAYAs/xYfcVHc7rNPo73oeLZ4= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMmIyO5YvncxrzJB3RjIhhuY42gEs3XPlMNC2EQXdafN
```
This file has been automatically generated when opening an sftp connection in the terminal and confirming the remote host to be trusted. From that on, I can connect by sftp from the command line without any trouble.

During connecting by _AsyncSSH_, I get the following stacktrace:
```Traceback (most recent call last):
  File "/home/rkrell/work/sftp_test.py", line 53, in <module>
    raise exc
  File "/home/rkrell/work/sftp_test.py", line 51, in <module>
    asyncio.get_event_loop().run_until_complete(run_client())
  File "/home/rkrell/work/pypy3.5-7.0.0-linux_x86_64-portable/lib-python/3/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/home/rkrell/work/pypy3.5-7.0.0-linux_x86_64-portable/lib-python/3/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/home/rkrell/work/pypy3.5-7.0.0-linux_x86_64-portable/lib-python/3/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/rkrell/work/sftp_test.py", line 38, in run_client
    options=opts
  File "/home/rkrell/work/site-packages/asyncssh/misc.py", line 192, in __aenter__
    self._result = yield from self._coro
  File "/home/rkrell/work/site-packages/asyncssh/connection.py", line 5751, in connect
    'Opening SSH connection to'))
  File "/home/rkrell/work/site-packages/asyncssh/connection.py", line 167, in _connect
    yield from conn.wait_established()
  File "/home/rkrell/work/site-packages/asyncssh/connection.py", line 1948, in wait_established
    yield from self._waiter
  File "/home/rkrell/work/pypy3.5-7.0.0-linux_x86_64-portable/lib-python/3/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/home/rkrell/work/pypy3.5-7.0.0-linux_x86_64-portable/lib-python/3/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/home/rkrell/work/pypy3.5-7.0.0-linux_x86_64-portable/lib-python/3/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/home/rkrell/work/site-packages/asyncssh/connection.py", line 764, in data_received
    while self._inpbuf and self._recv_handler():
  File "/home/rkrell/work/site-packages/asyncssh/connection.py", line 985, in _recv_packet
    processed = handler.process_packet(pkttype, seq, packet)
  File "/home/rkrell/work/site-packages/asyncssh/packet.py", line 215, in process_packet
    self._packet_handlers[pkttype](self, pkttype, pktid, packet)
  File "/home/rkrell/work/site-packages/asyncssh/kex_ecdh.py", line 117, in _process_reply
    host_key = self._conn.validate_server_host_key(host_key_data)
  File "/home/rkrell/work/site-packages/asyncssh/connection.py", line 2520, in validate_server_host_key
    raise HostKeyNotVerifiable(str(exc)) from None
asyncssh.misc.HostKeyNotVerifiable: Host key is not trusted
```

During debugging, I found that this is due to an empty internal list of known hosts, thus the file contents of _.ssh/known_hosts_ have not been acknowledged.

Is this format supported?

**Comment by rkrell** [comment]
The workaround is of course to override validating the server host key, but anyway, I'd appreciate an explanation whether this known_hosts format is supported or what I might do wrong.

This code works:
```python
class SSHTrustingClient(SSHClient):
    def validate_host_public_key(self, host, addr, port, key):
        return True


def create_trusting_client() -> SSHClient:
    return SSHTrustingClient()


async def run_client():

    sftp = ...  # type: SFTPClient

    opts = SSHClientConnectionOptions(
        client_factory=create_trusting_client,
        client_keys=CLIENT_KEY_FILE,
        username=SERVER_USER,
        password=None,  #  Do not permit password authentication
        #known_hosts='/home/rkrell/test/sftp-python-example/known_hosts'
    )
    async with asyncssh.connect(
            SERVER_HOST, SERVER_PORT,
            options=opts
    ) as conn:
        async with conn.start_sftp_client() as sftp:
            await sftp.chdir(SFTP_REMOTE_DIR)
            print(await sftp.getcwd())
            await sftp.get('example.txt')

try:
    asyncssh.set_log_level(logging.DEBUG)
    asyncssh.set_sftp_log_level(logging.DEBUG)    
    asyncssh.set_debug_level(2)

    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    raise exc
```

**Comment by ronf** [comment]
Yes - the "|1|" style of known hosts entries should be supported by AsyncSSH. It is a "hashed" entry to try and hide which specific host it is associated with. Since it is hashed, though, the hostname or IP address and port you pass in to AsyncSSH must _exactly_ match the hostname used when the entry was first created (by "sftp" in your case). What host/port are you trying to use here, and what did you use the same in "sftp" command?

By the way, a simpler workaround for this would be to pass in "known_hosts=None" to disable the known hosts check - there's no need to create  a custom SSHClient class. However, both that and what you are doing here leaves you open to man-in-the-middle attacks, so I wouldn't recommend sticking with that long-term.

**Comment by rkrell** [comment]
> Yes - the "|1|" style of known hosts entries should be supported by AsyncSSH. It is a "hashed" entry to try and hide which specific host it is associated with. Since it is hashed, though, the hostname or IP address and port you pass in to AsyncSSH must _exactly_ match the hostname used when the entry was first created (by "sftp" in your case). What host/port are you trying to use here, and what did you use the same in "sftp" command?

This is an internal hostname I cannot tell, but anyway, I will have a look at it and try this again by ensuring having exactly the same hostname. Very useful information, I didn't know exactly this is just a hash.

> By the way, a simpler workaround for this would be to pass in "known_hosts=None" to disable the known hosts check - there's no need to create a custom SSHClient class. However, both that and what you are doing here leaves you open to man-in-the-middle attacks, so I wouldn't recommend sticking with that long-term.

In fact, the code
```
    opts = SSHClientConnectionOptions(
        client_keys=CLIENT_KEY_FILE,
        username=SERVER_USER,
        password=None,  #  Do not permit password authentication
        known_hosts=None
    )
```
worked also, without defining an overriding `SSHClient`

Thanks for your detailed answer.
