### ISSUE TITLE
dealing with StrictHostKeyChecking in cloud environments?

### ISSUE THREAD

**Issue by jmccarrell** [ronf/asyncssh#237]
# Description

First of all, thanks for asyncssh.  It is super cool.

In the cloud environment many of us operate in, the mapping of hostname to IP address is not stable, and is in the control of the cloud provider.

So when building tools / utilities that should just work, as I am trying to do, the issue of how to cope with known_host checking and verification comes up.  In my environment, my tooling needs to deal with at least these 3 cases:

- there is a match in the users `known_hosts` file for the ssh target, and it identifies the target
- there is a match in `known_hosts` for an IP address that has been recycled at some time in the past and is being reused by the cloud provider.
- there is no match in `known_hosts`

In the OS level ssh, specifying `StrictHostKeyChecking=no` provides a work around for this issue.

I have searched the `asyncssh` docs and sources, but don't currently see anything that suggests to me that `StrictHostKeyChecking` is supported.

So I am looking for advice here.  

# What is working now

Currently, my tool which reports a per-host sha with asyncssh is *very* simple:

``` python
    try:
        async with asyncssh.connect(host) as conn:
            ssh_result = await conn.run(sha_cmd)
            if ssh_result.exit_status == 0:
                sha = ssh_result.stdout.strip()
            else:
                sha = ssh_result.stderr.strip()
    except Exception as e:
        sha = str(e)
        
    return HostSha(host, sha)
```

this approach gives 2 classes of results:

```
hosta.example.com: Host key is not trusted
hostb.example.com: 78293c55c49ae74722e9030c1082253259481617
```

# the ask

How would you recommend I approach a solution here?

I can see: 
1. code up a interactive ssh session that can read the 3 variants of known_hosts interactions?
2. somehow configure the ssh client to ignore the host validation, maybe via `SSHClientConnectionOptions`?

Any pointers welcome.

And thanks again for providing asyncssh.  I am a fan.

**Comment by ronf** [comment]
Thanks for your kind words - I'm glad you like AsyncSSH.

Regarding host key checking, AsyncSSH today basically always operates in the equivalent of StrictHostKeyChecking=yes, unless you go out of your way to disable this checking by passing in an argument of "known_hosts=None", in which case host key checking is completely disabled. AsyncSSH doesn't directly support any of the modes where it interactively prompts you for whether to accept an unknown host key, and never automatically adds anything to the user's known_hosts file. However, there are callbacks you can define on your SSHClient object to provide additional functionality like this if you want it, or you can use these to implement your own matching mechanism.

Specifying "known_hosts=None" should allow you to connect even when the host key is unknown and may be good enough for what you need here, but unlike OpenSSH's "StrictHostKeyChecking=no",  it won't add unknown keys to the user's known_hosts file. I'm not sure if that's something you want or not.

If you want that, you can implement validate_host_public_key() and/or validate_host_ca_key() on SSHClient and these functions will be called with the host key or CA provided by the server to let you validate the key yourself, and you'd have the option in that callback to modify the user's known_hosts file if you wanted to. You can even use the AsyncSSH match_known_hosts() function from within these callbacks to do the default matching against what's in the file so you don't have to implement that yourself. By controlling whether you pass in a host name or IP address, you could even distinguish what type of match was found (host or IP), if you need to know that.

More documentation is available at https://asyncssh.readthedocs.io/en/latest/api.html#sshclient. Take a look at the section named "Host key validation handlers". If you have further questions about this, feel free to ask.

**Comment by jmccarrell** [comment]
Thanks much for the info.  

I indeed do not care about updating `known_hosts`, so simply passing in `known_hosts=None` solved this use case for me.

Like this:
```python
        async with asyncssh.connect(host=host, known_hosts=None) as conn:
```

**Comment by ronf** [comment]
Yeah - that should work. Just keep in mind that disabling this checking means you are opening yourself up to a man-in-the-middle attack.

**Comment by jmccarrell** [comment]
Understood, and thanks for the heads up.

For this use case, the machines are not exposed to the public internet; all of this traffic can only be routed over VPN tunnels.  So the trade off here is acceptable to us.
