### ISSUE TITLE
make "-cert.pub" configurable

### ISSUE THREAD

**Issue by toyg** [ronf/asyncssh#238]
`load_keypairs()` should really have an optional `suffix` parameter, which can be defaulted to `-cert.pub`. The classic convention for key generation gives you keys ending with just `.pub`, so at the very least it should be configurable.

**Comment by ronf** [comment]
The ".pub" and "-cert.pub" files are completely different things. The ".pub" is a public key, and is never needed when loading a key pair as the private key file contains a superset of what's in the corresponding ".pub" public key file. So, you never need to provide a public key file when calling load_keypairs().

The "-cert.pub" file, on the other hand, is a certificate which has signed a public key file using some other CA (certificate authority) private key. If you wish the other side of the SSH connection to validate your key using the corresponding CA public key, you need to pass both your private key and the corresponding certificate file as a tuple to load_keypairs(), or let it find this certificate file automatically by passing in a filename for the private key and using the usual convention of the certificate being in a file with a "-cert.pub" suffix.

**Comment by toyg** [comment]
In that case, how do I get the comment that is only available in .pub? If I load the private key alone, it is never populated.

>

**Comment by ronf** [comment]
If you store private keys in OpenSSH format (which is the default when writing keys from AsyncSSH), you can store a comment in the key file that will be accessible when you later load that key back in. If you use other formats like PKCS#1 or PKCS#8, though, you're right that the comment is not preserved in the private key file. It would only be available in the public key file in that case.

If you need access to the comment and you are unable to use OpenSSH format for some reason, you can load the private and public keys separately and then copy the comment over into the private key object by using set_comment(pub key.get_comment()), or just keep the public key object around for when you need to look at the comment. However, it's much easier to just write it out as part of the private key by using OpenSSH format.

**Comment by toyg** [comment]
Thank you, that matches what I'm seeing. It would be still nice to have something where I can throw private and public key, regardless of source format, and have it all in one place, but I guess I'll make do.

**Comment by ronf** [comment]
I spent some time on this over the weekend. It was a bit more complicated that I was hoping for, but load_keypairs() is now capable of accepting either certificates or public keys as the second argument in a tuple, and it will also automatically look for public key files with the '.pub' suffix when the private key is being read from a file. When deciding which comment to use for a loaded keypair, the order of preference is:

  * Private key comment
  * Certificate comment, in cases where a certificate is paired with a key
  * Public key comment, if a public key is available
  * File name of private key file, if it was loaded via a filename and no other comments are set

This is now available in the "develop" branch as commit 29bdda5.
