### ISSUE TITLE
data should be bytes

### ISSUE THREAD

**Issue by sharow** [ronf/asyncssh#24]
Currently `data_received(self, data, datatype)` is giving str,
and it is decoded by `session_encoding`. default is utf-8.
however I think data should be bytes or bytearray.

### reason 1
for examaple

```
# test.py
import sys
import random
import time

data = 'あいうえお'.encode('utf-8')

while True:
    r = random.randint(0, len(data))
    sys.stdout.buffer.write(data[:r])
    sys.stdout.buffer.flush()
    time.sleep(0.5)
    sys.stdout.buffer.write(data[r:])
    sys.stdout.buffer.flush()
    sys.stdout.buffer.write(b'\r\n')
    sys.stdout.buffer.flush()
```

server is https://gist.github.com/sharow/809242c0c12d66d0594f
```
# client run:
python test.py | ssh -o StrictHostKeyChecking=no -p 2200 test@x.x.x.x
```

and server say
```
SSH connection received from x.x.x.x
あいうえお
あいうえお
あいうえお
あいうえ
Exception in callback SSHConnection._cleanup(DisconnectErr...ecode error',))
handle: <Handle SSHConnection._cleanup(DisconnectErr...ecode error',))>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/site-packages/asyncssh/connection.py", line 394, in _cleanup
    self._owner.connection_lost(exc)
  File "simple_server.py", line 31, in connection_lost
    raise exc
  File "/usr/lib/python3.4/site-packages/asyncssh/connection.py", line 473, in data_received
    while self._inpbuf and self._recv_handler():
  File "/usr/lib/python3.4/site-packages/asyncssh/connection.py", line 694, in _recv_packet
    processed = self.process_packet(pkttype, packet)
  File "/usr/lib/python3.4/site-packages/asyncssh/packet.py", line 161, in process_packet
    self.packet_handlers[pkttype](self, pkttype, packet)
  File "/usr/lib/python3.4/site-packages/asyncssh/connection.py", line 1485, in _process_channel_msg
    chan.process_packet(pkttype, packet)
  File "/usr/lib/python3.4/site-packages/asyncssh/packet.py", line 161, in process_packet
    self.packet_handlers[pkttype](self, pkttype, packet)
  File "/usr/lib/python3.4/site-packages/asyncssh/channel.py", line 329, in _process_data
    self._accept_data(data)
  File "/usr/lib/python3.4/site-packages/asyncssh/channel.py", line 229, in _accept_data
    self._deliver_data(data, datatype)
  File "/usr/lib/python3.4/site-packages/asyncssh/channel.py", line 201, in _deliver_data
    'Unicode decode error') from None
asyncssh.misc.DisconnectError: Disconnect Error: Unicode decode error
```

payload is correct utf-8. data is arrived but divided sometime.
that mean.. session middleware shouldn't care about encoding.

### reason 2
encoding is depend on client. NOT SSH SEVER.

--
also paramiko channel.recv() is giving byte.

**Comment by ronf** [comment]
Thanks for this report!

Asyncssh provides an option to receive data as either bytes or str. If you want to receive bytes, simply pass encoding=None when setting up the SSH session. It also automatically defaults to encoding=None when setting up TCP port forwarding channels, though an encoding can be set on those if you like.

When an encoding is set, asyncssh currently assumes that both sides are aware of this encoding, and that SSH message boundaries will be on character boundaries. So, you can run into the problem you have documented here if you are using an application to do the encoding which is feeding data to ssh as a byte stream that doesn't preserve this. I should be able to fix this fairly easily. I already have code for that in another application that I've written in Python that processes byte streams coming from telnet and returns Unicode data. With the fix, partial Unicode bytes will simply not be delivered until additional data  is received over SSH which completes the character.

**Comment by sharow** [comment]
Thanks for your reply.

> If you want to receive bytes, simply pass encoding=None when setting up the SSH session.

Yes! that fine by me.

but I got this, with create_server(... , session_encoding=None, ...)
```
SSH connection received from x.x.x.x.
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 669, in _read_ready
    self._protocol.data_received(data)
  File "/usr/lib/python3.4/site-packages/asyncssh/connection.py", line 473, in data_received
    while self._inpbuf and self._recv_handler():
  File "/usr/lib/python3.4/site-packages/asyncssh/connection.py", line 694, in _recv_packet
    processed = self.process_packet(pkttype, packet)
  File "/usr/lib/python3.4/site-packages/asyncssh/packet.py", line 161, in process_packet
    self.packet_handlers[pkttype](self, pkttype, packet)
  File "/usr/lib/python3.4/site-packages/asyncssh/connection.py", line 1485, in _process_channel_msg
    chan.process_packet(pkttype, packet)
  File "/usr/lib/python3.4/site-packages/asyncssh/packet.py", line 161, in process_packet
    self.packet_handlers[pkttype](self, pkttype, packet)
  File "/usr/lib/python3.4/site-packages/asyncssh/channel.py", line 415, in _process_request
    self._session.session_started()
  File "simple_server.py", line 15, in session_started
    self._chan.get_extra_info('username'))
  File "/usr/lib/python3.4/site-packages/asyncssh/channel.py", line 631, in write
    self._send_buf.append((bytearray(data), datatype))
TypeError: string argument without an encoding
```

--

>asyncssh currently assumes that both sides are aware of this encoding, and that SSH message boundaries will be on character boundaries.

That is **original protocol**. text encoding is doesn't matter for [SSH protocol](https://tools.ietf.org/html/rfc4253) payload.

For personally, `SSHServer` must be session_encoding=None as default.
If that name is `SSHTextServer` then utf-8 as default is understandable.

Terminal's escape sequence is not part of text.
If I use openssh from terminal, it is not part of text(character) world.
I mean, pure-text-message is not majority use case.

--
Note:
if i use stream things(terminal, file, ..), wait for `complete character` is unnecessary.
It dosen't matter. because text is stream.

```
$ echo -ne '\xe3\x81\x82'
あ
$ echo -ne '\xe3' ; sleep 1 ; echo -ne '\x81' ; sleep 1 ; echo -e '\x82'
あ
```

**Comment by sharow** [comment]
sorry session_encoding=None is works fine.
it my simple wrong:
```
- self._chan.write('Welcome to SSH server')
+ self._chan.write(b'Welcome to SSH server')
```

**Comment by ronf** [comment]
Yes, as you discovered, you are only allowed to operate on bytes when you set encoding=None. You can't send or receive strings any longer. When you have an encoding set, you are allowed to send either strings or bytes, but you will always receive strings (decoded using the encoding you have set).

I just checked in a change which now properly handles cases where bytes making up a single Unicode character get split across successive SSH data packets when you have an encoding set. In this case, the character will be delivered only after all of its bytes have been received. Invalid encoding of data or a partial Unicode byte sequence just before EOF will still trigger a "Unicode decode error" DisconnectError, though.

As for the default, I chose to make text the default because it matches the default for the local stdin, stdout, and stderr in Python. People expect to read and write strings on these objects, and have to go out of their way to refer to objects like "sys.stdout.buffer" if they want to directly read & write bytes. I wanted to make it easy to do either, though, since SSH is not always used to carry textual data, and that's why I provided the encoding parameter when setting up a new session/connection.

**Comment by sharow** [comment]
I understand your decision.
Thank you.
