### ISSUE TITLE
U2F support

### ISSUE THREAD

**Issue by Snawoot** [ronf/asyncssh#240]
Hello,

Recently native support for authentication with U2F keys has [landed in OpenSSH](https://marc.info/?l=openssh-unix-dev&m=157259802529972&w=2). At this moment it has experimental status, but I don't expect any problems to appear because U2F is pretty mature, sound and already has wide adoption.

I wonder if you consider to implement this feature as well. At least server side support should be pretty much like authentication with ECDSA keys and from my understanding it'll not require to introduce additional dependencies.

**Comment by ronf** [comment]
I've been following the discussion about this on the OpenSSH mailing list, and it's definitely something I'm interested in adding. I'll probably wait until the OpenSSH version is available in a real release, though, to avoid any incompatible changes that might be introduced during development.

In terms of dependencies, there is currently an external dependency in the OpenSSH implementation on "libfido2", to actually interact with the U2F token. I'll need to either add a ctypes wrapper around that, or see if the "python-fido2" package can be used for this. There may be licensing complication around the latter, though, as I see part of python-fido2 is under the Mozilla Public License. I'm not sure offhand if there are any issues combining that with the Eclipse Public License. I also ran across a "pyu2f" package that could possibly be used, but I need to dig further into what functions are actually needed and what these libraries support.

**Comment by Snawoot** [comment]
I guess pyu2f is **not** the way to go because it supports only FIDO U2F 1.2 protocol: [https://github.com/google/pyu2f/blob/master/pyu2f/u2f.py#L71-L72](https://github.com/google/pyu2f/blob/master/pyu2f/u2f.py#L71-L72). Probably it's outdated.

`python-fido2` from Yubico (the same as `libfido2`) seems strictly superior and well maintained. Mozilla License seems to be related to public suffix list. Your package doesn't contain, distribute, sublicense, modify or link this file. Here is [OSS license compatibility matrix](https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses).

Also I'll let myself to outline: FIDO libraries are not needed for server side verification of signature. FIDO libraries are needed for client side to communicate with FIDO token. I believe `asyncssh` in client mode is used mostly for automation, but FIDO tokens require user presence to operate (my dongle requires to touch golden contact on it). Even if someone wants to alternative ssh client based on `asyncssh`, he still can use U2F key without direct FIDO support from `asyncssh` by mean of communicating with plain OpenSSH agent (as far as `asyncssh` supports forwarding new key type). Summarizing the talk, FIDO driver in `asyncssh` is needed in very narrow case of interactive ssh client without OpenSSH agent available. IMO communication with FIDO key is a last thing to think about; server-side implementation is much more useful. Like 95% of value of this feature can be delivered without FIDO host libraries at all.

**Comment by ronf** [comment]
You make a convincing argument. :)  While I generally like to go for full client and server support for most features, this might be an ideal candidate to do just the server support first, and then look into adding client support later.

I've managed to successfully compile the latest version of openssl-portable and libfido2 here. However, I don't currently have a U2F token to test with. I tried installed "Soft U2F" (a Mac soft token), and I did get it to work properly against demo.yubikey.com, but I'm getting a failure when I try running "ssh-keygen". I'm not sure if Soft U2F actually implements the newer protocol -- it may only support the older one.

Do you happen to know of any soft tokens which might work for this?

**Comment by Snawoot** [comment]
> I'm not sure if Soft U2F actually implements the newer protocol -- it may only support the older one.

I don't think it is the cause. I have old U2F token (Yubikey 4, FIDO U2F 1.2), which works perfectly with ssh-keygen (but only with ecdsa, not ed25519). I think in your case for some reason libfido2 fails to discover HID device emulated by Soft U2F. May be kernel module is missing or so.

Anyway, openssh-portable has U2F testsuite and it contains [`sk-dummy` library](https://github.com/openssh/openssh-portable/blob/master/regress/misc/sk-dummy/sk-dummy.c) which should work in place of `libsk-libfido2.so` without any additional components at all.

**Comment by ronf** [comment]
Ah, thanks! That worked great, both for creating keys and using them to authenticate with openssh-portable running on both sides.

I also placed an order for a Yubikey 5 NFC today. I'm hoping to be able to use it to not only test this new FIDO2 support but also the PKCS#11 PIV smart card support (as described at https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html).

I'm not sure why I couldn't get Soft U2F to work. I'll have to experiment further with that, but hopefully the real key should be here in a couple of days.

**Comment by ronf** [comment]
Quick update: I have serialization/deserialization for both private & public SK keys working in AsyncSSH, as well as support for reading and writing certificates that sign these keys and advertising all the right signature algorithms when these keys/certificates are used.

I also have a working Python ctypes wrapper around the sk_enroll/sk_sign API that I believe I should able to plug into libfido2 to do actual enrollment and signing, once I have a real Yubikey. In the meantime, I tested this successfully against sk-dummy and got back reasonable looking enrollment and signing responses, so I'm pretty close.

The last step is to actually build the signature verification code for the server side, and I have a pretty good sense of what I need to do there. I already have code that extracts the ECDSA/Ed25519 public key and the other fields needed to create the blob that the hardware signs. So, passing that into the existing ECDSA/Ed25519 code to verify the signature should be straightforward. I'm hoping to have a prototype working in a few days.

Thanks for all your help @Snawoot -- the pointers you provided were extremely helpful!

**Comment by cariaso** [comment]
this whole thread just makes me happy. This is like a crystalized perfect example of what open source collaboration can be.

**Comment by ronf** [comment]
Another update: I now have key enrollment, signing, and verification working for both ECDSA and Ed25519 SK keys, and I have tested this with both the "sk-dummy" provider from OpenSSH and the "libsk-libfido2" library talking to a real security key (Yubikey 5 NFC). This provider support is only needed if you want to do signing -- you can do verification without it. AsyncSSH will automatically try and find the provider, or you can pass in a pathname to it in the SSH_SK_PROVIDER environment variable.

I've also tested the AsyncSSH client and server against both itself and against OpenSSH-portable HEAD, confirming that they interoperate, and that I can use these new keys both directly and inside a certificate (both as the key being signed and the CA key doing the signing). This works with keys and certificates generated by ssh-keygen and when generating these keys and certificates from within AsyncSSH.

I've also tested enabling and disabling the "presence required" feature of the keys, and made this available as an optional argument to asyncssh.generate_private_key() when you pass in one of the SK algorithm names.

The main remaining work is to update my unit tests to get the code coverage back to 100% and add documentation for these new keys. After getting an initial version of this checked in, I'll circle back and look at what it takes to get SSH agent support working for these new keys.

Note: Unlike OpenSSH, I allow these new keys to be used as either user or host keys, and they can be used within both user and host certificates. When using them as a host key, you'd probably need to turn off the user presence requirement for a typical server deployment, but when opening reverse-direction SSH connections it would make sense to use them as a host key with presence required.

I did find one issue with OpenSSH related to trying to use a certificate containing a non-SK key signed by an SK CA key. This works fine when OpenSSH is the client, but seems to fail when it is the server, both when connecting to itself and when connecting from AsyncSSH. I've reported this back to the OpenSSH mailing list. This case works fine when AsyncSSH is the server.

**Comment by Snawoot** [comment]
> Unlike OpenSSH, I allow these new keys to be used as either user or host keys, and they can be used within both user and host certificates.

This is cool!

> After getting an initial version of this checked in, I'll circle back and look at what it takes to get SSH agent support working for these new keys.

I had an impression this is easiest part among all of this, I'm curious to see if it really is.

**Comment by ronf** [comment]
> > After getting an initial version of this checked in, I'll circle back and look at what it takes to get SSH agent support working for these new keys.
> 
> I had an impression this is easiest part among all of this, I'm curious to see if it really is.

It turned out that there was actually some complexity in getting SSH agent support to work, for a few different reasons. Switching to using the "constrained" add option with a new constraint providing the middleware library path wasn't difficult, but the documentation didn't provide all the details of the wire format in some cases (particularly when importing certificates), and there were a few inconsistencies between the doc and the current OpenSSH implementation. I've sent details about the issues I ran into to the OpenSSH list.

Also, as I did more testing, I discovered that some special-casing was needed when translating between the certificate algorithm name and the signature algorithm name used by the key inside the certificate, particularly in the agent case. In the past, this was always just a matter of stripping off the "-cert-v01@openssh.com" from the certificate algorithm name, but since the key algorithms end in "@openssh.com" in this case, that part needs to be preserved.

I have a feeling there may be some additional changes coming depending on what OpenSSH decides to do about a few of the items I reported, but if you'd like to start experimenting with this support, it is now available as commit fe757ea in the "develop" branch. Let me know what you think!

**Comment by Snawoot** [comment]
Good news: OpenSSH 8.2 has been released with U2F support: https://lists.mindrot.org/pipermail/openssh-unix-announce/2020-February/000138.html

**Comment by ronf** [comment]
Yeah, thanks - I saw that. That is good news!

Unfortunately, the middleware library OpenSSH was using in the pre-release is now bundled into OpenSSH itself rather than being part of libfido2. So, I can't easily call into that from AsyncSSH. When I saw that, I rewrote the AsyncSSH code to use the python-fido2 module instead, and I have that working. I just need to expand the unit tests a bit and I should have something I can release.

In the meantime, if you have the older version of the libsk-libfido2 library installed, the previous support I checked into the AsyncSSH "develop" branch appears to be fully compatible with the released version of this support in OpenSSH 8.2.

**Comment by ronf** [comment]
Ok - the updated version of the AsyncSSH U2F/FIDO2 support is now checked in as commit 8777c50 in the "develop" branch. This should be equivalent to what I previously checked in, but without a dependency on the C library "libsk-libfido2" that the previous version used. Instead, this version uses the Python fido2 package on PyPI, avoiding the problem that the "libsk" library is now folded into OpenSSH and not installed separately.

This version has been tested against OpenSSH 8.2 and so far everything looks good to me. It doesn't yet have support for the new OpenSSH 8.2 "resident keys" feature, though. I'll be looking into that next, but wasn't to get something out in the meantime.

**Comment by ronf** [comment]
Enhanced support for FIDO2 keys is now available in commit 3cafac0 in the "develop" branch. Changes include:

- A PIN can now be provided (if needed) when managing security keys
- Resident keys can now be created and loaded
- User and application names can now be set when generating keys
- Support has been added for "no-touch-required" in authorized_keys
- Support has been added for "no-touch-required" in OpenSSH certificates
- Unit tests have been expanded to cover certificates based on security keys, use of security keys as host keys, enforcement of no-touch-required, and a much greater number of error conditions.

If all goes well, I'm hoping to have an official release with this support out later today.

**Comment by ronf** [comment]
This support is now released in AsyncSSH 2.2.0!
