### ISSUE TITLE
Scaling asyncssh server (mainly sftp) via worker proccesses

### ISSUE THREAD

**Issue by cooperlees** [ronf/asyncssh#246]
Hi All,

This is more research to avoid re-inventing the wheel. Has anyone handed off asyncssh sftp connections to worker processes or another technique to get around the GIL and hitting 100% CPU in the one process with all the SSH encryption overhead?

Would love any example if anyone has one. I'd imagine I create my own `asyncssh.SFTPServer` sub class and create a worker pool in there and hand off connections from main process. Thoughts?

Thought in my head is based off apache2:
```
main_python_process (terminates TCP connection + hands to a worker)
  - worker 1: Setup encryption + authenticate + do transfer for X clients
  ...
  - worker X: ""
```
- I'd envision a round robin or weighted round robin to share the load.

**Comment by ronf** [comment]
I haven't specifically tried to do this, but my understanding is that you will need a separate asyncio event loop for each process you start up. Also, AsyncSSH _depends_ on all operations associated with any given connection being handled by the same event loop. However, it should be fine if you have multiple connections to farm those out across multiple event loops (potentially running in separate processes).

If you're running on Linux, one thing you might consider is taking advantage of "reuse_port" to open multiple SSH listeners on the same TCP port, leveraging the Linux's kernels behavior of automatically round-robining between the listening sockets when new connections arrive. This could be done by running completely independent instances of a Python script in their own processes which listen on the same socket, if you don't have any need to share any other state between them. Alternately, you could have a single Python script which used the multiprocessing module to set all this up, but you'd still want each process to get its own event loop and open its own SSH server instance (with reuse_port).

The reuse_port argument is already available in AsyncSSH's create_server() call, so you don't need to make any modifications to AsyncSSH to make this work.

**Comment by cooperlees** [comment]
Thanks for the tips @ronf. Will see how far I can push the one process but will try these tricks if I need to. Thanks!

Hope all is well!

**Comment by ronf** [comment]
I'm good - thanks. Nice to hear from you again!

I did a very quick test here of just adding "reuse_address=True" and "reuse_port=True" to my simple_scp_server.py example. Running on a 4-core Linux VM running in Parallels on my 8-core Mac with the SCP clients running native on the Mac and the servers running on the Linux VM, I saw the following rough numbers when transferring ten 100 MByte files in parallel:

1 SCP server instance: 497 MBytes/sec
2 SCP server instances: 733 MBytes/sec
4 SCP server instances: 1418 MBytes/sec

So, not a linear speed-up, but about a 2.85X gain going from a single core to four cores. In this testing, all four cores of the Linux VM were pegged at over 99% CPU at first. However, as some of the ten transfers finished, I saw that drop off somewhat. With a larger number of simultaneous transfers, I think this number might even get slightly better.

**Comment by cooperlees** [comment]
Thanks for testing Ron. I feel we should land this example and make notes in documentation somewhere that it's possible. 

I'll try get a PR up in the next few weeks. This will be helpful for others who hit limits in the future too!

**Comment by cooperlees** [comment]
Also, I would recommend using https://github.com/MagicStack/uvloop with your processes for event loop efficiency wins as well.

**Comment by ronf** [comment]
Good point about uvloop. AsyncSSH works just fine with that. Switching my test over to it (a one-line change) did improve the numbers noticeably:

1 SCP server instance: 554 Mbps
2 SCP server instances: 1043 Mbps
4 SCP server instances: 1813 Mbps
