### ISSUE TITLE
Intercept completed file `PUT` and obtain relative path from sftp root

### ISSUE THREAD

**Issue by cooperlees** [ronf/asyncssh#248]
I'm looking to intercept when a PUT finishes on an `asyncssh.SFTPServer`. I wish to do this so I can add that file path into an asyncio queue for some workers to upload the file elsewhere (think S3 bucket) for archival and remove from local disk.

Reading the code I see that the last method that knows the "path" is 
- `SFTPServerHandler._process_open`
From there it's all referred to by a handle ID. I can see it completes in
- `SFTPServerHandler._process_close`

I was thinking of SubClassing + monkey patching. In my sub class I'd create a dictionary mapping of:
- `self.dict[handleID] = "path"`in `MySFTPServerHandler._process_open`
Then:
- On error, just remove from the file from the mapping.
- On success, take the path in said dictionary and add it to my worker queue, (also removing from the mapping)

I can't see a cleaner way. Does anybody else? Open to adding an easier API here? Happy to contribute.

**Comment by ronf** [comment]
There shouldn't be any need to monkey-patch SFTPServerHandler. This sort of thing is exactly what the SFTPServer was designed to let you do (by subclassing it). I'm thinking you'd do something like:

```python
class MySFTPServer(asyncssh.SFTPServer):
    def __init__(self, chan, chroot=None):
        super().__init__(chan, chroot)

        self.pathdict = {}

    def open(self, path, pflags, attrs):
        """Keep track of the path associated with each open file"""

        file_obj = super().open(path, pflags, attrs)
        self.pathdict[file_obj] = path
        return file_obj

    def close(self, file_obj):
        """Process files after they are closed"""

        path = self.pathdict.pop(file_obj)

        # Process path here
        print(f'{path} ready for processing')
```

You may want to put in a check on pflags in open() if you want to limit this to only files being written, and in that case you'd probably need to add a try block around the pop() in close to skip anything not found in pathdict, but this should give you the basic idea.

**Comment by cooperlees** [comment]
This works as described. Thanks - Will close and open if I hit any actual issues, thanks Ron.
