### ISSUE TITLE
Question: Is it possible to combine SSH Server with Curses?

### ISSUE THREAD

**Issue by J-A-M-E-5** [ronf/asyncssh#251]
Does anybody have any basic example code?

Thanks in advance

**Comment by ronf** [comment]
If you're looking to have separate curses contexts for each inbound connection to the server, I'm afraid you're out of luck. I looked into this last year and found that curses heavily relies on global variables, such that you really can't have multiple curses contexts active at once. This is especially true of the Python curses module, which further limits you to only being able to initialize the curses context with sys.stdout and not supporting the curses "newterm" API, which in theory could allow you to initialize multiple terminals at once and switch between them.

It is possible to use terminal escape sequences with AsyncSSH -- the built-in line editor module in AsyncSSH is actually an example of that. For any ANSI-compatible terminal, you can use it to provide readline-like behavior when entering input, including redrawing the input line as you edit it or when new output comes out, and supporting things like input history. In fact, you'll get this behavior by default on any connection to an AsyncSSH server which requests a PTY.

**Comment by J-A-M-E-5** [comment]
Thanks for quick response Ronf, much appreciated.
