### ISSUE TITLE
Record session for testing

### ISSUE THREAD

**Issue by Syniex** [ronf/asyncssh#255]
Adding an option to "record" a session and simulate it later will be great.

This feature could help unittest projects using asyncssh.

**Comment by ronf** [comment]
Are you thinking of something like "tcpreplay", but for the unencrypted version of an SSH stream, where new keys are negotiated on the replayed session but then the data inside is replayed encrypted with the new keys. It seems more like an application one would write on top of AsyncSSH rather than a core feature of AsyncSSH itself, though. I can imagine this getting pretty complex if you wanted to be able to "edit" the data in the SSH stream to account for application-specific differences that you'd have to account for in order for the replayed data to be properly accepted by whatever target you point at. I also expect you might need some way to know when to read data from the server to prevent flow control from eventually breaking things, and that you might even need to extract data from the returned data stream to influence the edits you make in the replayed stream.

**Comment by Syniex** [comment]
I was thinking about keep the session output as text (in some format).
Then after this session was saved, using asyncssh ssh server (with configureable username/password) we will be able to simulate this session over and over again for unittesting.

Example:
1) login to linux server
2) send command (ps -ef) -> get results (use readuntil to know when the output is done?) - This will be saved as Key-Value so when we simulate the command we will receive this results

Maybe there is better way by just providing a format asyncssh will be able to read and act as server for key->value , Autonomous ->Random every X.

Something like:

```
[ps -ef]
www-data 32395  1073  0 00:00 ?        00:00:00 /usr/sbin/apache2 -k start
www-data 32396  1073  0 00:00 ?        00:00:00 /usr/sbin/apache2 -k start
www-data 32397  1073  0 00:00 ?        00:00:00 /usr/sbin/apache2 -k start
www-data 32398  1073  0 00:00 ?        00:00:00 /usr/sbin/apache2 -k start
www-data 32399  1073  0 00:00 ?        00:00:00 /usr/sbin/apache2 -k start
root     32507     2  0 00:09 ?        00:00:01 [kworker/8:2-memcg_kmem_cache]
root     32642     2  0 00:39 ?        00:00:00 [kworker/3:1]
root@localhost:~#

[top] -> repeat until ctrl+c
top - 07:33:42 up  7:56,  1 user,  load average: 0.09, 0.04, 0.01
Tasks: 271 total,   1 running, 270 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   1981.1 total,    519.0 free,    379.2 used,   1082.9 buff/cache
MiB Swap:   2048.0 total,   2040.2 free,      7.8 used.   1381.3 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  841 root      20   0   81872   3700   3340 S   0.3   0.2   0:03.91 irqbalance
 1490 root      20   0       0      0      0 I   0.3   0.0   0:00.52 kworker/7:4-events
 2264 root      20   0       0      0      0 I   0.3   0.0   0:02.62 kworker/u32:2-events_power_efficient
 4092 root      20   0    9360   3972   3144 R   0.3   0.2   0:00.01 top

[autonomous] - >random every X seconds
I am autonomous
I am second

```

**Comment by ronf** [comment]
Trying to use readuntil() to find the end of command output can be pretty unreliable. If the server supports it, you'd probably be better off running each command in a separate SSH channel, so it's clear when the command is done generating output. You could still potentially do the replay all in a single channel where you pretended it was an interactive shell session, but it's not clear how you'd handle commands which require input from the client before they finished.

Basing the replay on a manually generated configuration file like you suggest here seems like it would be a lot simpler, and something like that could easily be written as an application on top of AsyncSSH. That could easily support clients which connected either interval shell or exec style sessions where each command is run on a separate channel. You'd still need to have some way to represent when input was needed, though, and how much input to read. If you wanted to support something like choosing a response at random, you'd also need some syntax in the file for how you tell what the boundaries are between the different random responses.

**Comment by cariaso** [comment]
@Syniex your original request was to "record a session". As I imagine my own use of that, I think I'd want to be able to record my manual usual command line ssh sessions.
This is akin to a command line selenium, allowing me to 'record' and then 'playback'. 

record would generate a log
playback would read that log, and executes it, perhaps via asyncssh.

I'd also want some way to edit that log.

While reading https://nullsweep.com/a-better-way-to-ssh-in-aws/ I noticed the phrase.
"Full SSH session logging is simple to enable (I actually recommend disabling this unless you really need it to avoid storing sensitive information in these logs)"

I'm curious if that log, would sufficiently capture what you need for replay?

would the logs generated by
https://github.com/cloudposse/sudosh
be sufficient?

if so, being able to read either as inputs to your imagined tool might be useful.
if not, what details are missing, for your purposes?
