### ISSUE TITLE
SSH command send to Cisco ASA hangs on command execution

### ISSUE THREAD

**Issue by settlej** [ronf/asyncssh#267]
```
import asyncio, asyncssh, sys, selectors
import time

async def run_client():
    async with asyncssh.connect('192.168.*******', username='*****', password='*****', known_hosts=None) as conn:
        result = await conn.run('show inventory\n')
        print(result.stdout)

try:
    a = time.time()
    asyncio.get_event_loop().run_until_complete(run_client())
    b = time.time()
    print('time to complete=' + str(b-a))
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))

```
PS C:\Users\xxxx> & "C:/Program Files/Python37/python.exe" c:/Users/xxx/asyncsshtest.py
User xxx logged in to C0xxx-FW01
Logins over the last 91 days: 71.  Last login: 20:53:08 UTC Mar 12 2020 from 192.168.254.6
Failed logins since the last login: 0.  Last failed login: 17:42:32 UTC Mar 12 2020 from 192.168.254.6
Type help or '?' for a list of available commands.
C0xxx-FW01# **show inventory**
Name: "Chassis", DESCR: "ASA 5525-X with SW, 8 GE Data, 1 GE Mgmt, AC"
PID: ASA5525           , VID: V06     , SN: FTX213xxx

Name: "Storage Device 1", DESCR: "Model Number: Micron_M600_MTFDDAxxxMBF"
PID: N/A               , VID: N/A     , SN: MSA21xxx

C0xxx-FW01#
time to complete=**300.2091748714447**

Python 3.8.2 and 3.7.6 on windows 10.  

SSH to normal router response fast.

**Comment by settlej** [comment]
![image](https://user-images.githubusercontent.com/53984619/76568445-17ff2a00-646e-11ea-8f4a-1ed9a394c54d.png)

The debug show the return of the command output, but it just sits there doing nothing untill 300 seconds.

**Comment by ronf** [comment]
From your trace, it would appear that the Cisco ASA is not actually sending EOF or closing the channel after running your command. Instead, it is outputting a prompt and probably waiting for additional command input. I wouldn't expect that, since you are passing the command to run in the call to run(). On most SSH servers, that runs the command you specify and then closes the channel when the command completes. Since that's not happening here, though, you are waiting for additional output and the ASA is waiting for you to provide additional input.

To work around this, you could perhaps try adding `stdin=asyncssh.DEVNULL` to the arguments to run(), so you are letting the ASA know you aren't going to provide any more input. Hopefully, this will cause it to close its end of the connection as soon as it is done generating all the output from the command you ran. There might still be an extra prompt showing up in the command's output, but you could strip that off if you wanted to after run() returns.

I'm guessing the 300 seconds here is the inactivity timeout configured on the ASA, so it closes the connection after waiting that long and not getting any additional input.

**Comment by settlej** [comment]
Yeah I figured the 300 seconds was the timeout for the firewall.  I tried the DEVNULL per your suggestion but the command output either gets cut during return or doesn't finish at all.  Is there a way to have a timeout if no EOF by so many seconds?

**Comment by ronf** [comment]
Yes - you can use asyncio.wait_for() to set a timeout. It would look something like:

```
    async with asyncssh.connect('localhost') as conn:
        proc = await conn.create_process('show inventory')

        try:
            await asyncio.wait_for(proc.wait_closed(), timeout=1)
        except asyncio.TimeoutError:
            pass

        stdout, stderr = proc.collect_output()
```

One thing I noticed as I wrote this is that you have a '\n' after 'show inventory' in your example. You shouldn't need that when you pass in a command to run. If you remove that, do you still run into the issue of the ASA not closing the connection after running the command?

The only time you should need to put a '\n' like that is if you open a channel without passing in a command and then you later write the command to the channel yourself or make the command part of the data you provide via stdin.

**Comment by ronf** [comment]
After thinking about this a bit, I decided this seems like a common enough use case that it might be useful to build the timeout capability into the SSHClientProcess.wait() and SSHClientConnection.run() method. I created a new asyncssh.TimeoutError class which is a subclass of both asyncssh.ProcessError and asyncio.TimeoutError, and added an optional `timeout` argument you can use when waiting for processes to finish. This is now available in the "develop" branch as commit 5179ffa. With this change, the above example can be simplified down to something like:

```python
    async with asyncssh.connect('localhost') as conn:
        try:
            result = await conn.run('show inventory', timeout=1)
        except asyncssh.TimeoutError as exc:
            result = exc
```

SSHCompletedProcess and ProcessError are different classes, but they provide access to the same set of member variables, so the TimeoutError exception (a subclass of ProcessError) can actually be used in place of the SSHCompletedProcess result when the timeout fires. However, in a real-world example, you'd probably want to do slightly different things in the "except" block than you would when the call succeeds, and so you'd probably end up with something like a try..except..else block.

**Comment by settlej** [comment]
Thanks for adding the new feature!  Yes having multiple devices respond differently warrants the feature capability.  The wait_for method you suggested did work.  I did figure a more guarantee method using the user/device prompt that is ASA ends with, I based the method on the 'Interactive input' example in the API documentation.  
```        
        async with conn.create_process() as process:
            await process.stdout.readuntil('Cxxx-FW01#')
            process.stdin.write('show inventory\n')
            result = await process.stdout.readuntil('Cxxx-FW01#')
            print(result)```

**Comment by ronf** [comment]
I'm glad to hear that wait_for() worked. I agree that readuntil() is probably a better approach, though, as it doesn't requiring trying to guess a timeout value that's long enough for all the output to be collected, and readuntil() will return more quickly. The only caveat is that you need to make sure the commands you are running will never have the prompt string you are looking for appearing in their output.
