### ISSUE TITLE
invoking a shell

### ISSUE THREAD

**Issue by Reitz86** [ronf/asyncssh#280]
Hello,

i'm currently working on a embedded device that supports some kind of ssh. Using threaded paramiko. Currently im opening a channel by invoking a shell and wait for the prompt ">" and then send my command.

```python
channel = client.invoke_shell(term="vt100")
response = str(channel.recv(MAX_BUFFER))
if  str(response)[-2:-1] != ">":
  return
channel.sendall(f"{command}\r")
```

Now i'm trying the code that @ronf posted in issue-70:
```python
import asyncio, asyncssh, sys

async def run_client():
    async with asyncssh.connect('localhost') as conn:
        await conn.run(term_type='xterm', stdin=sys.stdin,
                       stdout=sys.stdout, stderr=sys.stderr)

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```
While i'm getting the prompt printed to stdout, theres not response if i enter any of the supported commands (doesnt matter if i attach \r\r\n or any other newline combinations to it).

**Comment by ronf** [comment]
How are you providing the input? The example of mine you're using expects the input to come from stdin. Is that how you're feeding it?

Also, note that the run() method will keep on running until the shell exits. That doesn't seem to happen when you hit EOF on stdin in the case where you have requested a PTY. So, you might want to try removing the "term_type=xterm". That will also have the benefit of not echoing back your command input in the output.

If the input you want to feed it is static, there are probably better ways to do this than redirecting stdin. For instance, you can use the 'input' argument to run() instead. If you only want to run a single command, you can also just provide that command directly in the run() call, such as:

```python
    await conn.run('ls abc*', stdout=sys.stdout, stderr=sys.stderr)
```

**Comment by Reitz86** [comment]
Cheers for the fast reply. If I use the run command you provided, I get
`SSH connection failed: Session request failed`
immediately :(

**Comment by ronf** [comment]
Ok - that suggests that the device you are contacting only supports shell sessions and not exec sessions. In that case, I would try something like:

```python
    await conn.run(input='ls abc*', stdout=sys.stdout, stderr=sys.stderr)
```

**Comment by Reitz86** [comment]
Now i'm getting
`2020/05/17 07:03:49 socat[22727] E tcgetattr(0, 0xbed84720): Inappropriate ioctl for device`

**Comment by ronf** [comment]
Yeah - adding back the term_type should fix the tcgetattr error as you said.

If you're still not seeing it execute the command, try adding '\r' or '\n' to the end of the "input" string. If that still doesn't work, my guess is that maybe you need to delay until you add the shell prompt before you send that input, like you were doing in the Paramiko case. To do that, you'll need to switch from using run() to using create_process() or open_session(), so you split apart starting up the session from doing the I/O.

Here's an example of doing this with open_session(), where you can run multiple commands and get the output back within Python for each:

```python
import asyncio, asyncssh, sys

async def read_response(reader, separator='>'):
    response = []

    while True:
        try:
            response.append(await reader.readuntil(separator))
            break
        except asyncio.IncompleteReadError as exc:
            if exc.partial:
                response.append(exc.partial)
            else:
                break

    return ''.join(response)

async def run_client():
    async with asyncssh.connect('localhost') as conn:
        stdin, stdout, stderr = await conn.open_session(term_type='dumb')
        print(await read_response(stdout))

        stdin.write('ls abc*\n')
        print(await read_response(stdout))

        stdin.write('exit\n')
        print(await read_response(stdout))

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```

The print() calls there can be replaced with whatever you want to do to actually parse the output. Also, if your output contains a '>' outside of the shell prompt, you can replace that with something longer and more unique.

**Comment by Reitz86** [comment]
Cheers. I'm just on the run and don't have access to the device. I'll get back asap. Your help is really appreciated.

**Comment by Reitz86** [comment]
It's Looking good :) thanks
Just need to find a proper way to determine the prompt. It's just '>' and not changeable. Added to that, there appear a lot of >s in the output. Nevertheless, I learnt quite a lot.
