### ISSUE TITLE
Request: Add server requested values to KeyExchangeFailed (et al)

### ISSUE THREAD

**Issue by jeremyschulman** [ronf/asyncssh#289]
From discussion of #287:

**I have an enhancement request that would aid in the debub/troubleshooting process**.  When AsyncSSH raises

````
KeyExchangeFailed: No matching encryption algorithm found
````

Could the exception object include server supported values so that this information can be represented back to the User and they can make the necessary configuration changes?  If this information is not available in the exception instance then they would be required to enable debug logging to identify this information.

Could you please do the same for other similar exchange related exceptions (et al)?

Thank you!

**Comment by ronf** [comment]
Ok - this is now in commit 2d3860b in the "develop" branch. Here's an example of the new exception text:

No matching encryption algorithm found, sent aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc and received chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com

**Comment by jeremyschulman** [comment]
@ronf - Thank you; this is perfect!
