### ISSUE TITLE
Connection numbering

### ISSUE THREAD

**Issue by MichalMazurek** [ronf/asyncssh#292]
Hi!

Thanks for all your work on this, it's great!

I have a question about this line:

https://github.com/ronf/asyncssh/blob/bcd1c2bb3b5671e2a1d32965d937bd41acfa4cda/asyncssh/connection.py#L280

```python
    @staticmethod
    def _get_next_conn():
        """Return the next available connection number (for logging)"""

        next_conn = SSHConnection.next_conn
        SSHConnection.next_conn += 1
        return next_conn
```

I have a long-running process that sends files over SCP. What I noticed in logs, is that the connection id taken from this function will grow with each new connection.

Do you think this might be a problem at some point?

All the best,
Michal

**Comment by ronf** [comment]
Hi Michal,

This should be fine. As noted in the comment, this number is only used for debug logging, and Python's integers do not wrap around. So, this will always generate a unique value. Even if you were continuously opening a connection every second, it would take years to get beyond even 8 digits, so you'll never see this get big enough to have any significant impact on log size or speed to write the logs.

**Comment by MichalMazurek** [comment]
Thanks Ron for clarifying that :)

Btw, I love the API of this, thank you very much again for your work!

**Comment by ronf** [comment]
Thanks very much - I'm glad it's working well for you!
