### ISSUE TITLE
NETCONF client support - references?

### ISSUE THREAD

**Issue by jeremyschulman** [ronf/asyncssh#293]
I am looking for a python client for NETCONF based systems that use the asyncssh package as an underlying transport.  Does anyone know if such a package exists?  I do not expect this to exist with asyncssh directly;  although that would be quite amazing.  Thank you for any references.

**Comment by ronf** [comment]
Sorry, I don't know of a NETCONF implementation built on AsyncSSH yet. I added support for connect_reverse() and listen_reverse() specifically to make it easier to implement the "NETCONF Call Home" described in RFC 8071, though, should anyone decide they want to build something like that.

**Comment by carlmontanari** [comment]
Hey Jeremy -- [scrapli_netconf](https://github.com/scrapli/scrapli_netconf) may fit the bill depending on what you need. Hit me up on ntc slack if ya wanna chat about it!

Thanks for all the awesome work on asyncssh @ronf! /end issue jack!

**Comment by ronf** [comment]
My pleasure - thanks for the pointer, Carl!

**Comment by jeremyschulman** [comment]
@carlmontanari - thank you for creating the scrapli_netconf, I will check it out!
Closing this issue.
