### ISSUE TITLE
prepare() got an unexpected keyword argument 'login_timeout' 

### ISSUE THREAD

**Issue by tomaszdrozdz** [ronf/asyncssh#294]
async def my_coroutine(request):
        async with asyncssh_connect(
            "my.host.com",
            known_hosts=None,
            username="my_user",
            client_keys=["/my/ssh/key"],

            login_timeout=20) as conn:
            # or        
            options=SSHClientConnectionOptions(login_timeout=20)) as conn:

            ...

Gives :

    prepare() got an unexpected keyword argument 'login_timeout' 

But in documentation for asyncssh.connect() I can read that:
https://asyncssh.readthedocs.io/en/latest/api.html#connect
> options (SSHClientConnectionOptions) – (optional) Options to use when establishing the SSH client connection. These options can be specified either through this parameter or as direct keyword arguments to this function.

and for SSHClientConnectionOptions:
https://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SSHClientConnectionOptions
> login_timeout (see Specifying time intervals) – (optional) The maximum time in seconds allowed for authentication to complete, defaulting to 2 minutes. Setting this to 0 will disable the login timeout.

**Comment by ronf** [comment]
Yes - login_timeout is a valid argument for SSHClientConnectionOptions, and for the "prepare" method associated with that. Is "asyncssh_connect" some kind of wrapper function you are providing? If so, maybe that's triggering a problem. Can you provide a full traceback?

**Comment by tomaszdrozdz** [comment]
Thank Yoy for reply :)

asyncssh_connect is just asyncssh.connect

Well, I use [Sanic](https://sanic.readthedocs.io/en/latest/index.html).
I have package like:

    my_sanic_app/
        my_sanic_app.py                                  # my "main" file for sanic app
        auto_start_stop_environments/
            __init__.py
            viwes/
                __init__.py
                do_not_kill_list.py

    # do_not_kill_list.py
    # -*- coding: utf-8 -*-
    from sanic import Blueprint as sanic_Blueprint
    from sanic.response import text as sanic_response_text
    from asyncssh import connect as asyncssh_connect
    #from asyncssh import SSHClientConnectionOptions

    bp_do_not_kill_list = sanic_Blueprint("bp_do_not_kill_list")

    @bp_do_not_kill_list.route("/do_not_kill_list")
    async def do_not_kill_list(request):
        async with asyncssh_connect(
            "my.host.com",
            known_hosts=None,
            username="my_user",
            client_keys=["my_key"],

            login_timeout=20) as conn:
            # This also does not works:
            #options=SSHClientConnectionOptions(login_timeout=20)) as conn:

            # But for example these options produces no exception:            
            #keepalive_interval=20,
            #keepalive_count_max=15

            result = await conn.run(
                "my command",
                check=False,
                errors="ignore")

        return sanic_response_text(result.stdout)

And the traceback is:

> Traceback (most recent call last):
>   File "/my/python_env/lib/python3.8/site-packages/sanic/app.py", line 937, in handle_request
>     response = await response
>  File "/my/python_env/my_sanic_app/auto_start_stop_environments/views/do_not_kill_list.py", line 25, in do_not_kill_list
>     async with asyncssh_connect(
>   File "/my/python_env/lib/python3.8/site-packages/asyncssh/misc.py", line 164, in \_\_aenter\_\_
>     self._result = await self._coro
>   File "/my/python_env/lib/python3.8/site-packages/asyncssh/connection.py", line 5641, in connect
    options = SSHClientConnectionOptions(options, **kwargs)
>   File "/my/python_env/lib/python3.8/site-packages/asyncssh/misc.py", line 212, in \_\_init\_\_
    self.prepare(**self.kwargs)
> TypeError: prepare() got an unexpected keyword argument 'login_timeout'

**Comment by ronf** [comment]
Which version of AsyncSSH do you have installed? Looking at the line numbers in your traceback, it's not lining up against the latest version.

**Comment by tomaszdrozdz** [comment]
>import asyncssh
    > asyncssh.__version__
    '2.1.0'

Mayby it is the case.
I have installed it with [conda](https://docs.conda.io/en/latest/) from [conda-forge channel](https://conda-forge.org/)
No wersion 2.3.0 on conda-forge.

**Comment by ronf** [comment]
Ok - that's the problem. The "login_timeout" argument has been supported on SSHServerConnection for a while now (going back to 1.4.0 in 2016), but it was only added as an SSHClientConnection option in release 2.2.0 (at the end of February). Some other distributions may not have had a chance to pick up this change yet. See https://asyncssh.readthedocs.io/en/latest/changes.html for the detailed change history.

**Comment by tomaszdrozdz** [comment]
Thank You.
I should have check my version first.
asyncssh rocks ! Thank You for creating it.
And fact that You so yarely ( <- mey be I chosed wronk word here) respond :)

Can I ask here one more question ?
There is timeout parameter for run coroutine:

    conn.run( ... , timeout=20, ...)

and in docs:

> If a timeout is specified and it expires before the process exits, the TimeoutError exception will be raised.
> By default, no timeout is set and this call will wait indefinitely.

But on for asyncssh.connect()

> Unlike socket.create_connection(), asyncio calls to create a connection do not support a timeout parameter. However, asyncio calls can be wrapped in a call to asyncio.wait_for() or asyncio.wait() which takes a timeout and provides equivalent functionality.

So for some reasons after login I can wait for "being trully connected" forever (for example server is to bussy ) ???
But what is the reason behind not adding "timeout" parameter also for asyncssh.connect() ?

**Comment by ronf** [comment]
Good question - you can find some discussion about this in #21. My original thinking was to not provide timeout arguments to my calls, as I was trying to mirror the arguments found in the asyncio network calls, and asyncio expected you to wrap your calls in a wait_for() call when you wanted a timeout.

Later on, though, I found that there was a good reason to add an explicit timeout call to conn.run(), as I didn't want it to just raise an exception there. I wanted it to actually collect the partial output generated (if any) to stdout/stderr. So, I added that to run() and the wait() function it uses.

Very recently, as you saw I decided to also add "login_timeout" as an explicit option in the SSH client connection options, to mirror what was already available in the SSH server connection options. In many ways, this is serving the same purpose as a "timeout" argument would have in connect(), so I should probably remove the earlier note I added to the connect() documentation about that. The "login_timeout" applies to the time taken to both connect and authenticate the user, but since connect() only returns when authentication is complete, that's probably how any "timeout" argument would have worked.

**Comment by tomaszdrozdz** [comment]
So to recap.  
From versoin 2.3  

    asyncssh.connect(login_timeout=20, ...)  

is a "timeout" for establishing connection  
(and the documentation should be updated).  

Than You very much again :)

**Comment by ronf** [comment]
Yes - that's right. I have removed the note in question in commit 7f10985 in the "develop" branch. Thanks for pointing this out!
