### ISSUE TITLE
Interactively Kill Async Tasks

### ISSUE THREAD

**Issue by leimao** [ronf/asyncssh#295]
Thank you very much for making such a great contribution, @ronf. However, I do have a more general question related to `asyncio`  and it is not specific to `asyncssh`. Using Python `asyncio`, I could easily set up five `task`s and use `asyncio.gather` to create a new `coroutine`, and the single process single thread `asynio` will help me manage all the executions. If using Python threading, I could get `future` objects for each task and interactively check if the `future` is `done` or not. If it is taking too long, I can interactively kill the thread in the Python interactive interpreter. I feel using `asyncio` is less interactive and I could not control the `task` or the `future` just like how I controlled the similar correspondings using `threading`. Do you have any good suggestions? Thank you.

**Comment by ronf** [comment]
Python's asyncio has future objects where you can check if the asyncio task is done or cancelled, and you can also call cancel() on these tasks to get them to raise a CancelledError (though this will only happen the next time they return to the asyncio event loop). More info can be found at https://docs.python.org/3/library/asyncio-future.html.

As for trying to cancel interactively, I have played a bit with running an asyncio event loop with an interactive Python shell inside of it, but it was a bit tricky to get that working. Normally, if you are sitting in the regular Python REPL, you won't be running your asyncio event loop, so none of those tasks will make any progress. You need to set up your own REPL which uses asyncio to do user input & output and then hook that into a running event loop.

**Comment by leimao** [comment]
> Python's asyncio has future objects where you can check if the asyncio task is done or cancelled, and you can also call cancel() on these tasks to get them to raise a CancelledError (though this will only happen the next time they return to the asyncio event loop). More info can be found at https://docs.python.org/3/library/asyncio-future.html.
> 
> As for trying to cancel interactively, I have played a bit with running an asyncio event loop with an interactive Python shell inside of it, but it was a bit tricky to get that working. Normally, if you are sitting in the regular Python REPL, you won't be running your asyncio event loop, so none of those tasks will make any progress. You need to set up your own REPL which uses asyncio to do user input & output and then hook that into a running event loop.

Thank you very much for your prompt reply, @ronf. I am thinking to create a tool that allows the user to play with the I/O-bound async interactively. Using `threading`, I think I could do it easily. But I would also like to try `asyncio` since it is a little bit new to me and a little bit brain-twisting. I do find from the Python doc that we could get `future` object to a new Python thread (see https://docs.python.org/3/library/asyncio-task.html#asyncio.run_coroutine_threadsafe). I thought I could interactively measure if the `future` is done in the terminal, but it seems that it was always `False`. Since it is an incomplete example, I was not sure where I did wrong. If this method would work, I think we could cancel `asynio` interactively.

**Comment by leimao** [comment]
If you have any code example or suggestions on `asyncio.run_coroutine_threadsafe`, please let me know :)

**Comment by leimao** [comment]
@ronf, I think this is an example of how to control the tasks from another thread.
https://github.com/no7dw/py-practice/blob/8c1787d2eab94f8f30ddb8942e84155fa4df8d2e/async/thread.py
It returns a `concurrent.futures.Future` instead of an `asyncio.Future`. `concurrent.futures.Future` could be controlled in another thread in Python and it is interactive to the user. The only short-coming is that one thread will run forever, and you would not exit normally as a program. But this is definitely acceptable for users to do work interactively.

**Comment by leimao** [comment]
Another short-coming compared to `threading` is that we could not control every single task in the `coroutine`, but treated them as a bundle. This might not be favored in some use cases.

**Comment by ronf** [comment]
Yes - if you wanted to use the traditional Python REPL, you could choose to run that in one thread and run asyncio coroutines in a separate thread dedicated to running the asyncio event loop. You could even have a function which calls loop.stop() if you at some point wanted to shut that event loop thread down, or you could use loop.run_until_complete() to run a coroutine that waits for an event, and then have another coroutine that signals the event called from run_coroutine_threadsafe().

If you start each async task with a separate call to run_coroutine_threadsafe(), you probably could control them individually, and still gain the scalability that asyncio gives you over having a completely separate thread for each task. I haven't really looked into how expensive run_coroutine_threadsafe() is, though -- I imagine there would be some locking required in that which you wouldn't normally need with plain asyncio coroutines and futures.

**Comment by leimao** [comment]
Thank you very much @ronf. I made a summary of the discussion with some code examples [here](https://leimao.github.io/blog/Control-Python-AsyncIO-Coroutine-Interactively/). 
Regarding your points on running `run_coroutine_threadsafe` on each task so that we could control them individually, I think in most of the use cases, people would rather probably use `threading` without `asyncio`.

**Comment by ronf** [comment]
I agree that it wouldn't be common to mix asyncio and threading, and most people would choose to only use one or the other. The main downside to using threading is that it doesn't scale nearly as well when you have a large number of tasks to schedule. Each thread needs its own call stack, and all the threads will be fighting to get scheduled. Also, there will be locking related to each of the threads trying to acquire the Python "global interpreter lock". 

By comparison, asyncio doesn't create separate stacks for each task and works in a more cooperative fashion in terms of when it switches between tasks. This also avoids contention on the global interpreter lock, though you are limited for any given event loop to only task advantage of a single core if you have a multi-core CPU, but with Python's global interpreter lock that's generally true for threads as well -- you need to use "multiprocessing" to get true concurrency in Python.

Seeing the example code in your blog, I wrote a variation of that which shows how you can fire up an event loop in the background and use it to schedule tasks, including cancelling individual tasks rather than all of them at once. Here it is:

```python
import asyncio
from concurrent.futures import CancelledError
from threading import Thread

class EventLoop(Thread):
    def __init__(self):
        self._loop = asyncio.get_event_loop()
        super().__init__(target=self._loop.run_forever)
        self.start()
        
    def stop(self):
        self._loop.call_soon_threadsafe(self._loop.stop)

    def create_task(self, coro):
        return asyncio.run_coroutine_threadsafe(coro, self._loop)
        

async def some_func(number):
    await asyncio.sleep(3)
    return number
    

event_loop = EventLoop()
tasks = [event_loop.create_task(some_func(number)) for number in range(3)]
    
tasks[1].cancel()

for i, task in enumerate(tasks):
    try:
        print(f'Task {i} result: {task.result()}')
    except CancelledError:
        print(f'Task {i} cancelled')

event_loop.stop()
```

I think you could probably do all of this interactively from the REPL if you wanted to.

**Comment by leimao** [comment]
Thank you very much @ronf. Yes, indeed. `asyncio` could handle a higher volume of IO-bound concurrencies better than `threading`, so it is much more suitable for an IO-bound task.
I was not able to think of we could kill the even loop and the thread by `self._loop.call_soon_threadsafe(self._loop.stop)`. This is cool.
Your example is very useful and I would like to thank you again.

**Comment by leimao** [comment]
Closing this "issue" as it has been solved almost perfectly.
