### ISSUE TITLE
ConfigParseError with unbalanced quotes in .ssh/config comments

### ISSUE THREAD

**Issue by Thirdegree** [ronf/asyncssh#296]
As of 2.3.0, connecting to any host while there is a comment in $HOME/.ssh/config that contains an uneven number of quotations will result in an error.

Steps to reproduce:

1. Place the following line anywhere in $HOME/.ssh/config:

`# This is a' test`

2. Run the following:

```python 
import asyncio, asyncssh
async def main():
    async with asyncssh.connect('localhost') as conn:
        return await conn.run('echo "Hello world"')
print(repr(asyncio.get_event_loop().run_until_complete(main())))
```

Expected result: 
`SSHCompletedProcess(env={}, command='echo "Hello world"', subsystem=None, exit_status=0, exit_signal=None, returncode=0, stdout='Hello world\n', stderr='')`

Actual Result: 
`/home/thirdegree/.ssh/config line 1: No closing quotation`

Version: 2.3.0
Last working version: 2.2.1

**Comment by ronf** [comment]
Thanks for the report. I fixed this in the "develop" branch a couple of weeks ago, but it hasn't made it into a new release yet. See commit 471fdf6 for details if you'd like to apply this fix locally.

**Comment by Thirdegree** [comment]
Ah ok cool. I'll just exclude 2.3.0 from the version pin then. Thanks!
