### ISSUE TITLE
connection to Cisco IOS devices fail with DisconnectError: ProtocolError: expected packet type 61, got 50 

### ISSUE THREAD

**Issue by yosemitesammy217** [ronf/asyncssh#3]
when connecting to a Cisco IOS router (specifically a 3945 running IOS 15.2(4)M6a), there is an exception thrown:

asyncssh.misc.DisconnectError: Disconnect Error: Protocol error: expected packet type 61, got 50

logger output

2015-03-03 22:18:26,983 - Utility - collect_configs3 - cs_ssh_get_config - INFO - starting ssh session to ash-39t-gsgo-oob-1 with username scrooks...
2015-03-03 22:18:30,321 - Utility - collect_configs3 - cs_ssh_get_config - ERROR - ssh connection failed hostname=ash-39t-gsgo-oob-1, ip=131.253.126.240 exc=Disconnect Error: Protocol error: expected packet type 61, got 50
Traceback (most recent call last):
  File "/glusterfs/home/scrooks/bin/cybersonic/network/Utility.py", line 347, in cs_ssh_get_config
    server_host_keys=None)
  File "/glusterfs/lib/python3.4/site-packages/asyncssh/connection.py", line 3088, in create_connection
    yield from auth_waiter
  File "/glusterfs/lib/python3.4/asyncio/futures.py", line 348, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/glusterfs/lib/python3.4/asyncio/tasks.py", line 332, in _wakeup
    value = future.result()
  File "/glusterfs/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
asyncssh.misc.DisconnectError: Disconnect Error: Protocol error: expected packet type 61, got 50
2015-03-03 22:18:30,349 - Utility - collect_configs3 - cs_collect_config - INFO - finished collecting config for ash-39t-gsgo-oob-1...

the same code works fine for other types of devices which use an OpenSSH-based ssh server (Juniper routers, Cisco Nexus 3000 series switches)

code:

    @asyncio.coroutine
    def cs_ssh_get_config(self, hostname, ip, username, password, cmd, type):

        try:
            result = ""
            stderr_output = ""

            logger.info("starting ssh session to %s with username %s..." % (str(hostname), str(username)))

            if(type == "ios"):
                #kex_list = ["diffie-hellman-group-exchange-sha1", "diffie-hellman-group14-sha1", "diffie-hellman-group1-sha1"]
                kex_list = ["diffie-hellman-group1-sha1"]
                enc_list = ["aes128-cbc",]
                mac_list = ["hmac-md5"]
                #pdb.set_trace()
                conn, client = yield from asyncssh.create_connection(None,
                                                                     host=ip,
                                                                     username=username,
                                                                     password=password,
                                                                     mac_algs=mac_list,
                                                                     encryption_algs=enc_list,
                                                                     kex_algs=kex_list,
                                                                     client_keys=None,
                                                                     server_host_keys=None)
                #pdb.set_trace()
                if(conn):
                    logger.info("connection extra info=%s" % (str(conn.get_extra_info())))
                    logger.info("opening ssh session to hostname=%s, ip=%s" % (str(hostname), str(ip)))

                    #pdb.set_trace()
                    stdin, stdout, stderr = yield from conn.open_session(cmd, term_type="vt100")
                    #pdb.set_trace()
                else:
                    logger.exception("ssh connection == None, hostname=%s, ip=%s" %(str(hostname), str(ip)))
                    return None
            else:
                conn, client = yield from asyncssh.create_connection(None, host=ip, username=username, password=password, server_host_keys=None)
                if(conn):

                    logger.info("connection extra info=%s" % (str(conn.get_extra_info())))
                    logger.info("opening ssh session to hostname=%s, ip=%s" % (str(hostname), str(ip)))
                    stdin, stdout, stderr = yield from conn.open_session(cmd)
                else:
                    logger.exception("ssh create_connection == None, hostname=%s, ip=%s" %(str(hostname), str(ip)))
                    return None

            if(stdin and stdout and stderr):
                while not stdout.at_eof():
                    result += yield from stdout.read()
                while not stderr.at_eof():
                    stderr_output += yield from stderr.read()

                logger.info("closing ssh session to hostname=%s, ip=%s ..." % (str(hostname), str(ip)))
                conn.close()
                logger.info("closed ssh session to hostname=%s, ip=%s ..." % (str(hostname), str(ip)))
                return result

            else:
                logger.exception("ssh open_session() failed to hostname=%s, ip=%s" %(str(hostname), str(ip)))
                return None
        except (asyncssh.Error) as e:
            logger.exception("ssh connection failed hostname=%s, ip=%s exc=%s" % (str(hostname), str(ip), str(e)))
            return None

**Comment by ronf** [comment]
Thanks for you help debugging this, Sam!

A fix for this is now checked in. It loosens the checking on the prompt to accept any prompt with the word "password" in it, ignoring punctuation, case, and whitespace. It also fixes another bug in this code where it was using the wrong function to retrieve the password provided when the connection is created. Since most SSH servers prefer password authentication over keyboard-interactive, this went unnoticed during routine testing.

**Comment by ricecs** [comment]
I encounted same error today when our password prompt is passcode instead of password

I changed the following line in /asyncssh/connection.py
 #elif len(prompts) == 1 and 'password' in prompts[0][0].lower():
to
 elif len(prompts) == 1 and ( 'passcode' in prompts[0][0].lower() or 'passcode' in prompts[0][0].lower()):
This way either password or passcode will be able to connect.

**Comment by ronf** [comment]
Sure, this seems reasonable. This is now available in commit a83cad6 in the "develop" branch. I reworked the code a bit to remove some duplication and enhanced the unit tests to cover this change, but it should behave equivalent to the change you suggested. Let me know if you have any problems with it.
