### ISSUE TITLE
How to use custom SSHTCPSession in direct TCP connection

### ISSUE THREAD

**Issue by woodywuuu** [ronf/asyncssh#302]
I'm new to  asyncSSH and ssh protocol. I want to use asyncSSH to build a ssh-server like bastion, user can ssh to target-server through this ssh-server using ProxyJump.    
Using OpenSSH8.1 on my terminal,  and OpenSSH7.4 on target-server
My ssh_config like this:
```
Host target-server
   IdentityFile ~/.ssh/id_rsa
   User user
   Port 2222
   ProxyJump 127.1:8022
```
And I run a demo server just like direct-tcp demo in document:
``` python
import asyncio, asyncssh, sys

import logging

logging.basicConfig(level=logging.DEBUG)


class MySSHTCPSession(asyncssh.SSHTCPSession):
    def session_started(self):
        print('session started')

    def connection_made(self, chan):
        self._chan = chan

    def data_received(self, data, datatype):
        self._chan.write(data)


class MySSHServer(asyncssh.SSHServer):
    def connection_requested(self, dest_host, dest_port, orig_host, orig_port):
        print(orig_host, orig_port, dest_host, dest_port)
        if dest_port == 2222:
            return MySSHTCPSession()
        else:
            raise asyncssh.ChannelOpenError(
                asyncssh.OPEN_ADMINISTRATIVELY_PROHIBITED,
                'Only echo connections allowed')

    def begin_auth(self, username):
        return True

    def password_auth_supported(self):
        return False

    def public_key_auth_supported(self):
        return True

    def validate_public_key(self, username, key):
        return True

    def auth_completed(self):
        print('Authentication successful.')


async def start_server():
    await asyncssh.create_server(MySSHServer, '', 8022,
                                 server_host_keys=['./ssh_host_key/id_rsa'],
                                 )


loop = asyncio.get_event_loop()

try:
    loop.run_until_complete(start_server())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH server failed: ' + str(exc))

loop.run_forever()
```
The function data_received in custom MySSHTCPSession firstly return like 
```
b'SSH-2.0-OpenSSH_8.1\r\n'
```
seems just return my local ssh version.  
I read this code but have no idea about it .
```
        if result is True:
            result = self.forward_connection(dest_host, dest_port)

        if isinstance(result, tuple):
            chan, result = result
        else:
            chan = self.create_tcp_channel()
```
When I turn the function connection_requested return True. This works.Any idea to use custom SSHTCPSession?  

Any information you can provide me would be greatly appreciated.

**Comment by ronf** [comment]
You're on the right track.

If you just want to do authentication and make some decisions about whether to forward the client session or not to a destination host/port the client has selected, you can simply return True in connection_requested() function. As you saw, this will create a connection forwarder to the client's requested destination host & port, and you wouldn't need to build your own custom TCP session.

If you wanted to further inspect or modify the bytes in the forwarded connection, you would need your own TCP session for that. You'd need to open a raw TCP connection using the asyncio create_connection() function to forward data to, and you'd need to set up a custom TCP session to copy data back and forth between the incoming SSH channel and that TCP connection. You can take a look at the SSHForwarder() class for an example of this, and the forward_connection() function in SSHConnection class for how to get that started. Keep in mind that the forwarded SSH connection is going to be encrypted, though, so there will be very little you'll be able to do to look inside the data after the initial SSH version information is sent and the key exchange runs.

**Comment by woodywuuu** [comment]
I got it, Thank you very much !
