### ISSUE TITLE
API compatibility with asyncio.StreamReader

### ISSUE THREAD

**Issue by termim** [ronf/asyncssh#304]
I've a client that connects to some service using either `asyncio.open_connection` or `asyncssh.open_connection` depending on the environment. When writing unit tests for this client I've found handy to have `asyncio.StreamReader.feed_data` and `asyncio.StreamReader.feed_eof` methods. It would be very useful to have the same API available in `SSHReader` as well so the tests could be run over both direct and SSH connection.

Please take a look at #305 for the possible implementation.

**Comment by ronf** [comment]
This functionality is now released in AsyncSSH 2.4.0.
