### ISSUE TITLE
No check that port argument is in a valid range

### ISSUE THREAD

**Issue by rmawatson** [ronf/asyncssh#312]
Specifically when using `forward_local_port`, where the socket is opened in in `SSHForwardListener.create_tcp_local_listener()` if a port is given that is greater than `0xffff`, `getaddrinfo` will return `listen_port & 0xffff` as part of the returned `addrinfo` which is used ultimately used to open the socket.

In the case of a typo in a config file for instance, this results in a subtle bug of the port forward succeeding, but on an unexpected port, rather than an exception being raised.

It's possible this is not checked elsewhere and could cause similar issues.

**Comment by ronf** [comment]
I'm not seeing that behavior here. When I try to pass in a listen_port greater than 65535, getaddrinfo() raises a socket.gaierror.  On macOS, I see:

    socket.gaierror: [Errno 8] nodename nor servname provided, or not known

On Linux, I see:

    socket.gaierror: [Errno -2] Name or service not known

Either way, it exits with that error before attempting to call bind() on the out-of-range port, and if it DID get to call bind(),
that returns an error as well if the number is still out of range:

    OverflowError: bind(): port must be 0-65535.

You said that something is returning "listen_port & 0xffff", but where is the code which does that?

**Comment by rmawatson** [comment]
looks like its specific to windows - thanks for looking.

```
>>> socket.getaddrinfo("",65535,family=socket.AF_UNSPEC,type=socket.SOCK_STREAM,flags=socket.AI_PASSIVE)[0]
(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('fe80::53ee:5ebd:f1d5:1bbb', 65535, 0, 28))

>>> socket.getaddrinfo("",65536,family=socket.AF_UNSPEC,type=socket.SOCK_STREAM,flags=socket.AI_PASSIVE)[0]
(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('fe80::53ee:5ebd:f1d5:1bbb', 0, 0, 28))

>>> socket.getaddrinfo("",65537,family=socket.AF_UNSPEC,type=socket.SOCK_STREAM,flags=socket.AI_PASSIVE)[0]
(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('fe80::53ee:5ebd:f1d5:1bbb', 1, 0, 28))
```

**Comment by ronf** [comment]
Interesting! You might want to file a bug against the Python socket library code regarding that. It looks like the problem may be down in the C code. There are multiple places where a u_short is used to hold the port, and the atoi() return value is cast to that without checking it first (see [here](https://github.com/python/cpython/blob/471247150e9707e583297ac6b4edff978efd8941/Modules/getaddrinfo.c#L342).)
