### ISSUE TITLE
Help with sudo commands

### ISSUE THREAD

**Issue by sharayahnscott** [ronf/asyncssh#317]
Hello! I'm very new to asyncssh (ie, found out about it this morning). I'm attempting to rewrite some code we had initially used fabric/paramiko libraries for, and I'm having some difficulty on how to process sudo commands. I did some digging through other posts and saw @ronf mention you would likely have to have your code feed in the password, but I'm not sure how to do that in this instance. With fabric, I was able to use Invoke/Responders to auto-reply my password.

Here's what I've got so far:
```
import asyncio, asyncssh, sys

#apparently needed for Jupyter Lab where I am testing
import nest_asyncio
nest_asyncio.apply()

async def run_client():
    async with asyncssh.connect(<host>, port=<port>, username=<user>, password=<pw>) as conn:
        cmd1= '''
        cd <directory>
        ls archive/*.sav
        '''
        archive_files = await conn.run('/bin/bash -e -s', input=cmd1, stderr=asyncssh.STDOUT)
        archive_files = archive_files.stdout.split()
        archive_files.sort()
        sav_file=archive_files.pop()
        print(sav_file)
        
        cmd2 = '''
        cd <the same directory>
        ls error/*.dat
        '''
        try:
            error_files = await conn.run('/bin/bash -e -s', input=cmd2, stderr=asyncssh.STDOUT)
        except Exception as e:
            log.error('EXCEPTION CAUGHT: %s', e)
            return None
        error_files = error_files.stdout.split()
        error_files.sort()
        error_file = error_files.pop()
        print(error_file)
        
        cmd3=f'''
        cd <the same directory still>
        wc -l {error_file}
        comm --nocheck-order -13 {sav_file} {error_file} | wc -l
        sudo -S comm --nocheck-order -13 {sav_file} {error_file} > /tmp/temp.dat
        sudo -S chmod 664 error/*.dat
        sudo -S cat /tmp/temp.dat > {error_file}
        sudo -S rm /tmp/temp.dat
        '''
        result = await conn.run('/bin/bash -e -s', input=cmd3, stderr=asyncssh.STDOUT)
        print(result.stdout, end='')

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```

I think I have to add the '-S' flag to prevent from receiving "sudo: no tty present and no askpass program specified"...but I'm not sure how to feed in my password. Can anyone help?

**Comment by sharayahnscott** [comment]
Of course, now that I've swallowed some pride and made a post for help -- I think I found my solution.

Is there a better way than doing: `echo '{password}' | sudo -S <command>`

**Comment by ronf** [comment]
There are a few different ways to do this which are probably better than leaving the password in the command line itself.

If you _only_ need to feed in a password and and nothing else, you can try setting "input" on the call to conn.run(). That will feed whatever input data you give it into stdin when it runs the command.

If you need to feed in more data than that, you'll probably need to switch to using create_process() rather than run(). You can then read data from proc.stdout/proc.stderr and write data to proc.stdin, building whatever interactive responses you need depending on the output you get.

You can find an example of this at https://asyncssh.readthedocs.io/en/latest/#interactive-input.

**Comment by sharayahnscott** [comment]
@ronf  Thanks so much! I think I can make it work this way. Appreciate the help, and saving me an angry phone call from our security team ;)

**Comment by ronf** [comment]
Happy to help - let me know if you have any other questions!
