### ISSUE TITLE
Attempting to read closed connection doesn't raise any exception

### ISSUE THREAD

**Issue by ashiquzzaman33** [ronf/asyncssh#321]
After a successful connection, if I disconnect the remote server manually (disconnect internet) then `await process.stdout.readline()` wait indefinitely. In this scenario I was expecting `ConnectionLost` or `BrokenPipeError` error.
Is it intended behavior?

Sample Code:

    async def run_client():
        async with asyncssh.connect(host='remote_host', username='user', password='password') as conn:
            async with conn.create_process('bc') as process:
    
                while True:
                    for op in ['2+2', '1*2*3*4', '2^32']:
                        process.stdin.write(op + '\n')
                        result = await process.stdout.readline()
                        print(op, '=', result, end='')
                        await asyncio.sleep(2)
    
    
    try:
        asyncio.get_event_loop().run_until_complete(run_client())
    except (OSError, asyncssh.Error) as exc:
        sys.exit('SSH connection failed: ' + str(exc))

Thanks for your awesome package.

**Comment by ronf** [comment]
When you say you disconnect the remote server "manually",  do you mean something like unplugging the network cable? If so, it's not unusual for any program to take a long time recognizing that the server has "gone away" in such a case, particularly if it is reading from the server and has no data to write. This is not specific to AsyncSSH -- pretty much any network application will have the same problem.

As soon as the network stack detects that the server is gone and notifies AsyncSSH, it will break out of the readline() call with an error. However, this can take a while. AsyncSSH has a feature that can help here, though. See the keepalive_interval and keepalive_count_max arguments to asyncssh.connect(). If no data is received after the interval you set, AsyncSSH will send a "keep alive" message to see if the server is still there. If it doesn't get a response after the configured number of attempts (which defaults to 3), it will trigger an error even if the network stack hasn't detected a problem yet. Even the act of sending the keepalives is enough in some cases to also speed up the detection of the server being gone.

Try adding something like keepalive_interval=5 to your connect() call and see if that helps.

**Comment by ashiquzzaman33** [comment]
Thanks, @ronf for this nice solution.
