### ISSUE TITLE
SSH key doesn't work in docker (in virtualenv all's fine)

### ISSUE THREAD

**Issue by vasili-ii** [ronf/asyncssh#322]
Hello, Ron.
I have a problem with docker container. I created connection to remote host and copied known_hosts to separete directory "project/ssh_keys". Also I generated ssh key (rsa, 4096 bytes) for that remote host and copied pub-key to the remote host (id_rsa_test+id_rsa_test.pub -> into separate directory "project/ssh_keys"). Then I tested that ssh-key: I connected to the remote host using previously generated ssh key and standard ubuntu client. Then I created a simple script on python:

```
import asyncio
import asyncssh
import sys
import os


HOST = 'super-host'
PATH = 'path/to/file/'
FLNAME = 'test_file.txt'
FLPATH = os.path.join(PATH, FLNAME)


async def run_client():
    ssh_dir = 'project/ssh_keys'
    known_hosts = os.path.join(ssh_dir, 'known_hosts')
    private_key = os.path.join(ssh_dir, 'id_rsa_test')
    async with asyncssh.connect(HOST,
                                known_hosts=known_hosts,
                                client_keys=[private_key]) as conn:
        async with conn.start_sftp_client() as sftp:
            await sftp.get(FLPATH)


if __name__ == '__main__':
    try:
        asyncio.get_event_loop().run_until_complete(run_client())
    except (OSError, asyncssh.Error) as exc:
        sys.exit('SFTP operation failed: ' + str(exc))
```

This script works fine in virtualenv: it got file from remote server.

The problem is in docker container. When I try to use this script in docker container - it doesn't work, it shows:
```
...
    client_keys=[private_key]) as conn:
  File "/home/python/.local/lib/python3.7/site-packages/asyncssh/misc.py", line 206, in __aenter__
    self._result = await self._coro
  File "/home/python/.local/lib/python3.7/site-packages/asyncssh/connection.py", line 6416, in connect
    conn_factory, 'Opening SSH connection to')
  File "/home/python/.local/lib/python3.7/site-packages/asyncssh/connection.py", line 218, in _connect
    await conn.wait_established()
  File "/home/python/.local/lib/python3.7/site-packages/asyncssh/connection.py", line 2096, in wait_established
    await self._waiter
asyncssh.misc.PermissionDenied: Permission denied

```
Path to directory with ssh is correct. Ssh-keys are the same in both variants (virtualenv vs docker).
What can be a reason of such error?

**Comment by ronf** [comment]
I noticed you closed this shortly after opening it. Were you able to figure out the issue? I'm guessing it might have been a problem of the client key not being found when running in the Docker container, or some other failure related to authentication.

**Comment by vasili-ii** [comment]
You are right the problem was in authorisation: I used ssh_key of my account on the local machine, but then I tryed to use it via docker I didn't set username, so code used incorrect username. Then I set username explicitly in code it began work correctly.

**Comment by ronf** [comment]
Ah, thanks - glad you were able to find the problem! If you have any other questions, feel free to ask any time.
