### ISSUE TITLE
Client disconnection during key exchange

### ISSUE THREAD

**Issue by DavidVentura** [ronf/asyncssh#323]
Hi
Against some hosts, asyncssh fails to establish a connection:

```
asyncssh.set_log_level(logging.DEBUG)
asyncssh.set_debug_level(2)
async with asyncssh.connect('some ipaddr',
                            agent_forwarding=False,
                            client_username=settings['USER'],
                            username=settings['USER'],
                            password=settings['PWD'],
                            login_timeout=120,
                            known_hosts=None,
                            public_key_auth=False,
                            ) as c:
    await c.run('ls')
```

Logs:
```
INFO:asyncssh:Opening SSH connection to destination, port 22
INFO:asyncssh:[conn=0] Connection to destination, port 22 succeeded
INFO:asyncssh:[conn=0]   Local address: local-addr, port 49802
DEBUG:asyncssh:[conn=0] Requesting key exchange
DEBUG:asyncssh:[conn=0]   Key exchange algs: diffie-hellman-group-exchange-sha256
DEBUG:asyncssh:[conn=0]   Host key algs: sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-ed448-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-1.3.132.0.10-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,ssh-ed448,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,ecdsa-sha2-1.3.132.0.10,rsa-sha2-256,rsa-sha2-512,ssh-rsa
DEBUG:asyncssh:[conn=0]   Encryption algs: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
DEBUG:asyncssh:[conn=0]   MAC algs: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
DEBUG:asyncssh:[conn=0]   Compression algs: zlib@openssh.com,none
DEBUG:asyncssh:[conn=0] Received key exchange request
DEBUG:asyncssh:[conn=0]   Key exchange algs: diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
DEBUG:asyncssh:[conn=0]   Host key algs: ssh-rsa,ssh-dss
DEBUG:asyncssh:[conn=0]   Client to server:
DEBUG:asyncssh:[conn=0]     Encryption algs: aes256-ctr,AEAD_AES_256_GCM,aes256-gcm@openssh.com,aes256-cbc,aes128-cbc,3des-cbc
DEBUG:asyncssh:[conn=0]     MAC algs: hmac-sha2-256,AEAD_AES_256_GCM,hmac-sha1
DEBUG:asyncssh:[conn=0]     Compression algs: none
DEBUG:asyncssh:[conn=0]   Server to client:
DEBUG:asyncssh:[conn=0]     Encryption algs: aes256-ctr,AEAD_AES_256_GCM,aes256-gcm@openssh.com,aes256-cbc,aes128-cbc,3des-cbc
DEBUG:asyncssh:[conn=0]     MAC algs: hmac-sha2-256,AEAD_AES_256_GCM,hmac-sha1
DEBUG:asyncssh:[conn=0]     Compression algs: none
DEBUG:asyncssh:[conn=0] Beginning key exchange
DEBUG:asyncssh:[conn=0]   Key exchange alg: diffie-hellman-group-exchange-sha256
DEBUG:asyncssh:[conn=0] Received disconnect:  Client Disconnect (11)
INFO:asyncssh:[conn=0] Connection failure:  Client Disconnect (error 11)
INFO:asyncssh:[conn=0] Aborting connection
```

I'm on asyncssh 2.4.2

**Comment by DavidVentura** [comment]
so, if i manually do:
```
ssh-keyscan 'target' > known_hosts
```
*and* set `known_hosts` to this file, it works fine. Clearly setting `known_hosts` to `None` is not having its intended effect.

**Comment by ronf** [comment]
Actually, setting `known_hosts` to `None` has a side effect that may explain what you are seeing. When `known_hosts` is set, the `server_host_key_algs` list defaults to only the host key algorithms found in the `known_hosts` list you provide. However, when you set it to `None`, you're saying that you will accept any host key algorithm, so it provides a much longer list of allowed algorithms. Some servers have trouble with this, though, as they don't search far enough down the list to find an algorithm they support. In particular, if I remember right, dropbear stops looking after the first 20 algorithms.

In the example here, setting known_hosts to `None` seems to result in AsyncSSH sending the list:

    sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-ed448-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-1.3.132.0.10-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,ssh-ed448,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,ecdsa-sha2-1.3.132.0.10,rsa-sha2-256,rsa-sha2-512,ssh-rsa

This may be long enough to trigger the problem.

The workaround is to add something like `server_host_key_algs=['ssh-rsa']` as an additional argument, if you don't want to add a `known_hosts` entry.

As an aside, setting `known_hosts` to `None` could also be a security concern, as it opens you up to a potential man-in-the-middle attack.

**Comment by DavidVentura** [comment]
Thank you, this (amount of algos offered) was the problem.
By the way, there was a change merged a few days ago to dropbear to address this:
https://github.com/mkj/dropbear/commit/1a208c460b412113704c4d5f98585017ee0a6ccf

**Comment by ronf** [comment]
Ah, great - thanks for the info!
