### ISSUE TITLE
Pagent not being used

### ISSUE THREAD

**Issue by batterseapower** [ronf/asyncssh#331]
When calling `asyncssh.connect(ip, known_hosts=None, username='my-username')` on Windows it looks like Pagent isn't being used to find keys. This issue is similar to that reported in #215, but I'm seeing the issue in 2.4.2 which already has the patch for that problem.

The problem is that `_agent` is never set on the `SSHClientConnection`, and this is in turn caused by the fact that `SSHClientConnectionOptions.agent_path is None`. It looks to me at first glance that if in the arguments to `connect`, `client_keys=()` and `agent_path=()` (the defaults) then `SSHClientConnectionOptions.agent_path` will always be `None` so there is no way to trigger the Pageant codepath: https://github.com/ronf/asyncssh/blob/master/asyncssh/connection.py#L5919

Maybe the right fix is to change `os.environ.get('SSH_AUTH_SOCK', None)` to `os.environ.get('SSH_AUTH_SOCK', ())` on https://github.com/ronf/asyncssh/blob/master/asyncssh/connection.py#L5897? This does solve the problem for me.

**Comment by ronf** [comment]
Thanks for the report!

The previous fix to #215 would have fixed this, but it looks like part of it was unintentionally rolled back in the following release (commit  8749f84). Unfortunately, I don't have a unit test to cover this case, as I never created a mock Pageant service to test against.

The change you suggested looks right to me, and is consistent with what was done in #215. I'll look into getting this put back into the "develop" branch and into the next release. Sorry for the trouble!

**Comment by ronf** [comment]
This should now be available in the "develop" branch as commit f9b5830, and will go into the next release.

**Comment by ronf** [comment]
This fix is now available in the AsyncSSH 2.5.0 release.
