### ISSUE TITLE
How to get filesize with sftp.readdir?

### ISSUE THREAD

**Issue by josephernest** [ronf/asyncssh#333]
I read https://asyncssh.readthedocs.io/en/latest/_modules/asyncssh/sftp.html but I'm not sure about the best way to find the filesize, mtime, boolean `is_directory` after a `sftp.readdir` call?

    for f in await sftp.readdir(remotedir):
        is_directory = f.longname[0] == 'd'  # I'm sure there's better than this parsing of the [d]rwxrwxrwx ;)
        mtime = f.attrs.mtime  # this seems ok
        filesize = ?       # how to get this? if possible without any call to another function

Is there no better way than to parse the `f.longname` string and isolate the filesize in this string @ronf ? (this seems like a hack)

    drwxrwxrwx  1 ssh      ssh         1234 Dec  3 17:11 test

^ here I don't think it would be super reliable to try to extract the 5th column (`1234` here)

**Comment by ronf** [comment]
The "attrs" field in the returned SFTPName objects contains a bunch of information. Here's an example of a directory:

> `SFTPName(filename='.',` longname='drwxrwxrwt   18 root     wheel         576 Dec  4 15:02 .', attrs=SFTPAttrs(size=576, uid=0, gid=0, permissions=17407, atime=1607134021, mtime=1607122942, nlink=None, extended=[]))`

Here's a plain file:

> `SFTPName(filename='x', longname='-rw-r--r--    1 ronf     wheel      167993 Dec  3 20:11 x', attrs=SFTPAttrs(size=167993, uid=501, gid=0, permissions=33188, atime=1607050137, mtime=1607055094, nlink=None, extended=[]))`

The file size is in the 'size' attribute, and the mtime/atime are both present as attributes as well. To determine if an entry refers to a directory, you can run stat.S_ISDIR() on the 'permissions' attribute, though I suspect that may depend on the client and server operating systems having a similar concept of the meaning of those bits. It's certainly more reliable than trying to parse the 'drwxrwxrwx' string in the longname, though. That output can vary wildly from one SFTP implementation to another.

As you can see, you can also get uid/gid information, if you need it.

**Comment by josephernest** [comment]
Thank you for your answer @ronf!
I didn't see this, because:

    for f in await sftp.readdir(remotedir):
        print(f.attrs)

only showed `permissions: 040777, atime: Thu Dec  3 17:11:36 2020, mtime: Thu Dec  3 17:11:36 2020` and nothing else. Then I thought there is *only* `permissions`, `atime`, `mtime`.
Now I see that the class `<class 'asyncssh.sftp.SFTPAttrs'>` has more than this, thanks!

**Comment by ronf** [comment]
Not all SFTP server implementations provide all of the possible attributes. If you only saw permissions. atime, and mtime, that probably means that's all that server provides. If that's the case, you might still be able to use stat.S_ISDIR() on the permissions field to check which entries are directories, but you might not be able to get size information. You might want to check that again, though -- the server might return different attributes for files vs. directories. I'd be kind of surprised if it didn't provide a size for files, but I'm not surprised it didn't try to provide UID/GID information.

**Comment by josephernest** [comment]
Thanks for your answer! I confirm size and uid/gid are available, good thing!
