### ISSUE TITLE
Auth behavior change from 2.3.0+ introduces backwards incompatibility

### ISSUE THREAD

**Issue by kryptek** [ronf/asyncssh#335]
I've been using asyncssh 2.2.1 for some time. As soon as I update from there, my auth breaks

Working test, v2.2.1:
```
INFO:asyncssh:Opening SSH connection to <REDACTED>, port 22
DEBUG:pssh.clients.native.tunnel:Channel closed
DEBUG:pssh.clients.native.tunnel:Closing channel and forward socket
INFO:asyncssh:[conn=0] Connection to <REDACTED>, port 22 succeeded
INFO:asyncssh:[conn=0]   Local address: <REDACTED>, port 58018
DEBUG:asyncssh:[conn=0] Requesting key exchange
DEBUG:asyncssh:[conn=0] Received key exchange request
DEBUG:asyncssh:[conn=0] Beginning key exchange
DEBUG:asyncssh:[conn=0] Completed key exchange
INFO:asyncssh:[conn=0] Beginning auth for user <REDACTED>
DEBUG:asyncssh:[conn=0] Received authentication banner
DEBUG:asyncssh:[conn=0] Trying public key auth with rsa-sha2-256 key
DEBUG:asyncssh:[conn=0] Trying public key auth with rsa-sha2-256 key
DEBUG:asyncssh:[conn=0] Signing request with rsa-sha2-256 key
INFO:asyncssh:[conn=0] Auth for user <REDACTED> succeeded
```

Non-working test (v2.4.2)
```
DEBUG:pssh.clients.native.tunnel:Channel closed
DEBUG:pssh.clients.native.tunnel:Closing channel and forward socket
INFO:asyncssh:Opening SSH connection to <REDACTED>, port 22
INFO:asyncssh:[conn=0] Connection to <REDACTED>, port 22 succeeded
INFO:asyncssh:[conn=0]   Local address: <REDACTED>, port 58032
DEBUG:asyncssh:[conn=0] Requesting key exchange
DEBUG:asyncssh:[conn=0] Received key exchange request
DEBUG:asyncssh:[conn=0] Beginning key exchange
DEBUG:asyncssh:[conn=0] Completed key exchange
INFO:asyncssh:[conn=0] Beginning auth for user <REDACTED>
DEBUG:asyncssh:[conn=0] Received authentication banner
DEBUG:asyncssh:[conn=0] Trying public key auth with rsa-sha2-256 key
INFO:asyncssh:[conn=0] Auth failed for user <REDACTED>
INFO:asyncssh:[conn=0] Connection failure: Permission denied
INFO:asyncssh:[conn=0] Aborting connection
```

From the looks of it, only one key was offered.. so I'm not sure if it's using my ssh-agent in the newer release or not. Is there any guidance you can please give me? Here's what my connection code looks like:

```python
            try:
                options = dict(
                    host=host_ip,
                    port=port,
                    tunnel=self.tunnel,
                    known_hosts=None
                )

                async with asyncssh.connect(**options) as conn:
                    return {host_ip: await conn.run(command)}
```

**Comment by ronf** [comment]
Looking at the two traces, it appears that the 2.2.1 release tried two different RSA client keys, while 2.4.2 only tried a single RSA client key. If you add the argument "config=None" with 2.4.2, does that change anything? One of the differences between those two releases is the addition of support for `.ssh/config` files. Perhaps you have something in your config which is changing which client keys it tries to use? Config file support was added in 2.3.0, which would have been just after 2.2.1.

**Comment by kryptek** [comment]
> Looking at the two traces, it appears that the 2.2.1 release tried two different RSA client keys, while 2.4.2 only tried a single RSA client key. If you add the argument "config=None" with 2.4.2, does that change anything? One of the differences between those two releases is the addition of support for `.ssh/config` files. Perhaps you have something in your config which is changing which client keys it tries to use? Config file support was added in 2.3.0, which would have been just after 2.2.1.

Success! :) Thanks a lot. I looked at the commits from 2.2.x onward but wasn't able to pin down exactly what I should do.

**Comment by ronf** [comment]
Glad to hear that worked - thanks for confirming!
