### ISSUE TITLE
Request for connection_id field in connection_made and connection_lost

### ISSUE THREAD

**Issue by cratuki** [ronf/asyncssh#339]
Consider if you have an application where multiple users ssh into it. The developer wants to create a different session for each user in the application layer. In this way, they can target a display update to connection 0, but not to connection 1.

I have considered how to achieve this. My first attempt was through the user of connection_made/connection_lost. In detail: class asyncssh.SSHServer has callbacks connection_made and connection_lost. But there is no common key supplied to these two methods. So you do not have a way to identify which connection_made corresponds to which connection_lost.

Could the signatures be changed so that they always supplied a handle for the connection, such as connection_id?

**Comment by ronf** [comment]
This can already be done today, and in fact this use case was what led me to build AsyncSSH (and the server support in it in particular) in the first place. Take a look at https://asyncssh.readthedocs.io/en/latest/#serving-multiple-clients as an example for how to do this.

Basically, you set up a server with asyncssh.listen() and specify a process factory to run each time a new client session is opened to it. Within that handler, you can create objects corresponding to each new client and keep track in something like a class variable of a list of all the currently open sessions. If you want to assign these connections numeric connect IDs, you can, but that may not be necessary as you can use the client objects themselves as a way to distinguish which client you want to send to.

Each process has a separate stdin, stdout, and stderr, so when you write data you simply choose which process's stdout or stderr to write to. Similarly, if you want to read input from the connections, you can have separate coroutines reading from each of the separate process's stdin streams.

This could all be done with low-level callbacks like connection_made/connection_lost (and indeed that's how the process_factory mechanism is implemented internally), but you're probably better off using the process API to do this, as it is much simpler.

**Comment by cratuki** [comment]
Thanks, this led to a decent solution.
