### ISSUE TITLE
Make test of chacha20-poly1305 optional

### ISSUE THREAD

**Issue by vincentbernat** [ronf/asyncssh#34]
Hey!

OpenSSL 1.0.2d, as installed on my system, is unable to handle chacha20-poly1305 cipher. Therefore, several tests are failing:

```
======================================================================
ERROR: test_key (tests.test_public_key.TestRSA) [Export OpenSSH private (chacha20-poly1305@openssh.com)] (keytype=2048)
Check key import and export
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-asyncssh-1.3.0/tests/test_public_key.py", line 854, in check_openssh_private
    self.export_openssh_private(cipher)
  File "/build/python-asyncssh-1.3.0/tests/test_public_key.py", line 314, in export_openssh_private
    select_passphrase(cipher), cipher)
  File "/build/python-asyncssh-1.3.0/asyncssh/public_key.py", line 352, in write_private_key
    f.write(self.export_private_key(*args, **kwargs))
  File "/build/python-asyncssh-1.3.0/asyncssh/public_key.py", line 244, in export_private_key
    cipher_name) from None
asyncssh.pbe.KeyEncryptionError: Unknown cipher: chacha20-poly1305@openssh.com
```

As far as I know, no official version of OpenSSL supports this cipher.

**Comment by ronf** [comment]
I'll see what I can do about making the test conditional on whether the cipher is available or not.

In terms of support for chacha20-poly1305, AsyncSSH isn't looking for it in OpenSSL. It gets it from libnacl and libsodium. See the 'Optional Extras' section of the installation instructions at http://asyncssh.readthedocs.org/en/latest/#optional-extras.

**Comment by vincentbernat** [comment]
My bad, I did spot some checks with OpenSSL on some tests, but the tests were in fact failing earlier because libnacl/libsodium weren't installed, so the chacha20-poly1305 cipher wasn't registered.

**Comment by ronf** [comment]
Vincent, I took a closer look at this and there were a few places where the checks for bcrypt and libnacl were either missing or not quite right. I have checked changes into the 'develop' branch that should fix this now, though. If you get a chance, please let me know if this fixes the problem you saw.

Thanks for the report!

**Comment by vincentbernat** [comment]
Yes, the latest commit in develop fixes the problem. Thanks!
