### ISSUE TITLE
Question about running the simple_client.py and enable X11 forwarding

### ISSUE THREAD

**Issue by wjcqmz520** [ronf/asyncssh#342]
Thanks for your time and help. 
**First question**: I failed to run the basic simple_client.py.

```
import asyncio, asyncssh, sys
import logging
logging.basicConfig(level='DEBUG')

async def run_client():
    async with asyncssh.connect(host='xxx', username='xxx',client_keys=None, known_hosts=None) as conn:
        print("{}: Trying to connect".format(host))
        result = await conn.run('echo "Hello!"', check=True)
        print(result.stdout, end='')
try:
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```
But I get the error as follows: 

```
INFO:asyncssh:[conn=0] Auth failed for user ***
INFO:asyncssh:[conn=0] Connection failure: Permission denied
INFO:asyncssh:[conn=0] Aborting connection
SSH connection failed: Permission denied
```
I'm sure the user and host are given correctly as I can ssh into the server with the ssh command.

**Second question:** Can you please give an example regarding how to enable X11 forwarding with the lib? Thanks.

**Comment by ronf** [comment]
The library won't prompt you for a password. Did you provide one in your test? You could alternately log in with a client key, but you have explicitly disabled that by setting client_keys=None.

To enable X11 forwarding, just make sure you have the DISPLAY environment variable set and then add "x11_forwarding=True" as one of the arguments in the create_session(), create_process(), or run() call, or whatever other method you are calling to create a new SSH session. There are some other x11 related variables you might want to set as well. For the full list, take a look at https://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SSHClientConnection.create_session.

**Comment by wjcqmz520** [comment]
Thanks for the prompt reply. There's no password for this ssh connection, so I didn't include that in the script. I tried before with the client_key, but got a similar error someone posted before: `asyncssh.public_key.KeyImportError: Passphrase must be specified to import encrypted private keys`. Any other suggestions?
I'll look into the document and give it a try once fixing this.

**Comment by ronf** [comment]
Are you saying the account on the destination system has an empty password? If so, you'll probably still need to specify `password=''` explicitly as one of the arguments when opening the connection to get it to attempt password auth.

As for attempting to use client keys, it sounds like the key you used was encrypted with a passphrase. To load that key into AsyncSSH, you'll need to specify the passphrase to use to decrypt it. This can be be provided via the `passphrase` argument when you open the connection, along with specifying `client_keys`. Alternately, if that key was loaded into an SSH agent you have running and SSH_AUTH_SOCK is set in your environment, you may be able to get access to the client keys through that. Just leave out the `client_keys` argument to get it to use the default keys.

**Comment by wjcqmz520** [comment]
Thanks for the help. I think I'm able to fix this and will try the suggestion soon. 
Closing the thread...
