### ISSUE TITLE
Example of scp multiple file list?

### ISSUE THREAD

**Issue by sgreszcz** [ronf/asyncssh#347]
I'm trying to send a list of multiple files to download via SCP.  I'm able to get a single file to work (file = '/var/logs/cert.log') and wildcards (file = '/var/logs/*.log').  However if I try to pass in a list of files I get the exception:

```
TypeError("can't concat list to bytes")
```

Does anyone have an example on how to download multiple files using asyncssh.scp?  I've tried to interpret the docs and api docs...

**Comment by ronf** [comment]
Which function are you calling? The function asyncssh.scp" doesn't take an argument named "file". Here's the signature and default argument values:

```python
async def scp(srcpaths, dstpath=None, *, preserve=False, recurse=False,
              block_size=SFTP_BLOCK_SIZE, progress_handler=None,
              error_handler=None, **kwargs)
```

Here's an example of copying multiple files:

```python
asyncssh.scp(['file1', 'file2', 'file3'], 'remote_host:remote_dir')
```

Like the command like scp, this can copy files in either direction, depending on where you add the 'remost_host:'. You can even copy from one remote machine to another without an intermediate step of copying to the local machine.

If you want to open a connection to the destination host and reuse it for multiple transfers, you can do something like:

```python
with asyncssh.connect('remote_host') as conn:
    asyncssh.scp(['file1', 'file2', 'file3'], (conn, 'remote_dir1'))
    asyncssh.scp(['file4', 'file5'], (conn, 'remote_dir2'))
```

The tuple of an open connection object and a directory name replaces the 'remote_host:remote_dir' syntax in this case. This can also be useful if you need to pass additional arguments when opening the connection.

You can put wildcards in any of these filenames, and can also leave out the directory if you want to copy to the current working directory on the target.

**Comment by sgreszcz** [comment]
ok, great, that helps me.  I've built my functions (downloading) like this, but for some reason passing in a list of path strings rather than a single remote filename string wasn't working.  I'll try it again now.

```
def main():
    create_download_directories(local_download_dir, expressway_hostnames)

    asyncio.get_event_loop().run_until_complete(run_multiple_scp_clients(expressway_hostnames, logs_to_download, local_download_dir))


# Open an SSH connection and asynchronously retrieve the logfiles
async def run_scp(host, password, remote_file, local_path):
    local_path_with_hostname = f'{local_path}/{host}/'
    async with asyncssh.connect(host, username='root', password=password, known_hosts=None) as conn:
        return await asyncssh.scp((conn, remote_file), local_path_with_hostname, preserve=True)

# Asynchronously run SCP downloads to multiple hosts in parallel
async def run_multiple_scp_clients(hostname_dict, files_to_download_list, local_path):
    tasks = (run_scp(host, hostname_dict[host], files_to_download_list, local_path) for host in hostname_dict)
    results = await asyncio.gather(*tasks, return_exceptions=True)
    print(f"results: {results}")


    for i, host in zip(results, hostname_dict):
        if isinstance(i, Exception):
            logging.error(f"An error '{i!r}' occurred while requesting data from {host}.")
        elif i is None:
            logging.debug(f"Task to retrieve logs from {host} succeeded.")
        else:
            logging.error(f"Unknown error when connecting to {host}.")


def create_download_directories(download_path, directory_of_hosts):
    for host in directory_of_hosts:
        path = pathlib.Path(f'{download_path}/{host}/')
        path.mkdir(parents=True, exist_ok=True)

**Comment by ronf** [comment]
If you are using the tuple syntax for the files, you need to pass in a list of tuples (repeating "conn" multiple times). In other words, it would look something like:

```python
asyncssh.scp([(conn, 'file1'), (conn, 'file2'), (conn, 'file3')], 'local_dir')
```

It won't work if you try to pass in something like `(conn, ['file1', 'file2', 'file3'])`.

**Comment by sgreszcz** [comment]
ah, thanks.  That was definitely what I was doing wrong.  Trying to use the existing ssh connection (conn) and pass in a list of the files to scp download in that open connection.

**Comment by ronf** [comment]
If you pass "conn" in multiple times, it will reuse that connection for all of the transfers. It's just that the code is expecting a list of objects which are either tuples of exactly 2 items or a string with ':' as the hostname separator. Note also you can pass in multiple connections this way, with each remote file potentially coming from a different source.
