### ISSUE TITLE
SFTP file like object

### ISSUE THREAD

**Issue by WolkoDav** [ronf/asyncssh#35]
Hello, how can I put file like object (for ex. cStringIO)  with sftp into remote host?

**Comment by jquast** [comment]
Probably best performed using paramiko, not pexpect.

https://github.com/paramiko/paramiko/blob/master/demos/demo_sftp.py#L106

**Comment by WolkoDav** [comment]
I use asyncssh in tornado application.
I need async ssh connection and execute.

2015-11-02 18:02 GMT+03:00 Jeff Quast <notifications@github.com>:

> Probably best performed using paramiko, not pexpect.
>
> https://github.com/paramiko/paramiko/blob/master/demos/demo_sftp.py#L106
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ronf/asyncssh/issues/35#issuecomment-153043969>.
>



-- 
С уважением,
Иван Кривошеев.
py.krivosheev@gmail.com

**Comment by ronf** [comment]
Unfortunately, AsyncSSH doesn't have a helper function that specifically covers this case right now. The higher-level functions like get/put/copy all expect to take file names, not already open file-like objects.

Your best bet with the current version would be to do an sftp.open() of a remote file and write your own loop to read bytes from your local file-like object and write them to the remote SFTP file object. The resulting code would look something like:

```python
import asyncio, asyncssh, io, sys

@asyncio.coroutine
def run_client():
    with (yield from asyncssh.connect('localhost')) as conn:
        with (yield from conn.start_sftp_client()) as sftp:
            with io.StringIO('Test data\n') as src:
                with (yield from sftp.open('test.txt', 'w')) as dst:
                    while True:
                        data = src.read(32768)
                        if not data:
                            break

                        yield from dst.write(data)

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SFTP operation failed: ' + str(exc))
```

The `src` object can be any file-like object, and you can adjust the buffer size in the read() call to whatever you like.

**Comment by WolkoDav** [comment]
Thanks. this is what you need

2015-11-03 7:11 GMT+03:00 Ron Frederick <notifications@github.com>:

> Unfortunately, AsyncSSH doesn't have a helper function that specifically
> covers this case right now. The higher-level functions like get/put/copy
> all expect to take file names, not already open file-like objects.
>
> Your best bet with the current version would be to do an sftp.open() of a
> remote file and write your own loop to read bytes from your local file-like
> object and write them to the remote SFTP file object. The resulting code
> would look something like:
>
> import asyncio, asyncssh, io, sys
> @asyncio.coroutinedef run_client():
>     with (yield from asyncssh.connect('localhost')) as conn:
>         with (yield from conn.start_sftp_client()) as sftp:
>             with io.StringIO('Test data\n') as src:
>                 with (yield from sftp.open('test.txt', 'w')) as dst:
>                     while True:
>                         data = src.read(32768)
>                         if not data:
>                             break
>
>                         yield from dst.write(data)
> try:
>     asyncio.get_event_loop().run_until_complete(run_client())except (OSError, asyncssh.Error) as exc:
>     sys.exit('SFTP operation failed: ' + str(exc))
>
> The src object can be any file-like object, and you can adjust the buffer
> size in the read() call to whatever you like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ronf/asyncssh/issues/35#issuecomment-153234552>.
>



-- 
С уважением,
Иван Кривошеев.
py.krivosheev@gmail.com
