### ISSUE TITLE
protect known_hosts parsing

### ISSUE THREAD

**Issue by parmentelat** [ronf/asyncssh#36]
my `known_hosts` file had an odd line - that contained a single `=`
in that case a simple client [as copied from here](http://asyncssh.readthedocs.org/en/latest/) crahsed with an exception
IMHO such lines could just be ignored, which is what `ssh` does apparently

    ~/git/asyncio-samples $ ./myssh2
    Exception in callback SSHConnection.connection_made(<_SelectorSoc...e, bufsize=0>>)
    handle: <Handle SSHConnection.connection_made(<_SelectorSoc...e, bufsize=0>>)>
    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/events.py", line 125, in _run
        self._callback(*self._args)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/asyncssh/connection.py", line 456, in connection_made
        self._connection_made()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/asyncssh/connection.py", line 1753, in _connection_made
    self._peer_addr, self._port)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/asyncssh/known_hosts.py", line 159, in match_known_hosts
    entries = _parse_entries(known_hosts)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/asyncssh/known_hosts.py", line 94, in _parse_entries
    line) from None
    ValueError: Invalid known hosts entry: =
    SSH connection failed: Disconnect Error: Connection lost

**Comment by ronf** [comment]
Some errors in the known_hosts file are ignored, such as not being able to parse the key. The thinking there is that future key formats might be defined that other clients understand but AsyncSSH doesn't. However, I'm not sure it is a good idea to ignore ALL errors. If the line looks nothing at all like what an entry should look like, it seems like it would be better to warn the user that there's something that doesn't belong in that file.

After discovering this problem in the file, why wouldn't you want to remove it and try again?

**Comment by parmentelat** [comment]
> On 18 Nov 2015, at 05:47, Ron Frederick <notifications@github.com> wrote:
> 
> Some errors in the known_hosts file are ignored, such as not being able to parse the key. The thinking there is that future key formats might be defined that other clients understand but AsyncSSH doesn't. However, I'm not sure it is a good idea to ignore ALL errors. If the line looks nothing at all like what an entry should look like, it seems like it would be better to warn the user that there's something that doesn't belong in that file.
> 
> After discovering this problem in the file, why wouldn't you want to remove it and try again?

fair enough; that’s what I did actually of course
I reported it because I was just in my first 3 minutes into asyncssh, and thought maybe this could be a showstopper to newcomers like me; and that maybe the issue had just been overlooked. 
But your answer shows it is not the case, so please just ignore this comment if you believe it’s the thing to do :)

Thanks in any case for providing this great addition to the asyncio ecosystem :)

**Comment by ronf** [comment]
Thanks very much for your interest, and please feel free to continue to post suggestions or questions, or report any other problems you encounter!
