### ISSUE TITLE
Asyncssh server hang?

### ISSUE THREAD

**Issue by NostalgiaRunner** [ronf/asyncssh#365]
Hello,

This library looks great and I'm eager to try it. Sadly though, I am unable to get the simple_server.py example working. When I generate a key and run it, I see nothing in the console, and when I try and connect with my standard ssh client on Linux, using `ssh 127.0.0.1:8022`, my Linux system throws an error with `ssh: Could not resolve hostname 127.0.0.1:8022: Name or service not known`. I am seeing no one else is having this issue. Is my client syntax wrong?

Thank you.

**Comment by ronf** [comment]
I don't think the syntax you are attempting to use is supported by the OpenSSH client. You need to use "-p" to specify an alternate port number. Also, for the simple server example, you'll probably want to specify a username. For instance:

```
ssh -p 8082 guest@127.0.0.1
```

You can also try:

```
ssh -p 8082 user123@127.0.0.1
```

In the latter case, you'll need to enter a password of 'secretpw'. For this particular example, those are the only two usernames which are accepted.

**Comment by NostalgiaRunner** [comment]
That did the trick. It was the port argument. Thank you so much!
