### ISSUE TITLE
Reading from tail -f piped to grep on remote host

### ISSUE THREAD

**Issue by MrOdds** [ronf/asyncssh#370]
I'd like to read and process output as it is generated from tail -f piped to grep from multiple ssh sessions.

With the actual files that I'm interested in I'm getting back output from one of the sessions only. Strangely, with test files it doesn't seem to work at all, here I'm focusing on the test files, hopefully the underlying issue is the same. 

I thought perhaps output was getting buffered, so have set bufsize to zero, but that hasn't helped. I'm getting same behaviour whether the command sent over ssh includes the pipe, or when seperating them out and having asyncssh pipe the results to the grep. 

Tail -f on it's own works fine, tail (without -f) piped to grep works fine, but not tail -f piped to grep.

There is probably something I've misunderstood, or am doing something really stupid, but so far have not been able to work out what, if you could have a look that would be greatly appreciated, and my apologies if this is not the right forum for such questions.

Below is the test script:

```
import os, sys
import asyncio, asyncssh

# Create four test files, each containing four lines
for i in range(0,4):
    fileName=f'example_input{i}.txt'
    with open(fileName, 'w') as writer:
        for j in (range(0,4)): writer.write(f"{fileName} {j}\n")

# Sending entire command as a string
async def run_client(host, command):
    async with asyncssh.connect(host) as conn:
        async with conn.create_process(command) as process:
            result = await process.stdout.readline()
            print(f"run_client: {result}")
            if not result:
                print(await process.stderr.readline())

#Letting asyncssh pipe output from tail command to grep
async def run_client_async_pipe(host, commandList):
    async with asyncssh.connect(host) as conn:
        proc1 = await conn.create_process(commandList[0], bufsize=0)
        proc2 = await conn.create_process(commandList[1], stdin=proc1.stdout, bufsize=0)
        result = await proc2.stdout.readline()
        print(f"run_client_async_pipe: {result}")

async def run_multiple_clients():
    current_path = os.getcwd()
    tasks = []
    for i in range(0,4):
        # Doesn't print any output when piped to grep, but tail -f on it's own does work
        command = f"tail -f -n +0 {current_path}/example_input{i}.txt | grep -w 0"
        # Commands that return work fine, such as tail without -f
        #command = f'tail -n +0 {current_path}/example_input{i}.txt | grep -w 0'
        tasks.append(run_client('localhost', command))
        commandList = command.split('|')
        tasks.append(run_client_async_pipe('localhost', commandList))
    tasks = tuple(tasks)
    await asyncio.gather(*tasks) 

try:
    asyncio.run(run_multiple_clients())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```

**Comment by ronf** [comment]
I think your issue here is probably with "grep". By default, it's only line-buffered when outputting to a terminal. However, the way you are running it here, it would be connected to a pipe. So, I think you have to change it to something like "grep --line-buffered -w 0". 

It might also work if you request a pseudo-tty in the create_process() calls. You could do that by passing in a terminal type. That might be enough to make grep think it is connected to a terminal, even though you are actually redirecting the output back into the SSH connection.

**Comment by MrOdds** [comment]
You're absolutely right, both suggestions worked!!

Thank you so much for your help, and great job with this library!
