### ISSUE TITLE
validating ssh keys

### ISSUE THREAD

**Issue by cinterloper** [ronf/asyncssh#371]
Is there example code available for how to validate individual user keys? 

I am implementing def validate_public_key(self, username, key)

When I try to hash myself with get_fingerprint or read_authorized_keys([..]).validate(key...) it appears to calculate a diff hash for the key on the wire and the authorized public key in the file.

I know they are the same ( I generated a fresh ed25519 key and put it both in the file and used -i to specify it on the wire)

**Comment by ronf** [comment]
If you just want to set different authorized keys depending on the user the client is trying to log in as, you don't actually need to implement your own instance of `validate_public_key`. Instead, you can call `set_authorized_keys` from within the `begin_auth` method, as shown in the second example at https://asyncssh.readthedocs.io/en/latest/#simple-server.

Take a look at https://asyncssh.readthedocs.io/en/latest/api.html#specifyingauthorizedkeys for the different things you can pass in via the set_authorized_keys() method. It can be a filename or list of filenames to load containing authorized key entries, or a set of entries previously loaded by `import_authorized_keys` or `read_authorized_keys`.

When you set authorized keys in this way, AsyncSSH will automatically call the validate() method on the authorized_keys object for you, taking into account all of the conditions in each authorized_keys entry when doing the match, so there's no need for you to replicate all that logic. You'd only need to implement `validate_public_key` yourself if you needed additional criteria at run time not currently supported by the existing `validate` method.

If you do implement the callback yourself, you would generally just want to do equality checks or "in" membership checks on the public key provided to the `validate` call against a set of allowed public key objects (loaded by something like `import_public_key` or `read_public_key`). AsyncSSH will take care of determining how to test whether keys are equal or not, depending on the type of key.

Note that `read_authorized_keys` expects authorized key entries, not public keys. A public key in the single-line OpenSSH format is very similar looking to an authorized keys entry, but authorized keys entries start with a pattern match against the host being accessed, and also have other optional parameters to limit when keys will match. If you are going to use `set_authorized_keys` or `read_authorized_keys`, you need to make sure what you provide is in that format.

**Comment by cinterloper** [comment]
Thanks for the tips, Ill try that approach this weekend.
