### ISSUE TITLE
SSHReader.readline blocking event loop

### ISSUE THREAD

**Issue by Fisch37** [ronf/asyncssh#375]
So I have an issue. I'm trying to constantly read from an existing SSHClientProcess while doing some other asynchronous actions. The code I currently have for that is this:
```py
async def processWatcher(self,process : asyncssh.SSHClientProcess):
    """Looks at any data the process receives.
    """
    while True:
        # if process.stdout.at_eof():
        #     break
        try:
            line = await process.stdout.readline()
            if line!="":
                logging.info(str(("SERVER: "+line).encode("utf-8")))
            await asyncio.sleep(0)
            pass
        except asyncio.CancelledError:
            logging.error("This task was cancelled?!")
    process.stdin.write_eof()
    process.stdin.close()
    process.close()
    logging.info("Watcher has reached EOF")
    pass

async def __waitShutdown__(conn):
    from time import perf_counter
    startTime = perf_counter()
    while perf_counter() - startTime < 60:
        print("Beep")
        await asyncio.sleep(1)
    conn.writeCommand("/stop")
    logging.info("Sent stop")
    pass
```

Theoretically, this should read from the stdout and every one second a Beep should appear. After 60 Seconds the client should send a stop command. This, however, is not what happens. What happens, is that I only get the output from the processWatcher and only one Beep. I think this is an issue with the readline command as a test script like
```py
import asyncio

async def test(stuff,delay):
    while True:
        print(stuff)
        await asyncio.sleep(delay)

async def main():
    await asyncio.gather(test("HI",0),test("HEY",0))

asyncio.run(main())
```
works just fine.

Any help on rewriting the processWatcher or the waitShutdown as well as other help is welcome. Ty! o/

**Comment by ronf** [comment]
How are you invoking the event loop here at startup, and the two coroutines (processWatcher and __waitShutdown__)?

Also, there's code here looking for CancelledError -- is your code attempting to cancel processWatcher in some cases?

I also see a writeCommand() call here - does that actually send a carriage return when it writes the command, assuming one is needed? Is it writing that command to process.stdin?

I don't see anything obvious that would prevent the "Beep" from appearing multiple times, or would prevent you from being allowed to write to process.stdin from a different coroutine than the one "blocked" in process.stdout.readline(). What you're trying to do looks like it should work, unless there's an issue in some of the code you left out.

Do you have a complete test case which reproduces the issue?

**Comment by Fisch37** [comment]
[That is the whole bit of code](https://pastebin.com/YVA3MNbk). As can be seen (maybe), I am trying to remotely launch a Minecraft Server. I am catching a CancelledError because for some reason (I suspect some signal over SSH) one is raised at the start. 

The writeCommand function uses stdin and sends a line feed (not a carriage return).

[This is a sample of a log](https://pastebin.com/Tiyq6bDi)

I have not found any other way to reproduce the issue sadly.

**Comment by ronf** [comment]
It looks like your problem here is in the call to asyncio.gather() in __main__. You left out the "await" in front of that, so the gather call is firing off the two tasks you requested it to start, but it's not waiting for them to complete. As a result, it's existing out of __main__, and therefore out of asyncio.run(), and that's causing the event loop to close (canceling all created tasks).

Adding "await" fixes it for me. The "Beep" messages come out once a second, and after 60 seconds it sends "/stop".

**Comment by Fisch37** [comment]
Oh damn
