### ISSUE TITLE
Disabling strictHostKey Check not working

### ISSUE THREAD

**Issue by hippm** [ronf/asyncssh#377]
Hey,

i use your library to connect to a bunch of devices and i deactivate the StrictHostkey Check. After upgrading to asyncssh==2.6.0 it stopped working. So i started looking and found that the deactivation of the strictHostKey check is not working properly with 2.6.0

I get the following error:
```
root:/# python test.py
SSH connection failed: [Errno 104] Connection reset by peer
root:/#
```
Testcode (test.py):
```python
import asyncio, asyncssh, sys

async def run_client():
    conn = await asyncssh.connect("localhost", known_hosts=None, username="admin", password="admin") 
    stdin, stdout, _ = await conn.open_session(term_type="vt100")
    response = await stdout.readuntil("$")
    print(f"{response}")
    await asyncio.sleep(1)
    stdin.write(f"ls -al\n")
    await asyncio.sleep(1)
    response = await stdout.readuntil("$")
    print(f"{response}")

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```

Steps:
- make sure known_hosts are empty
- Run test.py

I hope you can reproduce the bug and many thanks 
Greetings, Marco

**Comment by ronf** [comment]
Sorry, I'm not able to reproduce the problem here. The "Connection reset by peer" error suggests that the server side is closing the connection on you. Could you take a look to see if there's anything in your SSH server logs which might explain the failure? You might also want to enable client-side logging and see how far it gets before it fails. To enable logging, add lines like the following:

```python
    logging.basicConfig()
    asyncssh.set_log_level('DEBUG')
    asyncssh.set_debug_level(2)
```

Which version of SSH are you connecting to? There are some known issues with dropbear that can look like this.

**Comment by hippm** [comment]
Hey ronf thank you for your fast answer.
I added the Logger to the lines and here is the output:

```
root@6d3212b6c6e5:/# python test.py
INFO:asyncssh:Opening SSH connection to x.x.x.x, port 22
INFO:asyncssh:[conn=0] Connection to  x.x.x.x, port 22 succeeded
INFO:asyncssh:[conn=0]   Local address: x.x.x.x, port 44368
DEBUG:asyncssh:[conn=0] Requesting key exchange
DEBUG:asyncssh:[conn=0]   Key exchange algs: curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,ecdh-sha2-1.3.132.0.10,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256@ssh.com,diffie-hellman-group14-sha1,rsa2048-sha256
DEBUG:asyncssh:[conn=0]   Host key algs: sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-ed448-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-1.3.132.0.10-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,ssh-ed448,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,ecdsa-sha2-1.3.132.0.10,rsa-sha2-256,rsa-sha2-512,ssh-rsa-sha224@ssh.com,ssh-rsa-sha256@ssh.com,ssh-rsa-sha384@ssh.com,ssh-rsa-sha512@ssh.com,ssh-rsa
DEBUG:asyncssh:[conn=0]   Encryption algs: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
DEBUG:asyncssh:[conn=0]   MAC algs: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha256-2@ssh.com,hmac-sha224@ssh.com,hmac-sha256@ssh.com,hmac-sha384@ssh.com,hmac-sha512@ssh.com
DEBUG:asyncssh:[conn=0]   Compression algs: zlib@openssh.com,none
DEBUG:asyncssh:[conn=0] Received key exchange request
DEBUG:asyncssh:[conn=0]   Key exchange algs: curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,kexguess2@matt.ucc.asn.au
DEBUG:asyncssh:[conn=0]   Host key algs: ssh-rsa
DEBUG:asyncssh:[conn=0]   Client to server:
DEBUG:asyncssh:[conn=0]     Encryption algs: aes128-ctr,aes256-ctr
DEBUG:asyncssh:[conn=0]     MAC algs: hmac-sha2-256,hmac-sha2-512
DEBUG:asyncssh:[conn=0]     Compression algs: zlib@openssh.com,none
DEBUG:asyncssh:[conn=0]   Server to client:
DEBUG:asyncssh:[conn=0]     Encryption algs: aes128-ctr,aes256-ctr
DEBUG:asyncssh:[conn=0]     MAC algs: hmac-sha2-256,hmac-sha2-512
DEBUG:asyncssh:[conn=0]     Compression algs: zlib@openssh.com,none
DEBUG:asyncssh:[conn=0] Beginning key exchange
DEBUG:asyncssh:[conn=0]   Key exchange alg: curve25519-sha256@libssh.org
INFO:asyncssh:[conn=0] Connection failure: [Errno 104] Connection reset by peer
INFO:asyncssh:[conn=0] Aborting connection
SSH connection failed: [Errno 104] Connection reset by peer
root@6d3212b6c6e5:/#
```

Unfortunateley i cant get the server logs, the devices im connecting to are network appliance. They dont give a normal bash and i cant access the logfiles

**Comment by hippm** [comment]
I looked into the server with keyscan and got the following:

```
root:/# ssh-keyscan -H x.x.x.x
# x.x.x.x:22 SSH-2.0-dropbear_2017.75
<RSAKEY>
# x.x.x.x:22 SSH-2.0-dropbear_2017.75
# x.x.x.x:22 SSH-2.0-dropbear_2017.75
root:/#
```
It seems the appliance is using dropbear

**Comment by ronf** [comment]
Yeah - that's one of the versions of dropbear with the problem. See #368 and #263 for more discussion on this.

The dropbear issue was fixed in https://github.com/mkj/dropbear/commit/1a208c460b412113704c4d5f98585017ee0a6ccf, but not until October of last year. So, older versions will still have the problem.

If you know you are connecting to dropbear, the workaround is to reduce the number host keys algorithms that AsyncSSH advertises itself as supporting so that dropbear doesn't hit its limit of only looking at the first 20 entries for a compatible algorithm. Alternately, you can move 'ssh-rsa' earlier in the list, but that might cause you to use that instead of one of the stronger algorithms on other servers capable of supporting those stronger algorithms.

See #263 for some examples of how to set the server_host_key_algs argument to address this.

**Comment by ronf** [comment]
BTW, the reason that this only shows up when setting known_hosts to `None` is that AsyncSSH will advertise only algorithms which have corresponding known_hosts entries when you have a known hosts list. It's only when you set known_hosts to `None` that you're likely to list enough algorithms to trigger the dropbear issue.

**Comment by hippm** [comment]
Hey rofn,

Thank you for your help that "workaround" worked great!
So I'm closing this Issue because it is not a Problem in your library.

Ty
