### ISSUE TITLE
Small inconsistency in "About" and "Readme"

### ISSUE THREAD

**Issue by Hsilgos** [ronf/asyncssh#379]
Hi,
"About" tells that "It requires Python 3.4 or later"
When "README.md" tells "To use AsyncSSH 2.0 or later, you need the following: Python 3.6 or later"

**Comment by ronf** [comment]
Thanks for reporting this, but both statements are correct. AsyncSSH 1.x is supported on Python 3.4 or later, but AsyncSSH 2.x requires Python 3.6 or later.

**Comment by Hsilgos** [comment]
Ok, than sorry for bothering
