### ISSUE TITLE
ssh-agent

### ISSUE THREAD

**Issue by qix** [ronf/asyncssh#38]
Is there any plan to provide support for a local ssh-agent?

I'm trying to write a convenience/tooling wrapper, and perhaps a replacement for fabric/baker/etc. `asyncssh` fits the bill for the most part but the missing connection to a local ssh agent makes the library unusable.

Do you have any plan of including support? If not I can attempt an implementation of it as it is a necessity for the rest of my work.

**Comment by ronf** [comment]
I must admit I'm not that familiar with ssh-agent, as it's not something I use myself. However, it seems like it could be a useful capability to provide. Do you happen to know where I can find documentation on the protocol used?

**Comment by qix** [comment]
The protocol seems fairly trivial. I couldn't find an exact specification but a blog post that includes an example conversation[1] and the source in paramiko[2]

[1] http://ptspts.blogspot.com/2010/06/how-to-use-ssh-agent-programmatically.html
[2] https://github.com/paramiko/paramiko/blob/0b9d772a21a44af38ecceae0fdbae645e386bd9b/paramiko/agent.py

**Comment by ronf** [comment]
Thanks. Paramiko is LGPL, so I can use any of its code as a reference, but the other link there was a helpful overview. I also found the following documentation of the protocol:

https://anongit.mindrot.org/openssh.git/plain/PROTOCOL.agent

Am I correct in assuming that you're primarily looking for support in AsyncSSH  to get a list of available keys from the ssh-agent and use it perform private key operations, and that you don't immediately need to be able to add/remove keys or lock/unlock the agent?

**Comment by nchammas** [comment]
> so I can use

Did you mean "can't"?

**Comment by ronf** [comment]
Thanks, yes -- original comment edited!

**Comment by ronf** [comment]
Ok - I've just committed a first cut of ssh-agent support in the "develop" branch. There's a new "agent_path" argument in the create_connection() call and its variants which lets you specify the path to the agent socket. It will also automatically pick this up from the SSH_AUTH_SOCK environment variable if that is set. It will automatically use the agent when no client keys are explicitly provided, preferring that over the files in $HOME/.ssh when the agent is accessible. Feedback is welcome!

**Comment by ronf** [comment]
This feature is now merged back to master and available in AsyncSSH 1.4.0.
