### ISSUE TITLE
Question about connection closing

### ISSUE THREAD

**Issue by parmentelat** [ronf/asyncssh#39]
Hi there
this is more a question than an issue I am afraid, so feel free to redirect me to another channel

I am having problems getting SshClient.connection_lost() to trigger

My understanding - which obviously is wrong - was that I would call close() on the connection object, and that would cause the callback to trigger; but of course since SshClientConnection.close() is sychroneous and not a coroutine, it seems that I should await for something after I call close(), but I can't seem to figure out for what I should await..

Not sure if I am making myself clear, I can elaborate of course if needed

Thanks a lot - and happy new year :)

**Comment by redixin** [comment]
Got the same issue.

Calling `close()` just start connection closing and return immediately. Callback `connection_lost` will be called when connection is actually closed. You need a method like `wait_for_closed` but I can't tell where is it.
I made a workaround: create event object and set it in `connection_lost` callback, and just wait for it when needed.
I forgot to create an issue here, so thank you :)

**Comment by ronf** [comment]
You're right - there isn't currently a way to asynchronously wait for a close() on an SSHConnection object to finish. I have a wait_closed() method on SSHChannel which will allow you to wait for a channel to fully close, but not an equivalent for SSHConnection. It's a good idea, though, and pretty easy to add.

The only thing is that it would only complete when the connection was explicitly closed or when the underlying TCP connection was broken, though -- having the last channel close on a connection would not be enough to trigger it.

I'll add this to my list of enhancements to provide. Thanks for the suggestion!

**Comment by ronf** [comment]
Ok - I've just finished adding a wait_closed() method to SSHConnection in the "develop" branch. As expected, this method is a coroutine that should wait until the connection has fully closed and the connection_lost() method on the owner has been called.

In the process of doing this, I noticed that the _cleanup() method on a connection was not being called when close() or disconnect() was called explicitly, or when the connection object was used as a context manager. It's possible that this may be related to the memory leak reported in #37.

@redixin: Would you mind trying your test again to see if this commit helps with the memory leak you saw? It's possible that it won't solve it completely, but I'm curious if this makes a noticeable difference.

**Comment by parmentelat** [comment]
Thanks a lot Ron; I am in no position to provide fully reliable data about the improvement with this new release, as I am in a rather early stage of my project, but it does feel more efficient with commit 3d077cb98

FYI my goal is to interact with circa 300 hosts in parallel, a substantial portion of which being down or in otherwise bad condition; so I expect to see a wide variety of situations, and to still run into quite a few issues before I get this to work as expected :)

**Comment by ronf** [comment]
No problem.

It sounds like your application will give the error handling code a good workout when you get it running, which is an area that definitely isn't stressed as much as I'd like. I'm continuing to add explicit unit tests to make sure those code paths are correct, but if you run into any issues feel free to post them here. Feature requests are welcome, too!

**Comment by ronf** [comment]
This feature is now merged back to master and available in the AsyncSSH 1.4.0 release.
