### ISSUE TITLE
Proxying requests over SSH using HTTPX

### ISSUE THREAD

**Issue by squili** [ronf/asyncssh#390]
I'm trying to proxy my HTTPX network calls, but it seems a little confusing. While I get the basic concept (make a listener, make calls to that instead), if I specify `http://localhost:port` as my target url, I lose HTTPS and it seems like it'd be abusing features either way. Is there a better way of doing this through SSH? I'm currently just uploading a proxy server and running it on the target machine, which works, but it'd be nice to do it purely through SSH.

**Comment by ronf** [comment]
Are you trying to do use a browser as the HTTP/HTTPS client? If so, you probably will need a proxy that you can configure in the browser. AsyncSSH (and other SSH implementations) generally don't support being an HTTP proxy directly, but it is possible with AsyncSSH to make it act as a bare-bones SOCKS proxy, which you can configure a browser to use.

To do this, you first open an SSH client connection and then call forward_socks() on that, specifying a host & port to listen on. Then, in your browser, configure a SOCKS proxy on that host & port. The host can be an empty string here to bind on all addresses, and a common port number to use for this is port 1080. In the browser, you'd configure a SOCKS proxy pointing to "localhost" and whatever port you selected.

For instance:

```python
import asyncio, asyncssh, logging, sys

async def run_client():
    async with asyncssh.connect('localhost') as conn:
        listener = await conn.forward_socks('', 1080)
        await listener.wait_closed()

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```

You should be able to use this SOCKS proxy to forward either HTTP or HTTPS traffic.

This is the equivalent of specifying the "-D [address]:port" option to OpenSSH.

**Comment by squili** [comment]
Yes, this is exactly what I wanted! Thank you!
