### ISSUE TITLE
Ssh agent forwarding

### ISSUE THREAD

**Issue by qix** [ronf/asyncssh#40]
Thanks a lot for getting the ssh-agent hooked up. It's working great and we're now 90% of the way to using asyncssh pretty heavily in production, but hit another roadblock which should be a bit easier to solve.

We rely on agent forwarding to grant access to some of our servers and/or git repositories. Afaik it works fairly simply, by just opening a unix socket on the remote side and forwarding all read/write traffic to the local socket.

I'm busy investigating implementing it outside of the library, but it likely makes sense as an additional feature inside asyncssh too.

**Comment by qix** [comment]
A bit more digging found the draft for ssh agent channel:
https://tools.ietf.org/html/draft-ietf-secsh-agent-02

**Comment by ronf** [comment]
Thanks. I agree that this seems like a useful thing to support.

I took a look at the draft link you added above, but it looks like that describes a very different ssh-agent protocol than what I implemented from OpenSSH which is described at:

    https://anongit.mindrot.org/openssh.git/plain/PROTOCOL.agent

They have similar operations, but the operation numbers are completely different, and from a quick look at the OpenSSH source I don't see any sign of support for the protocol above except for recognizing its FAILURE code:

/* additional error code for ssh.com's ssh-agent2 */
#define SSH_COM_AGENT2_FAILURE                  102

I'm going to do a bit more looking around to see if I can find documentation for the OpenSSH version of agent forwarding. It doesn't seem to appear in the PROTOCOL or PROTOCOL.agent doc, unfortunately. I see that OpenSSH supports a channel request of type "auth-agent-req@openssh.com" and a channel type of "auth-agent@openssh.com", but haven't found a doc which describes those yet.

**Comment by ronf** [comment]
I spent some time this week looking more closely at OpenSSH's ssh-agent forwarding. It appears that ssh-agent protocol used for forwarding is completely unchanged from the local ssh-agent protocol. There's just a new channel type called "auth-agent@openssh.com" which can be opened from the server to the client and a channel request "auth-agent-req@openssh.com" that the client can send to the server when opening a new client session that triggers the server to set up this forwarding. The forwarding is then basically the same as UNIX domain socket forwarding, but it is directed to whatever path on the client is used to reach the ssh-agent.

I've just finished checking in full support for both general UNIX domain socket forwarding and SSH agent forwarding in the "develop" branch. Agent forwarding can be enabled with a new "agent_forwarding" boolean argument on the asyncssh.create_connection() call.

@qix, if you get a chance to try this, I'd appreciate it. Let me know what you think!

**Comment by qix** [comment]
@ronf This is great. Thanks so much.

The feature works just as expected and was the last remaining thing to switch over to tooler [working name for my fabric replacement] w/ asyncssh. Seeing a couple minor issues elsewhere but will open seperate issues for them.

**Comment by ronf** [comment]
Thanks for the report, @qix!

I'm not sure if you have a use for it or not, but I'm just about finished with ssh-agent support on the server side. This means you can use AsyncSSH running as a server to forward ssh-agent requests back to the client connected to it. So, if you wanted to have a server which turned around and made some other SSH client connection, you could do that client handshake using keys provided by the original client, if the original client advertises that it supports agent forwarding. The API for this is pretty simple -- you just pass in your SSHServerConnection object in place of a socket name in the 'agent_path' argument when calling create_connection/open_connection on the new client connection.

I'm also adding permission enforcement for UNIX domain socket and agent forwarding (in both authorized_keys and in certificates). All of this should be going into an AsyncSSH 1.5 release soon.
