### ISSUE TITLE
change default branch to "develop"

### ISSUE THREAD

**Issue by ktdreyer** [ronf/asyncssh#403]
Would you please change the default branch from "master" to "develop"?

[GitHub's settings](https://github.com/ronf/asyncssh/settings/branches) say:

> Default branch
> The default branch is considered the “base” branch in your repository, against which all pull requests and code commits are automatically made, unless you specify a different branch.

I almost accidentally submitted my recent PR against "master" until I noticed by chance that there were two branches in this repo. It would be a lot easier for newcomers to always submit PRs against "develop".

**Comment by ronf** [comment]
While I would like people to submit pull requests to the 'develop' branch by default, I'd still prefer someone cloning AsyncSSH to default to 'mater'. Is there a way to control the default branch separately for these two actions? When I go to update the default branch, Github warns that it may have an affect on future clone actions.

**Comment by ktdreyer** [comment]
Right, this setting controls both.

As a new contributor, I would expect to clone "the very latest" code, aka `develop` by default. If I want to go back and look at older stable code for some reason, I will look at Git tags. That matches how other open-source projects work.

**Comment by ronf** [comment]
Fair point. I guess if you're taking the trouble to check out the code, it probably makes sense you'd want the latest, especially if your intention is to eventually contribute something back, and in that case I'd definitely want people submitting pull requests on the develop branch.

Ok - this is done. Thanks for the suggestion!
