### ISSUE TITLE
Please provide some information on generating ssh_user_ca and ssh_host_key

### ISSUE THREAD

**Issue by AndKe** [ronf/asyncssh#424]
I am afraid of messing up this step, it would be very nice if the documentation pointed to some basic key generation info.
Thank you.

**Comment by ronf** [comment]
There are many different ways keys can be used, so it's hard to come up with general instructions for this. AsyncSSH provides all the primitives you need to create both keys and certificates (both OpenSSH and X.509), but how you store keys, whether to protect them with passphrases, and how you feed in the passphrase when you need to use these keys later on can vary widely depending on your application. Whether to use plain keys or certificates also varies depending on your application, and whether you have a way to generate and distribute new certificates to each new user/host that needs one.

That said, you can find documentation for all of the functions at https://asyncssh.readthedocs.io/en/latest/api.html#public-key-support. More specifically, you'll usually start by generating a new private key with [generate_private_key](https://asyncssh.readthedocs.io/en/latest/api.html#generate-private-key), which returns an [SSHKey](https://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SSHKey). This key can be directly used as an SSH host or user key, or it can be used as a certificate authority (CA) key that you use to sign certificates associated with other private keys.

If you want to use a key directly, there are methods on [SSHKey](https://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SSHKey) which will let you write a private key out to a file (optionally encrypted with a passphrase) and also write the public key corresponding to that private key, to be provided to systems you want to trust this new private key, generally putting the public key in a known_hosts or authorized_keys file on the remote system.

If you want to generate certificates, you'd have to create additional private keys corresponding to a user or host and then call a method like [generate_host_certificate](https://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SSHKey.generate_host_certificate) or [generate_user_certificate](https://asyncssh.readthedocs.io/en/latest/api.html#asyncssh.SSHKey.generate_user_certificate) on your private CA key, passing in the user/host key you want to sign along with other information to put into the certificate. This will give you back an [SSHCertificate](https://asyncssh.readthedocs.io/en/latest/api.html#sshcertificate) which has its own methods to export or write it to a file in various formats. The resulting certificate can then be used along with a private key to authenticate to anything which trusts the CA key which signed that certificate. In this case, you'd copy the public key of the CA to the remote system and mark it as a certificate authority in authorized_keys or known_hosts.

If you have a specific use can in mind, I'd be happy to provide something more concrete. The current documentation expects the caller to already know the basics of SSH authentication and the format of files like known_hosts and authorized_keys.

**Comment by AndKe** [comment]
yes, I've found ssh-keygen -t ed25519 to be both compatible and adequate. Thank you.

**Comment by ronf** [comment]
Yes - AsyncSSH is compatible with keys generated by OpenSSH, as well as some other formats, so using ssh-keygen should work fine. However, if you did want to generate an ed25519 key directly from AsyncSSH and write it to a file in OpenSSH format, you could do something like:

```python
    key = asyncssh.generate_private_key('ssh-ed25519')
    key.write_private_key('id_ed25519')
```

You could write out the public key using:

```python
    key.write_public_key('id_ed25519.pub')
```

This should produce output equivalent to `ssh-keygen`.
