### ISSUE TITLE
Clearing stdout for multiple command execution?

### ISSUE THREAD

**Issue by lamoni** [ronf/asyncssh#430]
Hello,

To avoid XY problem, I'm just going to explain what I'm trying to do, and then how I'm doing it.

I've got a list of commands, I want to run those commands in a for loop against a single device using the same persistent ssh session

The only issue I am running into is that when I use .run() multiple times, the outputs of the commands I run accumulate in stdout (which makes sense). Is there a way to clear the stdout SSH stdout after I run a command get its output? (Or better yet, if there's a way to properly do this, I'd appreciate hearing it)

Thanks!

**Comment by ronf** [comment]
If you are using run(), each command should be executed on its own SSH channel on a shared SSH connection, and you shouldn't have a problem with the returned output accumulating like that.

If you are trying to run the commands on a single SSH channel using an SSH "shell" session, it becomes much harder to tell where the output of one command ends and the next begins, unless you design the commands to always output something specific that signals the end of the output and have your client keep reading until it sees that. For instance, if you set your shell prompt to something you know won't appear in the output, you can do a `readuntil()` looking for that unique prompt. See #227 for some discussion about this.

Unfortunately, without special output like this, there's no way to reliably know when a command actually finishes running. So, even if you cleared all the existing output from the output buffer (which you can do with something like `collect_output()` on the SSHClientProcess class), there's no guarantee that the server won't send more output after you try and clear it out.
