### ISSUE TITLE
update project description

### ISSUE THREAD

**Issue by vapier** [ronf/asyncssh#431]
the readme file says:
> ### Prerequisites
> To use AsyncSSH 2.0 or later, you need the following:
> * Python 3.6 or later

but then the [GH About description](https://github.com/ronf/asyncssh) says:
> It requires Python 3.4 or later and the Python cryptography library for some cryptographic functions.

prob should just delete that sentence entirely :).

**Comment by ronf** [comment]
Actually, both statements are true. The AsyncSSH 1.x releases supported Python 3.4 and later, and those remain available if you're stuck for some reason on an older Python release. However, for AsyncSSH 2.0 and later, I changed the minimum Python version to 3.6, allowing me to take advantage of the new async and await syntax and a few other newer Python features.

That said, I agree the difference could be confusing, and it's not adding a lot of value, so I've gone ahead and removed the version info in the "About".

Thanks!
