### ISSUE TITLE
Run multiple commands on multiples hosts

### ISSUE THREAD

**Issue by Emilianocm23** [ronf/asyncssh#436]
Hello, i was trying to run multiple commands (run commands one by one and wait for each command to complete before sending new one), but i wasnt able to do it myself since i dont fully understand asyncssh and i have just started learning it. 

I tried using this code: https://github.com/ronf/asyncssh/issues/241#issuecomment-565681956

But its executing all the commands at the same time and a lot of them end with an error.

*i dont care about keeping stdout, i just want to run the commands one by one on multiple hosts i know they work
Thanks for your help!

**Comment by Emilianocm23** [comment]
Thanks for your fast reply, im getting this output while running the code you published

![image](https://user-images.githubusercontent.com/74161942/149546561-6e7039ee-086c-403e-bbd3-6be9500018e2.png)

**Comment by ronf** [comment]
The "exit status" lines there mean that AsyncSSH successfully sent the command and the server closed the session after running it, returning whatever exit status the command generated. So, that's not an error at the SSH level.

As for not running all the commands, I'm not sure I can help with that, as AsyncSSH is just treating the command as an opaque string and it's up to the target host to interpret it. If you run "ssh" from the command line with the same target host and command sequence, does it work in that case?

**Comment by Emilianocm23** [comment]
> The "exit status" lines there mean that AsyncSSH successfully sent the command and the server closed the session after running it, returning whatever exit status the command generated. So, that's not an error at the SSH level.
> 
> As for not running all the commands, I'm not sure I can help with that, as AsyncSSH is just treating the command as an opaque string and it's up to the target host to interpret it. If you run "ssh" from the command line with the same target host and command sequence, does it work in that case?

Thanks, the chained command had an error in it and thats why i wasnt able to run in. 

I have fixed my commands and now they are able to run as a single command like "echo foo; ls abc; sleep 5", how can i run this single command on multiple hosts at the same time? should i use same script?

* i dont want to wait for output, it would be nice to send the command (command takes like 10 seconds running but i dont need to wait)

**Comment by Emilianocm23** [comment]
I had the answer here https://github.com/ronf/asyncssh/issues/241#issuecomment-566836146
Thanks for your help, this is a great library with great support

**Comment by ronf** [comment]
I'm glad to hear AsyncSSH is working for you...

As you figured out, you can put a single command in the list, but you could also greatly simplify the code if you only need to parallelize a single run() call on each host. For instance:

```python
import asyncio, asyncssh

async def run_commands(host, cmds):
    """Run a set of commands on a host"""

    await asyncssh.connect(host).run(cmds)

async def parallel_run(hosts, cmds):
    """Run a set of commands on a set of hosts in parallel"""

    results = [run_commands(host, cmds) for host in hosts]
    await asyncio.gather(*results)

hosts = ('localhost', '127.0.0.1', '::1')
asyncio.run(parallel_run(hosts, 'echo foo; ls abc; sleep 5'))
```

Regarding not needing to wait for the output, that's actually a bit dangerous, as the commands you are running might fail if they try to produce output and find that the SSH channel is closed. It's better to keep the session open until the server explicitly closes it. If you wanted to, though, you could be running other asyncio tasks in parallel with running these commands. For instance, you can add other things to the "results" list before you call asyncio.gather().
