### ISSUE TITLE
Execute commands with paged/large outputs using asyncssh

### ISSUE THREAD

**Issue by mon-216** [ronf/asyncssh#437]
Hello Ronf, Greetings!

I have to access various vendor routers, execute some commands and process the output. 
Workflow is something like this - 
ssh to multiple devices in parallel
in each device, run commands sequentially
process the output of each command after execution
disconnect the ssh connection

Problem is, when the output is large and paginated, I am unable to get the full output. 

I went through [https://github.com/ronf/asyncssh/issues/241](issue241). But couldn't quiet figure it out. 

I tried the suggestions and samples from the other discussions. I am stuck at a point. My code works fine when the output of the command is limited to a page. 
When the output is large and paginated, I am unable to get the complete output from the device.
Can you please advise

Code snippet - 
`    import asyncio
    import sys
    import time
    import asyncssh
    
    
    async def run_client(host, cmd):
        k_algs = ['ecdh-sha2-nistp521', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp256', 'diffie-hellman-group14-sha1',
                  'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1']
        e_algs = ['aes256-cbc', 'aes128-cbc', '3des-cbc', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr',
                  'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com']
        m_algs = ['hmac-sha1']
        print('in run_client')
        async with asyncssh.connect(host, username=uname, password=pwd, port=22,
                                    known_hosts=None, kex_algs=k_algs, encryption_algs=e_algs, mac_algs=m_algs,
                                    compression_algs=None, ) as conn:
            async with conn.create_process(cmd) as process:
    
                print('after conn')
                print("**************************%s******************************" % cmd)
                process.stdin.write(f'{cmd}\r\n')
                process.stdin.write_eof()
                line = await process.stdout.read()
                print(str(line))
         
    
    async def run_multiple_clients():
        
     
        host = host_ip
        cmd = 'display bgp peer'
        #cmd = 'display ospf interface all'
        await run_client(host, cmd)
    
    
    start = time.time()
    

    asyncio.get_event_loop().run_until_complete(run_multiple_clients())
   
    end = time.time()
    
    print(f'Time taken : {end - start}')
`

With the above code, display bgp peer works fine since its a 2 line output. 
display ospf interface all returns output only until --- More ---

Log - 
` Backup Designated Router: 0.0.0.0
 Timers: Hello 10 , Dead 40 , Poll  120 , Retransmit 5 , Transmit Delay 1 
  ---- More ----
Time taken : 1.447819709777832
# 

`
Thanks in advance

**Comment by ronf** [comment]
Hi Monica,

While you could try to detect the pagination messages and have your AsyncSSH client code send input to request each new page, that would be messy and you'd also then have to deal with removing those prompt from the output you collect. A much simpler solution would be to just disable pagination as the first command you send on each session, so you never get those prompts.

The mechanism to disable pagination is likely to vary from router to router, so you may need to adjust the commands appropriately, but I"m sure you must already be doing that for other commands you are sending, since those would also vary depending on the target.

Doing a quick search, I see that some Cisco routers use the command "terminal length 0" for this. Other seem to use "terminal datadump".  I've also seen mention of "paging disable". On some Juniper routers, it looks like "set cli screen-length 0" might be what you need. Basically, you just need to find the right command and put that before you send the command that generates the output you want.

**Comment by mon-216** [comment]
Hello Ronf,
Thanks for your reply. With your suggestion, I tried finding the paging disable commands for the devices I am working on. I tried the below code - 
` async with asyncssh.connect(host, username=uname, password=pwd, port=22,
                                known_hosts=None, kex_algs=k_algs, encryption_algs=e_algs, mac_algs=m_algs,
                                compression_algs=None, ) as conn:
        async with conn.create_process(cmd) as process:
            print('after conn')
            print("**************************%s******************************" % disable_paging_cmd)
            process.stdin.write(f'{disable_paging_cmd}\r\n')
            print("**************************%s******************************" % cmd)
            process.stdin.write(f'{cmd}\r\n')
            process.stdin.write_eof()
            line = await process.stdout.read()
            print(str(line))`

It doesn't work for me. Can you please tell me where am wrong

**Comment by mon-216** [comment]
By replacing `async with conn.create_process(cmd) as process: ` with `async with conn.create_process('') as process:`, it works fine

**Comment by ronf** [comment]
You are mixing two styles here.

If you pass in `cmd` in the call to `create_process()`, you can't write commands via `stdin.write()`. In that case, the standard input you write will be fed directly to `cmd`, and that's not what you want here. If you want to write commands via `stdin.write()`, you would need to call `create_process()` without passing in `cmd`, which requests that the target system start a shell. You can then pass in multiple commands via `stdin.write()`. If there's any output from the paging disable command, it'll be mixed with the output from the other commands after that, though, so you'll need to take that into account if you try to parse what you get back from `stdout.read()`.

If the target provides a way to specify multiple commands in a single line (like using ";" in a UNIX shell), you may be able to go back to `create_process()` with `cmd` as an argument. You'd just need to include both the paging disable command and the actual command you want to run all in one line.

**Comment by mon-216** [comment]
Hi Ron, Agreed.

I tried without passing any args to the `create_process()`. For some reason, the below code runs only the first time. If I execute the code successively, no output is returned. 

```
async with conn.create_process() as process:
            print('after conn')
            print("**************************%s******************************" % disable_paging_cmd)
            process.stdin.write(f'{disable_paging_cmd}\r\n')
            print("**************************%s******************************" % cmd)
            process.stdin.write(f'{cmd}\r\n')
            print("**************************%s******************************" % exit_command)
            process.stdin.write(f'{exit_command}\r\n')
            process.stdin.write_eof()
            line = await process.stdout.read()
            print(str(line))
```
Unfortunately, target does not support specifying multiple commands in a single line. So I have to specify it one by one.

**Comment by ronf** [comment]
In the case where you are opening a shell, that read() call with block until the server closes the connection. After sending `cmd` to stdin, you'll probably need to do something like `process.stdin.write_eof()` so that the target knows you aren't going to be sending any more commands. That should cause it to close the session when it's done sending output, and that will unblock your call to read().

**Comment by mon-216** [comment]
Do you suggest adding `process.stdin.write_eof()` after cmd? I have `process.stdin.write_eof()` after exit_command. only after write_eof() I am trying read()

**Comment by ronf** [comment]
Ah, sorry - I didn't read you example carefully enough. In theory, if `exit_command` actually causes the server to close the connection, you should be able to use that instead of the `write_eof()`. However, I've seen some target systems not properly accept additional command input while processing a previous command, so there's a chance the exit command may not actually trigger the close. Still, since you have a `write_eof()` after that and before the `read()`, that should be good enough.

If the function only runs correctly the first time, it's possible that this is because the target system won't accept multiple sessions being opened on the same connection. You may need to actually close the connection and open a new one every time for devices which have this limitation, so that you only ever call `create_process()` once per connection.

**Comment by mon-216** [comment]
Not sure if I am understanding it correct. Are you suggesting to use `create_process()` for every command (disable paging and cmd separately) ?

**Comment by ronf** [comment]
No - keep the code above basically the same, but don't reuse "conn". Open a new connection for each call to `create_process()`, and then send the paging disable, command, and exit on the process just like you're doing here.

**Comment by mon-216** [comment]
> No - keep the code above basically the same, but don't reuse "conn". Open a new connection for each call to `create_process()`, and then send the paging disable, command, and exit on the process just like you're doing here.

Sorry. I dont get it :)

**Comment by mon-216** [comment]
I passed only the` exit_command` and removed `write_eof`. It seems to be working now. I will check with all device types I am working on and shall update this ticket. 
 
```
async with conn.create_process() as process:
            print('after conn')
            print("**************************%s******************************" % disable_paging_cmd)
            process.stdin.write(f'{disable_paging_cmd}\r\n')
            print("**************************%s******************************" % cmd)
            process.stdin.write(f'{cmd}\r\n')
            print("**************************%s******************************" % exit_command)
            process.stdin.write(f'{exit_command}\r\n')
            line = await process.stdout.read()
            print(str(line))

            print(process.exit_signal)
```

**Comment by ronf** [comment]
Glad to hear you got it working. With the code you have now, are you ever calling create_process() more than once with the same value of "conn", do you always end up calling asyncssh.connect() and then using the value you get back from that in your call to conn.create_process(), so it's a different "conn" value for every new process you start?

**Comment by mon-216** [comment]
Hi Ron, 
`create_process()` I am calling only once. conn is also single. Pasting below the code for your reference - 

```
async with asyncssh.connect(host, username=uname, password=pwd, port=22,
                                known_hosts=None, kex_algs=k_algs, encryption_algs=e_algs, mac_algs=m_algs,
                                compression_algs=None, ) as conn:
        async with conn.create_process() as process:
            print('after conn')
            print("**************************%s******************************" % disable_paging_cmd)
            process.stdin.write(f'{disable_paging_cmd}\r\n')
            print("**************************%s******************************" % cmd)
            process.stdin.write(f'{cmd}\r\n')
            print("**************************%s******************************" % exit_command)
            process.stdin.write(f'{exit_command}\r\n')
            line = await process.stdout.read()
            print(str(line))

            print(process.exit_signal)

```

**Comment by ronf** [comment]
Ok, sounds good. In the case where you tried to run multiple commands, though, did you start with a new asyncssh.connect() and then create_process() for each new set of commands?

**Comment by mon-216** [comment]
> Ok, sounds good. In the case where you tried to run multiple commands, though, did you start with a new asyncssh.connect() and then create_process() for each new set of commands?

Yes thats right. A new connect and then create_process() for each new set of commands

**Comment by mon-216** [comment]
Closing this issue. As mentioned, paging issue resolved with disable paging commands.
