### ISSUE TITLE
Problem with >10 parallel SSH connections

### ISSUE THREAD

**Issue by seandlg** [ronf/asyncssh#456]
Hello there,

I am using `AsyncSSH` (which has been absolutely great thus far :pray: ) in combination with `FastAPI` to build a performant, `async`-ready `API`. Now I have noticed that the opening of multiple parallel connections can cause a few `SSH` connections to be dropped, and I was wondering if this was expected behavior given my approach or if I misunderstood something about `AsyncSSH`/`asyncio` (which I assume to be the case).

My first assumption was that `.run` might reuse existing connections and open separate channels (which by default most `SSH`-servers only allow 10 of per connection), but from investigating the source code and the access log, it doesn't look like that. Rather, a separate `SSH`-connection is opened for every command - perfect!

I've created a minimal reproducible build [here](https://github.com/seandlg/parallel-asyncssh). By tweaking the [`parallel_tasks` variable](https://github.com/seandlg/parallel-asyncssh/blob/5e354e8afb369dd06f918956f693d2d93c675157/main.py#L26) to `>10` I start noticing the issue..

The error I keep seeing is `asyncssh.misc.ConnectionLost: Connection lost`, the `stacktrace` looks as follows:

```bash
Error trying to connect to server via SSH...
Traceback (most recent call last):
  File "/home/user/Coding/asyncssh-test/main.py", line 8, in executeCommand
    async with asyncssh.connect(
  File "/home/user/.local/share/virtualenvs/asyncssh-test-LAQchyfJ/lib/python3.10/site-packages/asyncssh/misc.py", line 274, in __aenter__
    self._coro_result = await self._coro
  File "/home/user/.local/share/virtualenvs/asyncssh-test-LAQchyfJ/lib/python3.10/site-packages/asyncssh/connection.py", line 7646, in connect
    return await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/home/user/.local/share/virtualenvs/asyncssh-test-LAQchyfJ/lib/python3.10/site-packages/asyncssh/connection.py", line 439, in _connect
    await options.waiter
asyncssh.misc.ConnectionLost: Connection lost
```

Is this an issue with `AsyncSSH` or am I simply doing something wrong here?

**Comment by ronf** [comment]
Hi Sean,

I'm glad to hear that AsyncSSH is working well for you. Assuming you are making more than 10 connections to the same server, I think the problem you are running into is related to the server configuration option "MaxStartups". That limits the number of simultaneous unauthenticated connections the server will allow. By default, once you get over 10 such connections, a typical OpenSSH server will start randomly dropping some of the connections, and eventually drop all of them if you continue to pile on more load. This only applies while authentication is happening, so you can have more total open connections than that, but only if you pace things to avoid too many simultaneous authentications.

Regarding multiple connections vs. multiple sessions, AsyncSSH supports both. If you call the run() method multiple times on the same "conn" object, it'll open a new session on that existing connections for each command. That's much more efficient than opening a new connection every time, but as you said the default for maximum number of simultaneous sessions per connection is 10. This can be changed on the server via the configuration option "MaxSessions".

You open multiple independent connections if you call asyncssh.connect() multiple times, getting a new "conn" object for each one. This lets you get around the MaxSessions limit, but then you have to be careful about the above issue of not triggering too many authentications at once.

You can also do a mixture of the two approaches, opening multiple connections at once and then opening multiple sessions on each of those connections. Using something like a semaphore, you can also limit how many simultaneous sessions or connections you have at once.

**Comment by seandlg** [comment]
Hello Ron,

thanks a lot for getting back to me so quickly and with such a detailed and helpful answer! Indeed I could mitigate the issue by tweaking the `MaxStartups` variable of the `sshd` config (`/etc/ssh/sshd_config`), which by default seems to be set as `#MaxStartups 10:30:100`. Now it appears to me that adjusting this value "up" is a bad idea for systems that are exposed to the internet (`DDOS` comes to mind), but for any systems inside private networks, tweaking this value seems fine. The respective documentation is quoted below:

[`MaxStartups`](https://man.openbsd.org/sshd_config#MaxStartups):

> Specifies the maximum number of concurrent unauthenticated connections to the SSH daemon. Additional connections will be dropped until authentication succeeds or the `LoginGraceTime` expires for a connection. The default is 10:30:100.
Alternatively, random early drop can be enabled by specifying the three colon separated values start:rate:full (e.g. "10:30:60"). `sshd` will refuse connection attempts with a probability of rate/100 (30%) if there are currently start (10) unauthenticated connections. The probability increases linearly and all connection attempts are refused if the number of unauthenticated connections reaches full (60).

---

And for completeness sake the documentation on `MaxSessions`:

[`MaxSessions`](https://man.openbsd.org/sshd_config#MaxSessions):

> Specifies the maximum number of open shell, login or subsystem (e.g. sftp) sessions permitted per network connection. Multiple sessions may be established by clients that support connection multiplexing. Setting `MaxSessions` to 1 will effectively disable session multiplexing, whereas setting it to 0 will prevent all shell, login and subsystem sessions while still permitting forwarding. The default is 10.

Now, given the (hypothetical) requirement that I'd like to allow for up to ~1000 (number chosen rather arbitrarily) concurrent `shells` into a server, I'd like to split these via 100 connections that multiplex 10 sessions each. Instead of keeping a pool of 100 connections, I'd open and close connections as "`run` requests" against the `API` come and go. Therefore, I'd keep track of open connections inside `executeCommand` and only open a new connection once I max out the sessions of my connections. Does this sound like a sensible approach to you?

Again, thanks a lot for your support!

**Comment by ronf** [comment]
Yes - this makes sense. I imagine you'd want a per-server pool of already-open connection objects for this, and you might want to split it into two lists, one of which is connections which have 10 sessions already open and another with connections with less than 10 sessions. As sessions are started/stopped, you'd move the corresponding connection between the two lists whenever it crossed that threshold.

When it came time to open a new session, you'd see if the list of connections with less than 10 sessions was empty, and if so start a new connection and add it to that list. When the last session closed on a connection, you could close and remove it from the list, perhaps after some timeout if you wanted to try and reuse connections as often as possible. As an optimization, you could keep the list in sorted order by number of sessions open, preferring to reuse connections with the most sessions open (but still less than 10), allowing you to shrink the number of simultaneous open connections as much as possible as sessions close.

To deal with the other issue around MaxStartups, you can use an asyncio semaphore (one per server). Basically, for each server, create a semaphore with a count of 10. Then, before calling asyncssh.connect() to open a new connection to a server, grab that semaphore and hold it until the connect returns. The easiest way to do this is to use the semaphore as an async context manager while you are calling connect(). This will prevent more than 10 connections to that server from being opened as once. Once connect() returns (and before opening any sessions), you'd release the semaphore, as that would mean authentication has completed. This will ensure you don't start new connections too quickly if you get a flood of requests to a particular server.

**Comment by ronf** [comment]
Thinking about this a bit more, you might want to set the semaphore count somewhat lower than the actual limit on the server, just in case you have other SSH clients also connecting to that server at the same time as the logic here. You should still get reasonable results even if you set it to something like 5 or 7, I think, and that would reduce the risk of hitting the limit when you had multiple independent clients hitting a given server.

The other option would be to try and catch the ConnectionLost error and retry a few times, but you'd probably still want the semaphore in that case to minimize the chance of needing to retry.

**Comment by seandlg** [comment]
Hi Ronald,

Thanks a million for your feedback and time! This sounds like a really promising approach and I will give it a shot :-) I think I will start with using semaphores to prevent the `MaxStartups`-issue and later move towards keeping a connection- and session-pool as you suggested.

Best,
Sean

**Comment by ronf** [comment]
Happy to help - that sounds like a good approach. If you have any further questions, feel free to ask.
