### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by egorsmkv** [ronf/asyncssh#46]
Hello.

I use Windows and got this error:

```
...
    import grp
ImportError: No module named 'grp'
```

**Comment by nchammas** [comment]
I think this issue is probably better titled "Add Windows support". I don't think AsyncSSH is meant to work on Windows, at least not yet.

**Comment by ronf** [comment]
For the most part, AsyncSSH should be portable to Windows, but I had a feeling when I added SFTP support that I may have used a few things that wouldn't work there.

I took a closer look and the use of the 'grp' and 'pwd' modules were an issue there, as well as relying on the HOME environment variable to get the user's home directory in the connection module. I've made some simple tweaks to the code to work around these problems, though, and checked the results into the "develop" branch. The result is that I was able to get my simple_client.py example working on Python 3.4 on Windows!

Some things still won't work here, such as the ssh-agent support and UNIX domain socket forwarding. Also, I haven't tried to see if I can get libnacl working, so some of the newer ciphers and key types might not work. However, DSA, RSA, and ECDSA keys seem ok.

If anyone wants to play around with this further, I'd be happy to accept reports of any problems you find.

**Comment by ronf** [comment]
I did a bit more testing on this tonight and confirmed that AsyncSSH can properly use both libnacl/libsodium and py-bcrypt when they are installed, with no additional changes required. This means all private key formats and ciphers supported by AsyncSSH should work on Windows.

**Comment by theonewolf** [comment]
@ronf this really anticipated my current need.  Huge thanks for looking into this.

I had just bypassed `pwd` and `grp`.  I actually added a `HOME` variable to my Windows setup.

I am trying to do port forwarding and might have run into an issue.

I'll let you know, after I install the develop branch.

**Comment by theonewolf** [comment]
Can confirm, TCP forwarding appears to be working in the devel branch.

I'm going to test this out with very long-lived connections, using varying bandwidth.

Are you able to run the test suite on Windows?  If you have good coverage, it would be awesome to get a release including this new Windows support :grin:

**Comment by ronf** [comment]
I'm getting there on code coverage -- I've got all but 3 modules at 100% coverage now. Channel is almost there in my local repo (up to 97%) and that leaves only connection (currently at 79%) and sftp (not started yet, so only at 28%).

Unfortunately, the tests rely on things like command-line OpenSSL and OpenSSH to be installed, so they won't run on Windows at the moment. I know there is a Windows OpenSSH port these days, but I wasn't able to get it to work when I tried it. I'm also relying on some UNIX shell semantics that would have to be reworked.

While I'm happy to try and fix any issues found related to Windows support, it'll be a while before I'm able to spend any time getting the tests running there. I'd like to finish getting coverage on the UNIX version of the tests done first.

That said, I will try and get a release out soon with the Windows fixes made so far (and other recent bug fixes).

**Comment by theonewolf** [comment]
That makes sense.

I've gotten pretty far using Cygwin.  Do you think that would cover most of your bases?

I can run most of the stuff you listed without too much effort (`openssl` and `ssh`).

Do you need OpenSSH server locally for the tests to run?  I don't think I've tried a server on Windows yet.

However, you might also want everything to pass independently of Cygwin.

Do you have instructions for running the tests?  I don't mind trying them out on Windows.  I'll try and get pull requests to fix them up if I can.

**Comment by ronf** [comment]
At the moment, the tests depend on the following command line programs:

* ssh (though currently only to do a version check)
* ssh-keygen
* ssh-agent
* ssh-add
* openssl
* mkdir
* chmod
* cp
* mv
* rm
* cat
* printf (ugly workaround for the fact that "echo -n" is not portable)

They also depend on shell input/output redirection in some cases.

Some of the shell calls could easily be converted to native Python calls, but it was more readable to leave them as shell commands when they were setting up state needed by the other ssh & openssl commands listed there.

I don't currently rely on running sshd, as I'm using AsyncSSH's own SSH server to do some of the testing of the AsyncSSH client, but at some point I might want to go back and add some crossover testing with OpenSSH as a client to an AsyncSSH server and vice-versa. I do that with the public key tests, using a combination of OpenSSL and ssh-keygen to import/export keys and certificates in various formats and make sure that AsyncSSH can both read and write compatible files.

There are a few different ways to run the tests. One is to run "setup.py test" in the source directory. Another is to run "python -m unittest" or "coverage run -m unittest" to run the unit tests and calculate code coverage.
