### ISSUE TITLE
cryptography + asyncssh versioning issue.

### ISSUE THREAD

**Issue by sebby97** [ronf/asyncssh#465]
I believe an incorrect change was made here asyncssh/crypto/chacha.py where a "backend" was removed and no longer passed into Cypher. The commit hash that includes the change is https://github.com/ronf/asyncssh/commit/88dcdac875e186bcd47b9c15f66b2935317033c6. The commit message mentions adding in TypeDefs so removing the arg was likely a mistake with the current minimum recommended version of cryptography==2.8. The change breaks the code path, however it is clear that future cryptograph versions intended to deprecate the backend arg, so the thing to do might be to unpin/update the minimum cryptography version.

**Comment by ronf** [comment]
Thanks for catching this...

At this point, I think it probably makes more sense to move up the minimum version of cryptography than it would to add back an explicit backend argument. According to another report I got today (#467), the backend would need to be added in at least two places, and passing in backend has actually been deprecated as of cryptography version 36.

I think bumping the minimum version of cryptography in AsyncSSH's setup.py to  3.1 should resolve this issue. The backend will still be needed in chacha.py and ed.py to do checks on which ciphers are supported by the version of OpenSSL in use, but it should not be necessary at that point to pass in backend as an explicit argument to any cryptography functions.

**Comment by ronf** [comment]
The change to increase the minimum version of cryptography to 3.1 is now in the "develop" branch as commit e0da30a and will be included in the next release.

**Comment by ronf** [comment]
The cryptography dependency has been updated in the AsyncSSH 2.10.1 release.
