### ISSUE TITLE
Windows - missing 1 required positional argument: 'backend'

### ISSUE THREAD

**Issue by JavaScriptDude** [ronf/asyncssh#467]
When running a simple test on  `Windows Server 2019`, `asyncssh.connect`, is failing with `__init__() missing 1 required positional argument: 'backend'`.

Environment:
- OS - Windows Server 2019 Standard
- Python: v3.8.2
- asyncssh: v2.10.0
- cryptography: 2.8

Code is failing in `/crypto/chacha.py` in `def chacha20()` while calling `return Cipher(ChaCha20(...))`. Its `Cipher` (cryptography.hazmat.primitives.ciphers) that requires a `backend` parameter.

I was able to patch this by changing the line in `chacha.py` from:

```python3
        return Cipher(ChaCha20(key, (_CTR_1 if ctr else _CTR_0) + nonce),
                      mode=None).encryptor().update(data)
```
... to: 
```python3
        return Cipher(ChaCha20(key, (_CTR_1 if ctr else _CTR_0) + nonce),
                      mode=None, backend=backend).encryptor().update(data)
```

Does this fix seem correct?

I'll gladly add a PR if it looks ok.

**Comment by JavaScriptDude** [comment]
Confirming that `Cipher` class at [v2.8](https://github.com/pyca/cryptography/blob/25494f96d57b8995ee2fde099146b1192582ee1b/src/cryptography/hazmat/primitives/ciphers/base.py#L96), the `backend` parameter was required. It was later updated to be optional and ignored.

**Comment by JavaScriptDude** [comment]
Here is the dependencies for asyncssh `2.10.0` on windows:

```
>>> from importlib.metadata import requires
>>> requires('asyncssh')
['cryptography (>=2.8)', 
'typing-extensions (>=3.6)', 
"bcrypt (>=3.1.3); extra == 'bcrypt'", "fido2 (>=0.9.2); extra == 'fido2'", "gssapi (>=1.2.0); extra == 'gssapi'", "libnacl
(>=1.4.2); extra == 'libnacl'", "python-pkcs11 (>=0.7.0); extra == 'pkcs11'", "pyOpenSSL (>=17.0.0); extra == 'pyOpenSSL'", "pywin32 (>=227); extra == 'pywin32'"]
```

**Comment by JavaScriptDude** [comment]
Was playing around a bit more with encryption algo's and found another of the same issue.

When using `encryption_algs` of `aes*-ctl`  (eg. `aes128-ctr`), `cipher.py` fails in the same way.

Adding `from cryptography.hazmat.backends.openssl import backend` and `backend=backend`, fixes this as well.

**Comment by ronf** [comment]
Thanks for reporting this! As it turns out, I got another similar report just a few hours before yours (#465).

I'm looking at increasing the minimum required version of cryptography from 2.8 to 3.1 to address this problem. Can you confirm that things work without adding the backend argument if you move to cryptography 3.1?

**Comment by JavaScriptDude** [comment]
Sure, Ill check in a few minutes...

**Comment by JavaScriptDude** [comment]
Confirmed. cryptography `3.1` as a min version will works fine on my Windows server instance. My development desktop  (Ubuntu 20.04.4) was already at a higher rev because of pyOpenSSL dependencies at `3.2`.

**Comment by ronf** [comment]
Thanks for the confirmation!

This change is now in the "develop" branch as commit e0da30a and will be included in the next release.

**Comment by JavaScriptDude** [comment]
Thanks for the quick update!

**Comment by JavaScriptDude** [comment]
FYI - For the future, looks like cryptography `3.3.2` is the last version that will install in `Cygwin` due to rust build dependency.

**Comment by ronf** [comment]
Thanks for the heads-up. Unfortunately, there's not much I can do. I can continue to support older versions for a while, but eventually some security patch or needed feature may force me to move to a newer version of that.

Perhaps someone will figure out how to get rust running there, or how to cross-compile a binary for Cygwin, since rust is only needed to do the build and not afterward to actually use the package.

**Comment by JavaScriptDude** [comment]
Understood and agree. Security is #1 with asyncssh; especially since this library is security based. Hopefully, nothing big shows up any time soon. Anyhow, I don't have any needs at this time to run on Cygwin. It runs just fine natively in Windohs.

**Comment by ronf** [comment]
The cryptography dependency has been updated in the AsyncSSH 2.10.1 release.
