### ISSUE TITLE
Proxy ssh session without client configured jump setting

### ISSUE THREAD

**Issue by jabbera** [ronf/asyncssh#468]
I'd like to use asyncssh as an ssh proxy for a specific host without using the jump setting. IE: client connects to my asyncssh server, asyncssh makes a connection to a different remote host using client api, then traffic from original client is passed through to server and vice versa. Is there any easy way to do this?

**Comment by ronf** [comment]
As long as you have all the authentication information you need to open the upstream connection from this "SSH proxy", I think this should be straightforward. You can use the I/O redirection feature (https://asyncssh.readthedocs.io/en/latest/#i-o-redirection) to "plug" stdin/stdout/stderr from the SSHServerProcess that accepts the connection from the client into the SSHClientProcess you open to connect to the remote host.

You'd probably want to carry certain other parameters through (possibly with modifications), like the terminal type, terminal size, terminal modes, and environment. You might also want to change the user name used when opening the upstream connection.

It could get a bit more complicated if you want to allow multiple SSH sessions on a single connection from a client to share a single SSH connection to a server, each with its own session, or even potentially multiple SSH sessions from different clients to all share a single connection to a server, if they are all connecting as the same user to the same server. However, you could start with just one session per connection and work your way up to that, if you need it.

**Comment by ronf** [comment]
Here's an example you can start from:

```python
import asyncio, asyncssh, logging, sys

async def handle_client(process):
    process.stdout.write('Welcome to my SSH proxy, %s!\r\n\r\n' %
                         process.get_extra_info('username'))

    async with asyncssh.connect('remote_host') as conn:
        upstream_process = await conn.create_process(
            env=process.env, term_type=process.term_type,
            term_size=process.term_size, term_modes=process.term_modes,
            stdin=process.stdin, stdout=process.stdout,
            stderr=process.stderr)

        await upstream_process.wait_closed()

    process.close()

async def start_server():
    await asyncssh.listen('', 8022, server_host_keys=['ssh_host_key'],
                          authorized_client_keys='ssh_user_ca',
                          line_editor=False, process_factory=handle_client)

loop = asyncio.get_event_loop()

try:
    loop.run_until_complete(start_server())
except (OSError, asyncssh.Error) as exc:
    sys.exit('Error starting server: ' + str(exc))

loop.run_forever()
```
You'll need to decide how to fill in the `'remote_host'` argument there, and potentially add user and/or port information to that. The original client username is available if you want to use that (see the "Welcome" message in the example), and you could potentially also get the original client IP & port via `get_extra_info()` if you needed that.

In this example, it just opens up an interactive shell on the remote system, but you could also request it to run other commands if you like, while still providing interactive input after the command is started.

As soon as the upstream process exits, the downstream process is closed. One thing I didn't do here is to pass the return code from the upstream process through to the original client. That's not very interesting in the case of launching an interactive shell, but it could be useful if you wanted to run other commands.

Also, this code ignores any command or subsystem the client requests of the proxy right now, but if you wanted to preserve that, it would be straightforward to query `process` for `command` and `subsystem` and pass them through, similar to the other arguments in this example.

**Comment by jabbera** [comment]
Thank you for this. After many more hours of arguing and flakiness I convinced the powers above to create a shortcut on everyone's desktop.
