### ISSUE TITLE
SSH connection failed: Permission denied

### ISSUE THREAD

**Issue by damrkul** [ronf/asyncssh#477]
I am using a git-cloned repo to test out this repository.  When trying to run a simple example of SSH I get the following output:

```
python3 test.py
SSH connection failed: Permission denied
```

```
python3 --version
Python 3.9.6
```
```
pip3 show cryptography

Name: cryptography
Version: 3.3.1
```

When using the regular-standard **Paramiko module , I am to connect and get the data**.

**Comment by ronf** [comment]
Can you share your test code here? What kind of authentication are you attempting to use?

**Comment by damrkul** [comment]
```
cat test.py


import asyncio, asyncssh, sys

async def run_client():

    async with asyncssh.connect('localhost') as conn:
        result = await conn.run('hostname', username='jrankin', password='XXXX')
        print(result.stdout, end='')

try:
    asyncio.get_event_loop().run_until_complete(run_client())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```

**Comment by ronf** [comment]
Thanks. I don't see anything obvious wrong there. Do you have "localhost" in your ~/.ssh/known_hosts file? If not, AsyncSSH will fail the connection, but that should be with a different error. This error looks like you are providing the wrong username or password.

The next step would probably be to turn on debug logging. by adding lines such as:

```python
    logging.basicConfig()
    asyncssh.set_log_level('DEBUG')
    asyncssh.set_debug_level(2)
```

You could also look for log output from sshd, to see if it is reporting any failures.

**Comment by damrkul** [comment]
So  I made a SSH Key and added it to authorized hosts ... and i was able to run it and get my output..

So seems like USR/PW is not being sent .. (ill need to have usr/pw supplied and wont be able to use sshkeys)

**Comment by ronf** [comment]
Ah - I looked more closely at this and realized you are passing the username/password in the conn.run() call. Authentication happens at the connection level, so you'll need to pass those arguments in the connect(), not the run(). That explains why it was able to work for key-based auth, as it didn't need any additional arguments to find your key. The username would be required in that case, but it'll default to the user running the client.

**Comment by damrkul** [comment]
Gotcha.  
I moved usr/pw to the connection function.  

Everything works.

My apologies for wasting your time.

**Comment by damrkul** [comment]
Sorry while I have you here..

[root@gauss-fmn2 jrankin]# python3 test.py
SSH connection failed: Host key is not trusted

How can I ignore host keys identification?

**Comment by ronf** [comment]
I saw a question in e-mail about skipping the known_hosts check, which I'm guessing you figured out and then deleted the associated post, but I'll go and confirm here anyway...

Setting `known_hosts` to `None` will disable this check, but you should be aware that this can leave you open to man-in-the-middle attacks on the SSH connections you open.
