### ISSUE TITLE
IOS XR terminal resize event

### ISSUE THREAD

**Issue by adam-pawluczuk** [ronf/asyncssh#479]
Hi @ronf !

I'm not really sure if this is an `asyncssh` bug (or a feature), or a matter of something else.

Normally we support different Cisco devices (ASA / XE / XR and so on).

For all the devices when establishing a session we always disable pager (`terminal length 0` & `terminal width 0`).

Also after the connection is established we send terminal size change request (`asyncssh.channel.SSHClientChannel.change_terminal_size`).

For all the device types it seems to be working as expected.

Though for XR it is different. E.g. if I check terminal size (`show terminal`) and then resize the terminal window, we use asyncssh to send the `window-change` request which in the end also affects terminal size. Then I check `show terminal` again, and I don't have length 0 and width 0, but actual terminal sizes. If I manually disable pager again, resize again then still pager will be enabled again.

This doesn't happen for devices different than XR (pager stays disabled after terminal resize even the terminal resize requests are being sent).

Do you have any kind of a clue why it is different for XR?

Best regards,
Adam Pawluczuk

**Comment by ronf** [comment]
Yeah - it sounds like the XR is updating its width/height to match the new window size even if you had manually turned off paging by setting length/width to zero.

Would it be possible to do the terminal size change you want before you send the terminal length/width commands? That might work around the differences between the devices.

**Comment by adam-pawluczuk** [comment]
Thanks for the tip!

Yes, this was something we also considered.
