### ISSUE TITLE
Connection lost while "public_key_auth" option is not specified

### ISSUE THREAD

**Issue by AntonMuravlev** [ronf/asyncssh#505]
Hello!

I've noticed unusual behavior with old Cisco devices. If we have  explicit"public_key_auth=False" option connection will established succesfully

Example(log file - public_key_auth_False.log)
[public_key_auth_False.log](https://github.com/ronf/asyncssh/files/9281766/public_key_auth_False.log)

```python
import asyncio
import asyncssh
import logging

logging.basicConfig(level="DEBUG")
asyncssh.set_debug_level(2)


async def test_con(host, username, password):
    ssh1 = await asyncssh.connect(
        host=host,
        username=username,
        password=password,
        known_hosts=None,
        public_key_auth=False,
    )


if name == "main":
    asyncio.run(test_con("192.168.122.101", "cisco", "cisco"))
```

But if we don't have explicit "public_key_auth" option we will get connection lost after several attempts of public key auths. I don't see "keyboard-interactive auth" attemtps.
Code the same
Log file is attached - public_key_auth_not_specified.log
[public_key_auth_not_specified.log](https://github.com/ronf/asyncssh/files/9281767/public_key_auth_not_specified.log)

```python
async def test_con(host, username, password):
    ssh1 = await asyncssh.connect(
        host=host,
        username=username,
        password=password,
        known_hosts=None,
    )
```

I think it may be related to old Cisco SW verision, but will be great if asyncssh can thread this behavior

**Comment by ronf** [comment]
You're most likely running into the server's limit on the number of failed auth attempts which are allowed on a connection. If you use all of these up on public keys which the server doesn't accept, you'll never get to the username/password auth which could actually work.

There are no keyboard-interactive auth attempts showing up in the logs you provided. That method is being shown as one of the remaining auth methods, but if you look at the "Trying" log lines, they are all "Trying public key auth" with various default keys.

The best option here is to not allow AsyncSSH to use the default keys if they aren't going to work. This can be accomplished by setting `client_keys=None`, or by limiting `client_keys` to only keys which you think the server might accept. That way, if those keys don't work, there will still be auth attempts left over to fall back to something like username/password.

Limiting auth attempts like this is standard practice for all SSH servers. If you have a bunch of public keys in your ".ssh" directory and an SSH server you are trying to connect to doesn't accept any of them, you'll likely see the same behavior as you're seeing here. This also isn't limited to AsyncSSH. You should see the same behavior if you try to connect to such a server with OpenSSH.

**Comment by AntonMuravlev** [comment]
Got it. Thank you for the clear explanation!
