### ISSUE TITLE
ProxyCommand %h not replaced

### ISSUE THREAD

**Issue by FloLaco** [ronf/asyncssh#520]
I'm using another library (suzieq) which use asyncssh library.
I'm providing ssh config file with ProxyCommand option for trying to multiplex ssh session with netcat. 
It's working with openssh client, but it seems that asyncssh does not replace the token `%h` from the `ProxyCommand` option :

```
[WORKER 0]: 2022-10-27 13:03:59,303 - asyncssh - INFO - [conn=252] Connected to SSH server at 10.38.119.40, port 22
[WORKER 0]: 2022-10-27 13:03:59,303 - asyncssh - INFO - [conn=252]   Proxy command: nc -X 5 -x 127.0.0.1:2226 '' 22
[...]
[WORKER 0]: 2022-10-27 13:04:14,275 - asyncssh - INFO - [conn=252] Aborting connection
[...]
[WORKER 0]: 2022-10-27 13:04:14,275 - asyncssh - INFO - [conn=252] Connection closed
```

As you can see, we see `'' ` instead of `10.38.119.40`.

Here's my ssh config file : 
```
host  jumpserver
   IdentityFile   /home/suzieq/parquet/ssh_cred_conf/id_rsa
   IdentitiesOnly   yes
   user   xxxxxx
   hostname   x.x.x.x
   Protocol  2
   Port  22
   StrictHostKeyChecking   no
   DynamicForward 127.0.0.1:2226

host * !jumpserver
   Protocol  2
   StrictHostKeyChecking  no
   ProxyCommand nc -X 5 -x 127.0.0.1:2226 %h %p
   KexAlgorithms  +diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1

```

Just for information, I'm starting the ssh connection to jumpserver before running Python with this command : `ssh jumpserver -F /home/suzieq/parquet/ssh_cred_conf/config -N &`

**Comment by ronf** [comment]
It looks like the '%h' substitution during config file parsing isn't getting the hostname, but in a quick test I was not able to reproduce that here.

Can you show the call you are making to AsyncSSH to make the connection? Are you passing in that IP of 10.38.119.40 directly as the host to connect to, or is there something more involved going on there?

**Comment by FloLaco** [comment]
`suzieq` is passing the IP directly : 
```
                        self._conn = await asyncssh.connect(
                            self.address,
                            username=self.username,
                            port=self.port,
                            options=options)
```

**Comment by ronf** [comment]
I set up a configuration here with a jump server connection using DynamicForward and a ProxyCommand matching what you have here, but I'm still not able to reproduce the problem. The substituted hostname properly shows up in the debug output, and the proper host is contacted by the jump server.

I'm not sure what to try next.

**Comment by ronf** [comment]
I'm not sure if it's an option for you to use ProxyJump instead of ProxyCommand, letting AsyncSSH open the connection to the jump server instead of running it yourself in the background and using SOCKS to connect through it, but AsyncSSH does support that if you wanted to try it. It can be done either via ProxyJump in the config file or by passing the jump host info as the "tunnel" argument on an asyncssh.connect(), either referencing a previously opened SSHClientConnection or as a string containing a hostname and optional port of the jump server.

**Comment by FloLaco** [comment]
I cannot use Jump Server because I'm using this option to multiplex session, which is not supported by asyncssh. I'm trying to find workaround :)
It works well manually, but not with `asyncssh` with `suzieq`.

I can try to add more debug to asyncssh (or suzieq if needed).
Please let me know which debug I can add

**Comment by FloLaco** [comment]
Found out that `host` argument is empty here : https://github.com/ronf/asyncssh/blob/8665c5f35a834f9ed86b26941f280bff2f0b5ef2/asyncssh/config.py#L424

That's why substitution does not work

**Comment by ronf** [comment]
The line you identified in the SSHClientConfig constructor is called from the load() class method of SSHConfig, which gets the value from the prepare() method in SSHClientConfigOptions, and that gets the value from the asyncssh.connect() call (among other calls). So, if a "host" argument is being passed into the call to connect(), it should end up being filled into the a config object when connect() creates the "new_options" object. Based on the code you provided above, the host argument to connect() should be self.address in suzieq.

Can you confirm self.address is being passed into connect(), and that it has a proper value? Assuming it is, can you see what this value ends up being in SSHClientConnectionOptions.prepare() and SSHClientConfig.load()? This path is working correctly for me, but somehow in your environment it seems like the host value is getting lost somewhere along the way.

**Comment by FloLaco** [comment]
I put some logger message on `suzieq`and `asyncssh` : 

`asyncssh` : 
```
    loop = asyncio.get_event_loop()

    logger.info("FLA connect BEGIN %s", host)
    new_options = cast(SSHClientConnectionOptions, await _run_in_executor(
        loop, SSHClientConnectionOptions, options, config=config,
        host=host, port=port, tunnel=tunnel, family=family,
        local_addr=local_addr, **kwargs))
```

`suzieq` : 
```
                        self.logger.info(
                            f"FLAFLAFLAFLA {self.address}:{self.port} at "
                            f"{time.time()}")
                        self._conn = await asyncssh.connect(
                            self.address,
                            username=self.username,
                            port=self.port,
                            options=options)
```

Here's the output log : 
```
[...]
[WORKER 0]: 2022-11-04 16:28:58,736 - suzieq.poller.worker.nodes.node - INFO - FLAFLAFLAFLA 10.34.87.5:22 at 1667579338.7368286
[WORKER 0]: 2022-11-04 16:28:58,736 - asyncssh - INFO - FLA connect BEGIN 10.34.87.5
[...]
```

So yes the self.adress is okay. 

But the problem is in `SSHConfig.load()`. `config` returned is generated by `config = cls(last_config, reload, *args)`, which is the call of `SSHClientConfig.__init__()` which itself call `super().__init__(last_config, reload)` --> `SSHConfig.__init__()`. As `last_options` is defined `self._options` use `last_config`.

**Comment by ronf** [comment]
If you specify "config" explicitly as an argument when constructing an SSHClientConnectionOptions object, I believe that causes the config file parsing to happen at the time of that call. In this case, the "host" argument is not being specified until later, but by then the substitutions done when reading the config file have already happened.

If you want this to work, I think you are going to need to defer passing in the "config" option until the connect() call if you want the host substitution to work. Alternately, the host is know at the point where suzieq's init_ssh_options() is called, it may be sufficient to pass in the "host" argument within that.

The intent behind this behavior is to allow you to pay the cost of parsing the config file and any other operations related to constructing the SSHClientConnectionOptions only once, and any future options are built up incrementally from that. You'd only parse the config file again if the "config" argument is passed in again.
