### ISSUE TITLE
how to use sftp client create stream download task

### ISSUE THREAD

**Issue by Toadally-Awesome** [ronf/asyncssh#523]

**Comment by Toadally-Awesome** [comment]
I want realize a func of breakpoint resume, but I not found stream func in asyncssh

**Comment by Toadally-Awesome** [comment]
I found the stream function in SFTPClientFile, I feel losed my eyes

**Comment by ronf** [comment]
I'm not sure what you mean by "stream func".

The SFTPClientFile class is what gets returned when you do an sftp.open() of a remote file over SFTP. It presents an API which is similar to what you get on a local file, with calls like read() and write(), but with all the methods being async calls. It also has some enhancements for supporting multiple reads or writes running in parallel to improve performance.

I'm not sure offhand how well the Python debugger can handle async functions. That's not something I've ever attempted.
