### ISSUE TITLE
SFTPServer.format_longname use platform dependent time format directive %e

### ISSUE THREAD

**Issue by asidonus** [ronf/asyncssh#53]
time.strftime directive %e is not available on Windows so connected SFTP client receive error "Uncaught exception: Invalid format string" during reading remote directory.

Can it be replaced by %d?

**Comment by ronf** [comment]
I've just checked in a change to the 'develop' branch that should address this. The code attempts to use %e first, but if that triggers an error it falls back to %d.

**Comment by ronf** [comment]
The fix for this is now released as part of AsyncSSH 1.5.4.
