### ISSUE TITLE
If asyncssh channel has file descriptor?

### ISSUE THREAD

**Issue by CGQhaha** [ronf/asyncssh#535]
If I open a channel, is there any way to get the file descriptor of this channel to asynchronously trigger read and write operations on it? 

A example like this:

```python
import selectors

def handle_events(_events):
    for sock in [key.fileobj for key, _ in _events]:
        print(sock.recv())

if __name__ == "__main__":
    selector = selectors.DefaultSelector()
    data = ""
    selector.register(channel.fileobj, selectors.EVENT_READ)
    while True:
        events = selector.select(timeout=1)
        if events:
            handle_events(events)
```

Thanks in advance

**Comment by ronf** [comment]
What you're describing isn't really possible, as AsyncSSH channels don't have file descriptors at the OS level. One of the key advantages to AsyncSSH is that you only need a single file descriptor per SSH connection, no matter how many channels you open on that connection. Asyncio manages the event loop, automatically running code in AsyncSSH whenever there are new bytes available at the connection level, and AsyncSSH parses those bytes. In the case where an SSH message indicates there are new bytes available on a channel, AsyncSSH will call the appropriate callback associated with the channel's session to process those bytes, or wake up whatever asyncio task was asking to read bytes from that channel.

If you want to be able to read from multiple channels in parallel, you can either create an asyncio task for each channel and await on read() of the associated channel in each of those tasks or you can use a lower-level API where you define your own session subclass and implement the data_received() method, and AsyncSSH will call that method whenever new data bytes arrive on the channel.

If you go with the task approach, you can also use something like asyncio.gather() to wait for all of the tasks to complete. See https://asyncssh.readthedocs.io/en/latest/#running-multiple-clients for one example of this. This just shows using run(), which takes care of all the I/O for you, but to see an example on doing interactive I/O on a single channel, check out https://asyncssh.readthedocs.io/en/latest/#interactive-input. You can combine these two examples to create multiple tasks doing I/O on different channels in parallel, either on the same connection or on multiple connections.

For an example of using callbacks, see https://asyncssh.readthedocs.io/en/latest/#callback-example.

As for write operations, the write calls themselves will never block, so you can output as much as you like and asyncio will take care of writing data when space is available. However, if you want to limit the amount of data which is buffered, you can periodically await on drain() to block until the buffer is mostly written, and you can set high & low water marks on how much buffering to allow.
