### ISSUE TITLE
Use with Plain FTP Servers

### ISSUE THREAD

**Issue by AyrtonB** [ronf/asyncssh#536]
Hi, thanks for making such an awesome library.

I'm using `asyncssh` for a number of SFTP servers I interface with, I was wondering whether it's also possible to use the library for connecting to plain FTP server. I have tried with an existing one but had no luck, any advice would be much appreciated!

**Comment by ronf** [comment]
Sorry - despite the similar names, FTP and SFTP have nothing in common protocol-wise. The secure version of FTP is "FTPS", which is basically the original FTP protocol carried inside SSL/TLS. Having a single library which was capable of supporting both FTP and FTPS would be quite doable, similar to the effort to build a library that handled HTTP and HTTPS. However, SFTP more closely resembles a remote filesystem protocol like NFS or CIFS, carried inside SSH. The "file transfer" parts of SFTP are actually all implemented in the client.
