### ISSUE TITLE
SSHReader.at_eof() doesn't work the way I want it to

### ISSUE THREAD

**Issue by JKearnsl** [ronf/asyncssh#544]
Hello, why is 'self._stdout.at_eof()' not working as I need? After executing the command and getting a response from the server, I'd like to terminate the generator, but it's still waiting for data because 'self._stdout.at_eof()' is always 'False' for me.

```python
import asyncio, asyncssh, sys
from typing import Optional, AsyncGenerator, Any


class SSHTerminal:

    def __init__(
            self,
            host: str,
            port: int,
            *,
            username: str,
            password: str = None,
    ):
        self._host = host
        self._port = port
        self._username = username
        self._password = password

        self._connection: Optional[asyncssh.SSHClientConnection] = None

    async def connect(self) -> 'SSHTerminal':
        self._connection = await asyncssh.connect(
            self._host,
            self._port,
            username=self._username,
            password=self._password,
        )
        return self

    async def disconnect(self) -> None:
        self._connection.close()

    def execute(self, command: str) -> 'SSHCommandSession':
        # todo: connection check
        return SSHCommandSession(command, self._connection)


class SSHCommandSession:
    _stdin: asyncssh.SSHWriter
    _stdout: asyncssh.SSHReader
    _stderr: asyncssh.SSHReader

    def __init__(self, command: str, connection: asyncssh.SSHClientConnection):
        self._command = command
        self._connection = connection

    async def receive(self) -> AsyncGenerator[str | bytes, Any]:
        while not self._stdout.at_eof():
            yield await self._stdout.read(1024)

    async def __aenter__(self):
        self._stdin, self._stdout, self._stderr = await self._connection.open_session()
        self._stdin.write(self._command + '\n')
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        self._stdin.close()


async def main():
    term = await SSHTerminal('192.168.x.xx', 22, username="some", password="some").connect()
    async with term.execute("ls") as command_session:
        async for data in command_session.receive():
            print(data, end='')
            # if error:
            #     print(error, end='')


try:
    asyncio.run(main())
except (OSError, asyncssh.Error) as exc:
    sys.exit('SSH connection failed: ' + str(exc))
```

**Comment by ronf** [comment]
You're opening up a 'shell' session here, so generally speaking the remote system is going to wait for additional input from you on stdin when it finishes running the initial command you sent to it. There would be no EOF generated in this case, as the remote shell would be expecting to write output for all the commands over a single pair of stdout and stderr streams. Unfortunately, with a setup like this, you can't really know with certainty when you are at the end of command output. The best you could do is to try and search the output for whatever prompt the remote system is writing, and try to use a prompt which will not appear anywhere else in the command output.

An alternative would be to send the command as a "command" argument on `open_session()`. That will open an "exec" session, and will only be good for running a single command. However, you will get EOF on stdout/stderr in this case when the command finishes.

Some devices let you open multiple sessions over a single connection, allowing you to run multiple commands with each command getting its own separate stdin/stdout/stderr. This works well for UNIX servers and also works on some embedded devices, but not all of them. You may get an error when you try to open additional sessions on an existing connection, forcing you to open a new connection for every session (which can be slow). Also, you can't use multiple sessions (or multiple connections) if you need to run commands like "terminal length 0" before the actual command you want the output from, as that only works when both commands are sent on the same session (which must be a shell session).
