### ISSUE TITLE
Unable to run asyncio.run(), cannot be called from a running event loop, multiple tasks, multiple hosts

### ISSUE THREAD

**Issue by anarchy89** [ronf/asyncssh#552]
I have the following code which was helped created by @ronf 

I tested it last time and it worked but for some reason I am getting an error now.

```
import asyncio, asyncssh

async def run_client(host, commands, **kwargs):
    output = ''

    async with asyncssh.connect(host, **kwargs) as conn:
        for i, command in enumerate(commands):
            result = await conn.run(command)

            if result.exit_status != 0:
                output += f'=== Command {i+1}: {command} failed ===\n' + result.stderr
            else:
                output += f'=== Command {i+1}: {command} succeeded ===\n' + result.stdout

        return output

async def run_multiple_clients():
    # Put your lists of hosts and commands here
    hosts = 2*['127.0.0.1'] + ['0.0.0.1']
    commands = ['echo foo', 'echo bar', 'echo baz']

    tasks = (run_client(host, commands, client_keys=['~/.ssh/id_rsa']) for host in hosts)
    results = await asyncio.gather(*tasks, return_exceptions=True)

    for i, result in enumerate(results):
        if isinstance(result, Exception):
            print(f'Connection {i+1} to host {hosts[i]} failed: ' + str(result))
        else:
            print(f'Connection {i+1} to host {hosts[i]}:\n' + result, end='')

        print(75*'-')

asyncio.run(run_multiple_clients()

```

It says 

```
[/mambaforge/envs/extract/lib/python3.11/site-packages/dateutil/parser/_parser.py:192](https://file+.vscode-resource.vscode-cdn.net/mambaforge/envs/extract/lib/python3.11/site-packages/dateutil/parser/_parser.py:192): RuntimeWarning: coroutine 'run_multiple_clients' was never awaited
  raise StopIteration
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
35
35
35
35
36
36
37
37
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[/Volumes/heavy/d/master/scripts/misc/zfix.py](https://file+.vscode-resource.vscode-cdn.net/Volumes/heavy/d/master/scripts/misc/zfix.py) in line 130
    [127](file:///Volumes/heavy/d/master/scripts/misc/zfix.py?line=126) async def main():
    [128](file:///Volumes/heavy/d/master/scripts/misc/zfix.py?line=127)     run_multiple_clients()
--> [130](file:///Volumes/heavy/d/master/scripts/misc/zfix.py?line=129) asyncio.run(main())
    [131](file:///Volumes/heavy/d/master/scripts/misc/zfix.py?line=130) # try:
    [132](file:///Volumes/heavy/d/master/scripts/misc/zfix.py?line=131) #     asyncio.run(run_multiple_clients())
    [133](file:///Volumes/heavy/d/master/scripts/misc/zfix.py?line=132) # except (OSError, asyncssh.Error) as exc:
    [134](file:///Volumes/heavy/d/master/scripts/misc/zfix.py?line=133) #     sys.exit('SSH connection failed: ' + str(exc))

File [~/mambaforge/envs/extract/lib/python3.11/asyncio/runners.py:186](https://file+.vscode-resource.vscode-cdn.net/Volumes/heavy/d/master/~/mambaforge/envs/extract/lib/python3.11/asyncio/runners.py:186), in run(main, debug)
    [161](file:///mambaforge/envs/extract/lib/python3.11/asyncio/runners.py?line=160) """Execute the coroutine and return the result.
    [162](file:///Users/mambaforge/envs/extract/lib/python3.11/asyncio/runners.py?line=161) 
    [163](file:///Users/mambaforge/envs/extract/lib/python3.11/asyncio/runners.py?line=162) This function runs the passed coroutine, taking care of
   (...)
    [182](file:///Users/mambaforge/envs/extract/lib/python3.11/asyncio/runners.py?line=181)     asyncio.run(main())
    [183](file:///Users/mambaforge/envs/extract/lib/python3.11/asyncio/runners.py?line=182) """
    [184](file:///Users/mambaforge/envs/extract/lib/python3.11/asyncio/runners.py?line=183) if events._get_running_loop() is not None:
    [185](file:///Users/mambaforge/envs/extract/lib/python3.11/asyncio/runners.py?line=184)     # fail fast with short traceback
--> [186](file:///Users/mambaforge/envs/extract/lib/python3.11/asyncio/runners.py?line=185)     raise RuntimeError(
    [187](file:///Users/mambaforge/envs/extract/lib/python3.11/asyncio/runners.py?line=186)         "asyncio.run() cannot be called from a running event loop")
    [189](file:///Users/mambaforge/envs/extract/lib/python3.11/asyncio/runners.py?line=188) with Runner(debug=debug) as runner:
    [190](file:///Users/mambaforge/envs/extract/lib/python3.11/asyncio/runners.py?line=189)     return runner.run(main)

RuntimeError: asyncio.run() cannot be called from a running event loop
```

Any ideas on how I can fix it?

**Comment by ronf** [comment]
The traceback here doesn't match up with the example code that you included above. In the code that's failing are you calling asyncio.run() from multiple places? That's generally what will lead to this error, particularly if you attempt to call from inside an async function, or in a non-async function called by an async function.

**Comment by ronf** [comment]
`asyncio.run()` needs to be called exactly once (or once per event loop, if you choose to start more than one of those), from a non-async function that is executed when the code starts up. This `asyncio.run()` call should continue to run indefinitely, unless you choose to exit the associated event loop or until the async function you pass an argument exits.

**Comment by canine-afficionado** [comment]
Thanks @ronf, I'm new to async programming in Python - isn't that what I'm doing here:
```
import asyncio
import asyncssh

async def run_client(host, command: str) -> asyncssh.SSHCompletedProcess:
    async with asyncssh.connect(host, known_hosts=None) as conn:
        return await conn.run(command)

async def run_multiple_clients() -> None:
    # Put your lists of hosts here
    #hosts = 5 * ['localhost']
    hosts = ['MacBook']
    tasks = (run_client(host, 'ls -l') for host in hosts)
    results = await asyncio.gather(*tasks, return_exceptions=True)

    for i, result in enumerate(results, 1):
        if isinstance(result, Exception):
            print('Task %d failed: %s' % (i, str(result)))
        elif result.exit_status != 0:
            print('Task %d exited with status %s:' % (i, result.exit_status))
            print(result.stderr, end='')
        else:
            print('Task %d succeeded:' % i)
            print(result.stdout, end='')

        print(75*'-')

asyncio.run(run_multiple_clients())
```
Am I missing something obvious?

**Comment by ronf** [comment]
It certainly looks like the example you have here should run just fine, and I confirmed it runs fine here.

Is that the only code you're running? If you're executing this after running some other code which starts an async event loop, that could be a problem.

Try changing the `asyncio.run()` call to:

```python
asyncio.get_event_loop().run_until_complete(run_multiple_clients())
```

Does that make a difference?

**Comment by canine-afficionado** [comment]
Thanks @ronf, already tried it with the code you suggested, same problem. Definitely the only code I'm running. Tried running outside of vscode also in case it was some sort of background process causing the problem but same issue. Very basic asyncio code like:
```
import asyncio

async def main():
    await asyncio.sleep(1)
    print('hello')

asyncio.run(main())
```

runs fine in same .venv so maybe an issue with asyncssh? I'm on 3.12.

**Comment by ronf** [comment]
I've tried your example here and it runs fine, so I don't think it is AsyncSSH. It may be a combination of AsyncSSH and something in your environment, but I really don't see any way in which AsyncSSH could start an event loop itself. There's only one module that even tries to query for the existing event loop, but none of those calls are at the top level, and none of those calls actually try to "run" an event loop.

What does the traceback look like when you get the error about not being able to run in an existing event loop on the example you posted here?

Also, what happens if you test with the "hello" example but add an "import asyncssh" to the code after "import asyncio"?

**Comment by canine-afficionado** [comment]
Thanks @ronf enabling the tracemalloc helped me solve it (sort of, don't know why it's happening but I know what the problem is). For some reason when I run this script it's running another script in the same folder which also has an asyncio.run call - when I delete this script the script runs ok. Thanks for your help. Now I have to figure out why it's running another script at the same time.

**Comment by ronf** [comment]
Glad you found it!

Is the other script in the same folder named something like "asyncssh.py", or something else you are importing? If so, that would explain it -- it would be picking up that script when doing the import, rather than the actual AsyncSSH package. You need to be careful not to name your modules things that match other modules/packages you are depending on (directly or indirectly).

**Comment by canine-afficionado** [comment]
It was called 'queue.py' and it was being referred to by the thread.py library which I think the asyncio library must reference. Once I renamed it to queue2.py the problem went away. Lesson learnt. Thanks again for your help.

**Comment by ronf** [comment]
Yeah - name conflicts like this can be tricky, and can at times be really difficult to figure out.

Happy to help!
