### ISSUE TITLE
Host key not trusted / permission denied.

### ISSUE THREAD

**Issue by anarchy89** [ronf/asyncssh#553]
I am connecting to multiple hosts in aws (ec2 instances) using the following command,

I have tried my ssh key individually and it works when I do ssh -i sshkey xx.xx.xx

It also works with tools like cssh, which is a cluster shell tool.

But when I try,

```
import asyncio, asyncssh

async def run_client(host, commands, **kwargs):
    output = ''

    async with asyncssh.connect(host, **kwargs) as conn:
        for i, command in enumerate(commands):
            result = await conn.run(command)

            if result.exit_status != 0:
                output += f'=== Command {i+1}: {command} failed ===\n' + result.stderr
            else:
                output += f'=== Command {i+1}: {command} succeeded ===\n' + result.stdout

        return output

async def run_multiple_clients():
    # Put your lists of hosts and commands here
    hosts = 2*['127.0.0.1'] + ['0.0.0.1']
    commands = ['echo foo', 'echo bar', 'echo baz']

    tasks = (run_client(host, commands, client_keys=['~/.ssh/id_rsa']) for host in hosts)
    results = await asyncio.gather(*tasks, return_exceptions=True)

    for i, result in enumerate(results):
        if isinstance(result, Exception):
            print(f'Connection {i+1} to host {hosts[i]} failed: ' + str(result))
        else:
            print(f'Connection {i+1} to host {hosts[i]}:\n' + result, end='')

        print(75*'-')

asyncio.run(run_multiple_clients()

```

I get this error,

```
Connection 1 to host xx.xx.xx.x failed: Host key is not trusted
---------------------------------------------------------------------------
Connection 2 to host x.xx.x failed: Host key is not trusted
---------------------------------------------------------------------------
Connection 3 to host xx.xx.xx.xx failed: Host key is not trusted
---------------------------------------------------------------------------
Connection 4 to host x.x.x failed: Host key is not trusted
---------------------------------------------------------------------------
Connection 5 to host x.x.x.x failed: Host key is not trusted
---------------------------------------------------------------------------
```
how do i include the username? each of this hosts have the username ubuntu.

i also tried adding `known_hosts=None` but I get the multiple `failed: Permission denied`.

I think it has something to do with this issue https://github.com/ronf/asyncssh/issues/477.

Or is it that the python script doesnt have permission to read the file?

I recently had to deleted the crypto.py file and reinstall OpenSSL with pip as well could it be that? https://askubuntu.com/questions/1430594/broken-pip-due-to-bad-openssl-module

**Comment by anarchy89** [comment]
hey i figured it out, i had to add the username argument.

**Comment by ronf** [comment]
That's strange - the username shouldn't affect known_hosts checking. The error you are getting here of "Host key is not trusted" means that you haven't added an entry in your local known_hosts file for the systems you are trying to reach. If you 'ssh' to each system manually once and tell it to accept the host key, that should be enough to avoid the error in AsyncSSH about not trusting the host. I suspect maybe you did that while testing things, and that's what made the error go away.

As for adding the username, the run_clients() function is designed to let you add arbitrary keyword args and pass them through to asyncssh.connect(). If you add that to the call to run_client() in run_multiple_clients(), it should pass it along. If you needed a different username per host, it would be a bit more complicated. You'd have to update something like the "hosts" variable to contain tuples of host & username and unpack that to pass in to run_clients(). If all the usernames are "ubuntu", though, you can just add `username='ubuntu'` in the call to run_client().
