### ISSUE TITLE
Run command and detach

### ISSUE THREAD

**Issue by anarchy89** [ronf/asyncssh#555]
I am trying to run the following script over my servers.

```
commands = [f'DISPLAY=:0 /home/ubuntu/gatewaystart.sh']
time.sleep(60)
asyncio.run(run_multiple_clients(hosts=hosts, commands=commands, username=REMOTEUSERNAME, client_keys=[SSH_KEY_PATH], known_hosts=None))
```

The problem is that the script is supposed to run continuously, then detach, I can't move on to the rest of my script because it get's stuck here. Is there a way to just run the command and disconnect but ensure that the process keeps running?

**Comment by ronf** [comment]
This isn't an SSH thing, but if you want a program to keep running after its TTY is closed, you'd have to use something like "nohup" to detach it from the TTY before you closed it. This could work, but there's no way to "reattach" from a different TTY later on. If you want that kind of capability, you need something like "screen" or "tmux".
