### ISSUE TITLE
No matching key exchange algorithm found

### ISSUE THREAD

**Issue by xpertimage** [ronf/asyncssh#560]
Using AsyncSSH with Python 3.9 to communicate with Cisco network devices. Certain devices fail with No matching key exchange algorithm found. Details of the error and python code are below. I attempted to add diffie-hellman-group1-sha1 in the "encryption_algs" argument but everything I tried fails.

``` async def fetch_config(hostname, username, password):
    try:
        good_ping = await do_ping(hostname)
        if good_ping:
            async with asyncssh.connect(hostname, username=username, password=password, known_hosts=None, encryption_algs="+aes256-cbc") as conn:
                result = await conn.run('show version')
                # config = result.stdout
                # return True, config
                print(".", end ="",flush=True)
                return True
        else:
            raise('Ping Failed')
    except (asyncssh.Error, BaseException) as e:
        logging.error(f'Error connecting to {hostname}: {e}')
        return False
```

ERROR:root:Error connecting to 146.40.134.4: No matching key exchange algorithm found, sent curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,ecdh-sha2-1.3.132.0.10,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group15-sha512,diffie-hellman-group16-sha512,diffie-hellman-group17-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256@ssh.com,diffie-hellman-group14-sha1,rsa2048-sha256 and received diffie-hellman-group1-sha1

**Comment by ronf** [comment]
What your'e seeing in the negotiation there are key exchange algorithms (kex_algs), not encryption algorithms. You'll need to use the `kex_algs` argument if you want to add back support for diffie-hellman-group1-sha1, which appears to be the only key exchange algorithm that target device supports. You may not need to change `encryption_algs`, but if you do what you've got there looks ok.

**Comment by xpertimage** [comment]
Hey Ron, just got around to testing out your suggestion and as usual everything works fine when I add the kex_algs="+diffie-hellman-group1-sha1". Thanks again for the great support.

**Comment by ronf** [comment]
Happy to help - glad you got it working!
