### ISSUE TITLE
 进程无法被杀死 The process cannot be killed

### ISSUE THREAD

**Issue by wuyuhang409** [ronf/asyncssh#576]
`

async def main():

    conn: asyncssh.SSHClientConnection = await asyncssh.connect(host='xxxx', username='root',
                                                                password=xxxx', known_hosts=None)
    process: asyncssh.SSHClientProcess = await conn.create_process('tail -f /root/projects/test/test2.log')
    process.kill()
    process.close()
    conn.close()

`

当函数执行完成后, 我通过ps aux 进行查看, 发现进程没有被杀死, 我使用kill命令可以杀死进程, 好像kill方法并未正确的发送信号到process
After the function execution was completed, I checked through ps aux and found that the process was not killed. I used the kill command to kill the process, as if the kill method did not correctly send a signal to the process

**Comment by wuyuhang409** [comment]
<img width="613" alt="2" src="https://github.com/ronf/asyncssh/assets/58138896/e9f39ea0-1b7b-491a-83a8-b9e19ab0a9ee">

**Comment by wuyuhang409** [comment]
#112 I found the same issue in this issue, as he said, all signals were not received, and I have closed this issue

**Comment by ronf** [comment]
Yeah - older versions of OpenSSH didn't support the "signal" message, which is also what is used for `kill()` and `terminate()`. So, if your server is running something prior to OpenSSH 7.9 or running another SSH server which doesn't support "signal", that would explain what you saw.

There's a warning in the documentation for `send_signal()` about this:

```python
    def send_signal(self, signal: Union[str, int]) -> None:
        """Send a signal to the remote process

           This method can be called to deliver a signal to the remote
           process or service. Signal names should be as described in
           section 6.10 of :rfc:`RFC 4254 <4254#section-6.10>`, or
           can be integer values as defined in the :mod:`signal`
           module, in which case they will be translated to their
           corresponding signal name before being sent.

           .. note:: OpenSSH's SSH server implementation prior to version
                     7.9 does not support this message, so attempts to
                     use :meth:`send_signal`, :meth:`terminate`, or
                     :meth:`kill` with an older OpenSSH SSH server will
                     end up being ignored. This was tracked in OpenSSH
                     `bug 1424`__.

                     __ https://bugzilla.mindrot.org/show_bug.cgi?id=1424

           :param signal:
               The signal to deliver
           :type signal: `str` or `int`

           :raises: | :exc:`OSError` if the channel is not open
                    | :exc:`ValueError` if the signal number is unknown

        """
```
