### ISSUE TITLE
SSHClientConnectionOptions ignoring fields set after init

### ISSUE THREAD

**Issue by fishstamp82** [ronf/asyncssh#579]
I noticed when using SSHClientConnectionOptions, and modifying the attributes after instantiation, eventually, those set attributes become ignored when calling connect. More precisely after this line of code that does the functools.partial application: https://github.com/ronf/asyncssh/blob/e65ec42d38c5f0c7ce577c06faf116f9af8acc5e/asyncssh/connection.py#L514-L516

Here bellow are two example snippets showing the difference in behavior. In both cases, I would expect preferred_auth to be passed to asyncssh.connect via the options, but it only works for the first example.

### Debug logs

I modify the _run_in_executor to output the options before and after the run in executor command for both examples:

```python

async def _run_in_executor(loop: asyncio.AbstractEventLoop, func: Callable,
                           *args: object, **kwargs: object) -> object:
    """Run a potentially blocking call in an executor"""

    print("before partial", args[0].preferred_auth)
    val = await loop.run_in_executor(
        None, functools.partial(func, *args, **kwargs))
    print("after partial", val.preferred_auth)
    return val
```

## Example 1

``` python

#!/usr/bin/env python

import asyncio, asyncssh, sys, logging

logging.basicConfig(level=logging.DEBUG)
log = logging.getLogger()

async def run_client() -> None:
    options = asyncssh.SSHClientConnectionOptions(
            preferred_auth= ["keyboard-interactive"],
        )

    async with asyncssh.connect('localhost', options=options) as conn:
        result = await conn.run('ls', check=True)
        print(result.stdout, end='')


def main():
    asyncssh.set_log_level(logging.DEBUG)
    try:
        asyncio.get_event_loop().run_until_complete(run_client())
    except (OSError, asyncssh.Error) as exc:
        sys.exit('SSH connection failed: ' + str(exc))

if __name__ == "__main__":
    main()
 ```

Logs:

```bash
before partial ['keyboard-interactive']
after partial ['keyboard-interactive']
```

## Example 2

``` python

#!/usr/bin/env python

import asyncio, asyncssh, sys, logging

logging.basicConfig(level=logging.DEBUG)
log = logging.getLogger()

async def run_client() -> None:
    options = asyncssh.SSHClientConnectionOptions(
        )
    options.preferred_auth= ["keyboard-interactive"]

    async with asyncssh.connect('localhost', options=options) as conn:
        result = await conn.run('ls', check=True)
        print(result.stdout, end='')


def main():
    asyncssh.set_log_level(logging.DEBUG)
    try:
        asyncio.get_event_loop().run_until_complete(run_client())
    except (OSError, asyncssh.Error) as exc:
        sys.exit('SSH connection failed: ' + str(exc))

if __name__ == "__main__":
    main()
 ```

Logs:

```bash
before partial ['keyboard-interactive']
after partial ()
```

Here in the second example it will naturally be set to [b'gssapi-keyex', b'gssapi-with-mic', b'hostbased', b'publickey', b'keyboard-interactive', b'password'] on https://github.com/ronf/asyncssh/blob/e65ec42d38c5f0c7ce577c06faf116f9af8acc5e/asyncssh/connection.py#L3079-L3083

**Comment by ronf** [comment]
Yes - this is by design. Direct assignment to fields within the Options classes is not supported. The class does processing of the input values in some cases that won't run if you directly assign members of the option after it is created.

The right way to do this is to create a new object based on an existing one, using the "options" keyword. For example:

```python
    original_options = asyncssh.SSHClientConnectionOptions(
        # some initial set of keyword arguments here
    )

    new_options = asyncssh.SSHClientConnectionOptions(
        preferred_auth=["keyboard-interactive"],
        options=original_options
    )
```

If you look at the `prepare()` method of these Options classes, you'll see that a whole bunch of translation is done on the keyword arguments passed in at the time of creation that needs to run for the resulting member fields to be set in the right way for the rest of the AsyncSSH code to consume.

**Comment by fishstamp82** [comment]
Good to know it's by design :), thanks for the fast reply.
