### ISSUE TITLE
Why is it that when the downloaded file becomes larger, the speed of asyncssh is slower compared to paramiko?

### ISSUE THREAD

**Issue by FutureSuperCoder** [ronf/asyncssh#589]
Hello, I encountered an issue while using `asyncssh`. When downloading small files (e.g., 100KB), the speed of `asyncssh` is significantly slower compared to `paramiko` (which is synchronous). This is expected. However, when I attempt to download larger files (such as some 200MB file, hello.img, world.img), the download time using `asyncssh` is nearly twice as long as with `paramiko`. I'm curious about the reason behind this discrepancy. 
Here is my script:
```python
start_time = time.time()

async def async2():
    async with asyncssh.connect(ftp_server, username=username, password=password) as conn:
        async with conn.start_sftp_client() as s:
            tasks = [asyncio.create_task(s.get('/home/x/testDir2/hello.img', '/tmp/5.img')),
                        asyncio.create_task(s.get('/home/x/testDir2/hello.img', '/tmp/6.img')),
                        asyncio.create_task(s.get('/home/x/testDir2/hello.img', '/tmp/7.img')),
                        asyncio.create_task(s.get('/home/x/testDir2/world.img', '/tmp/8.img'))]
            done, pending = await asyncio.wait(tasks)
            for task in done:
                print(task.result())

            await asyncio.gather(*tasks)


asyncio.run(async2())
print(f"async endtime: {time.time() - start_time}")
```
When the file being retrieved is small, the speed of asyncssh is very fast.
How should I proceed?

**Comment by ronf** [comment]
If you only set `compression=None` and not `encryption_algs`, do you still see the speedup? AsyncSSH defaults to requesting no compression, but it does offer it. So, if a server decides to force compression, AsyncSSH will honor it. However, on modern networks, the network speeds are so good that it's usually faster to send uncompressed data over the network than it is to burn the extra CPU compressing it first, so it's best to leave compression off.

If it is the encryption algs that are giving you the speedup, that could be because the chacha20-poly1305 algorithm is slower than AES, possibly because of the hardware acceleration available in many modern CPUs for that. My experience has been that Chacha is also quite fast, though, as it was designed to be efficient to implement in software.

Regarding reusing a single connection for multiple SFTP client sessions, that should be fine, but keep in mind that most SSH servers have a limit on how many simultaneous sessions they will allow over a single connection. More importantly, there really isn't a need to create multiple SFTP client sessions at once. It should be perfectly safe (and more efficient) to just create a single FTP client object and use that to make multiple SFTP requests (even in parallel). So, you'd only need a single SSH connection with a single SFTP client session running on it, with potentially hundreds of requests running in "parallel".

In fact, a single sftp.get() call on a large file will generally be turned into multiple parallel requests by default, as a way of speeding things up.

**Comment by FutureSuperCoder** [comment]
Thank you very much for your response. I have greatly benefited from it. Regarding your explanation, I have formed the following understanding. Please let me know if it is correct.

> Regarding reusing a single connection for multiple SFTP client sessions, that should be fine, but keep in mind that most SSH servers have a limit on how many simultaneous sessions they will allow over a single connection. More importantly, there really isn't a need to create multiple SFTP client sessions at once. It should be perfectly safe (and more efficient) to just create a single FTP client object and use that to make multiple SFTP requests (even in parallel). So, you'd only need a single SSH connection with a single SFTP client session running on it, with potentially hundreds of requests running in "parallel".

Does this imply that by using the approach outlined below, the performance is very high and recommended?
```python
import asyncssh
import asyncio

async def create_sftp_client():
    async with asyncssh.connect('your_host', username='your_username') as conn:
        async with conn.start_sftp() as sftp:
            # Perform multiple SFTP operations in parallel using asyncio.gather

            tasks = [
                sftp.get('remote_path1', 'local_path1'),
                sftp.put('local_path2', 'remote_path2'),
                # Add more SFTP operations here
            ]

            await asyncio.gather(*tasks)

asyncio.get_event_loop().run_until_complete(create_sftp_client())

```

> In fact, a single sftp.get() call on a large file will generally be turned into multiple parallel requests by default, as a way of speeding things up.

Does this mean that when I use `await sftp.get(remote_path, local_path)` to download a file, if the file is a very large one, asyncssh will automatically split and process it in parallel internally to enhance the download efficiency, and I don't need to do anything extra?


Finally, when using asyncssh, if I want to avoid compression altogether and reject the server's compression request (if possible), what is the best practice you recommend?

Thank you once again for your answers, I truly appreciate it!

**Comment by ronf** [comment]
Yes - creating parallel tasks on the same SFTP client instance is your most efficient option. As long as the transfers (or other operations you request) don't depend on the outcome of other operations having completed first, you should be fine. In cases where you do need some operations to complete before starting others, you can still use a single SFTP client, but you'd want to break the calls into multiple groups, with a call to `asyncio.gather()` to finish a previous group of operations before starting something that depends on them.

When using the get/put/copy functions, multiple parallel transfers will be started automatically by default, but you can control this using the `block_size` and `max_requests` arguments. In particular, setting `max_requests` to 1 will force the call to be done sequentially (at a much slower speed), but this would probably only be needed if you were talking to an SFTP server that didn't properly handle parallel requests.

Regarding compression, setting `compression=None` in the client connection options as you mentioned above will allow you to make sure compression isn't used, even if a server defaults to requesting it.

**Comment by FutureSuperCoder** [comment]
Thank you for your patient explanations. With the use of your advice, my code has achieved significant performance improvements, and I've gained a deeper understanding of asyncssh. I appreciate your help.

Furthermore, I experimented with using "chacha20-poly1305@openssh.com" as an encryption algorithm, and compared to algorithms like aes128-gcm@openssh.com, it is much slower on my machine.

Regarding your question about `encryption_algs` being a list, it does not necessarily mean that all internal encryption methods will be used simultaneously. Your observation is correct:

```python
encryption_algs = ["chacha20-poly1305@openssh.com", "aes256-gcm@openssh.com"]
encryption_algs = ["aes256-gcm@openssh.com", "chacha20-poly1305@openssh.com"]
```

The performance of the two configurations differs, and the former is noticeably slower, taking almost twice as much time.

If I'm only using a single encryption method, what usage approach do you recommend?

Thank you！

**Comment by ronf** [comment]
For any given connection, exactly one encryption algorithm will be selected. It will be the earliest thing in the client's list that the server supports. So, if you include two algorithms in your `encryption_algs` option and the server supports both of them, you'll end up using whichever algorithm you list first. So, seeing an improvement when you swap the order makes sense, if ChaCha20 really is more expensive on your system.

You can set only a single encryption algorithm in the list if you like. If you run into a server that doesn't  support the algorithm, though, you'll get a failure when you try to connect. So, the usual best practice is to include all the algorithms you'd be willing to use, but put them in order of preference.

**Comment by FutureSuperCoder** [comment]
Once again, thank you for your answers. I greatly appreciate it. I hope asyncssh continues to improve, and I will recommend this library to my colleagues in the hope that they can benefit from it as well. Thanks again.

**Comment by ronf** [comment]
Thank you - happy to help!
