### ISSUE TITLE
How to pass PubkeyAcceptedKeyTypes to the connect method?

### ISSUE THREAD

**Issue by vsafonin** [ronf/asyncssh#595]
Hello, I'm sorry if this information is available in the documentation, but I couldn't find it.

I have an SSH server that doesn't accept 'ssh-rsa' in PubkeyAcceptedAlgorithms. On the server, I see the following message:
```
userauth_pubkey: signature algorithm ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
```
In my code, I catch the "PermissionDenied" exception.

On these servers, I can connect using the regular SSH client with the command:
```
ssh -i mykey user@server.local
```

Is this possible set PubkeyAcceptedAlgoritms?

**Comment by vsafonin** [comment]
now i found workaround, but don't sure that i don't make mistake
i manually set algrotihm to SSHKey object, like this:
```
try:
    username = cred['username']
    keyfile = asyncssh.read_private_key(cred['keyfile'])
    await connect(port=SSH_PORT,
                  known_hosts=None,
                  username=username,
                  keyfile=keyfile)
except PermisionDenied:
    keyfile.algorithm = 'rsa-sha2-256'.encode('ascii')
    try:
        await connect(port=SSH_PORT,
                      known_hosts=None,
                      keyfile=keyfile)
    except PermisionDenied:
        # check another user, file..
        continue
```

and now i can connect to this kind of devices. but this look like kludge

**Comment by ronf** [comment]
Is`mykey` the same key you are trying to pass into AsyncSSH via the `keyfile` argument? Also, I'm guessing you have your own wrapper here, as there is no "keyfile" argument in AsyncSSH itself. Are you setting any other arguments in the `asyncssh.connect()` call, or do you have anything relevant to this in your ~/.ssh/config file?

If the SSH server doesn't advertise 'ssh-rsa' in its list of allowed signature algorithms but it does advertise 'rsa-sha2-256' or 'rsa-sha2-512', AsyncSSH should automatically select one of those stronger signature algorithms when you give it an RSA key to authenticate with. I'm surprised that's not working for you here.

If that's not working (perhaps because the server is continuing to advertise 'ssh-rsa' even though it doesn't support it), you can try manually setting `signature_algs` on the client side to limit what is allowed, leaving out 'ssh-rsa' from the list
and including something like 'rsa-sha2-256'.

I would not recommend the workaround you suggested, as setting "algorithm" directly like that is not supported, in part because there are a number of other related members that really should be updated to match. Also, there are later steps where the SSHKey object is used to initialize an SSHKeyPair, and the signature algorithm can be reset there, possibly overwriting a change you tried to make in some cases.

**Comment by vsafonin** [comment]
> Ismykey the same key you are trying to pass into AsyncSSH via the keyfile argument?
> Also, I'm guessing you have your own wrapper here, as there is no "keyfile" argument in AsyncSSH itself. Are you setting any other arguments in the asyncssh.connect() call, or do you have anything relevant to this in your ~/.ssh/config file?

This is a mistake. I'm using `client_key` instead of `keyfile`.

> If the SSH server doesn't advertise 'ssh-rsa' in its list of allowed signature algorithms but it does advertise 'rsa-sha2-256' or 'rsa-sha2-512', AsyncSSH should automatically select one of those stronger signature algorithms when you give it an RSA key to authenticate with. I'm surprised that's not working for you here.
> 
> If that's not working (perhaps because the server is continuing to advertise 'ssh-rsa' even though it doesn't support it), you can try manually setting signature_algs on the client side to limit what is allowed, leaving out 'ssh-rsa' from the list
> and including something like 'rsa-sha2-256'.
> 

On the destination server, I'm using a default fresh installation of Debian 12. I also send these argument:
```
server_host_key_algs=['ssh-ed25519', 'ssh-dss', 'ssh-rsa', 'rsa-sha2-256']
```

Perhaps this is the reason why AsyncSSH is trying to use 'ssh-rsa' instead of 'rsa-sha2-256'?


> I would not recommend the workaround you suggested, as setting "algorithm" directly like that is not supported, in part because there are a number of other related members that really should be updated to match. Also, there are later steps where the SSHKey object is used to initialize an SSHKeyPair, and the signature algorithm can be reset there, possibly overwriting a change you tried to make in some cases.



Thank you. I rewrote my code to:
```
server_host_key_algs=['ssh-ed25519', 'ssh-dss', 'ssh-rsa', 'rsa-sha2-256']
try:
    username = cred['username']
    keyfile = asyncssh.read_private_key(cred['keyfile'])
    await connect(port=SSH_PORT,
                  known_hosts=None,
                  username=username,
                  client_keys=keyfile,
                  server_host_key_algs=server_host_key_algs)
except PermisionDenied:
    try:
        await connect(port=SSH_PORT,
                      known_hosts=None,
                      client_keys=keyfile,
                      signature_algs='rsa-sha2-256',
                      server_host_key_algs=server_host_key_algs
                      )
    except PermisionDenied:
        # check another user, file..
        continue
```
And this is still working, but it looks better.

**Comment by ronf** [comment]
> On the destination server, I'm using a default fresh installation of Debian 12. I also send these argument:
> 
> ```python
> server_host_key_algs=['ssh-ed25519', 'ssh-dss', 'ssh-rsa', 'rsa-sha2-256']
> ```
> 
> Perhaps this is the reason why AsyncSSH is trying to use 'ssh-rsa' instead of 'rsa-sha2-256'?

This wouldn't affect user authentication. It would only affect which host key the server presented during the initial key exchange, and how that host key was signed. In general, you probably shouldn't include 'ssh-rsa' and 'ssh-dss' there, or if you do you should put those at the very end of the list, preferring the stronger algorithms like Ed25519 and the SHA2 versions of RSA. At the very least, 'rsa-sha2-256' should be in front of 'ssh-rsa'. You can probably just take this argument out and let AsyncSSH use its default for this, which is already sorted in rough order of strength. You'd really only need it if there were some host key algorithms on the server you didn't want to allow.

> Thank you. I rewrote my code to:
> ```python
> server_host_key_algs=['ssh-ed25519', 'ssh-dss', 'ssh-rsa', 'rsa-sha2-256']
> 
> try:
>     username = cred['username']
>     keyfile = asyncssh.read_private_key(cred['keyfile'])
>     await connect(port=SSH_PORT,
>                   known_hosts=None,
>                   username=username,
>                   client_keys=keyfile,
>                   server_host_key_algs=server_host_key_algs)
> except PermisionDenied:
>     try:
>         await connect(port=SSH_PORT,
>                       known_hosts=None,
>                       client_keys=keyfile,
>                       signature_algs='rsa-sha2-256',
>                       server_host_key_algs=server_host_key_algs
>                       )
>     except PermisionDenied:
>         # check another user, file..
>         continue
> ```

This is looking better, but you might want to instead just change the first "await connect" to already include:

```python
    signature_algs = 'rsa-sha2-256'
```

This may eliminate the need for the outer "try" block. This is assuming your keyfile will always be an RSA key. If you want to support other key types, you might try something like:

```python
    signature_algs = '-ssh-rsa'
```

This will leave the signature algs as the default value, but just remove 'ssh-rsa' from the list of things it will try (in cases where the keyfile is RSA).
