### ISSUE TITLE
 module 'asyncssh' has no attribute 'connect'

### ISSUE THREAD

**Issue by Iyamoto** [ronf/asyncssh#60]
Hi.
I try to run https://github.com/ronf/asyncssh/blob/master/examples/gather_results.py
and get "Task 1 failed: module 'asyncssh' has no attribute 'connect'" error.
Any ideas?

**Comment by ronf** [comment]
I see you closed this shortly after opening it. Did you figure out the problem?

**Comment by Iyamoto** [comment]
Yes, I did. It was just a stupid mistake on my side :) Named my test file "asyncss.py"...

**Comment by xpertimage** [comment]
I am happy to see that I am not the only one :-/
