### ISSUE TITLE
Piping binary data around seems to break things.

### ISSUE THREAD

**Issue by oliwarner** [ronf/asyncssh#61]
I've been working on something to take screenshots from some of our kiosks over SSH but binary data seems to break things. I get an empty `SSHCompletedProcess` back:

    SSHCompletedProcess(exit_status=None, exit_signal=None, stdout='', stderr='')

This isn't just redirection (per my example below). Text works fine. And if I remotely pipe binary data through `base64` (for example), I can get it back centrally and then reprocess it back into binary... But that's more computation and more code. It'd be nice if asyncssh handled binary natively.

```
import os, asyncio, asyncssh

CMD_SCREENSHOT = 'DISPLAY=:0 import -window root png:-'
CMD_SCREENSHOT = 'ls -Al'

screenshot_directory = os.path.join(settings.MEDIA_ROOT, 'kiosks')
if not os.path.exists(screenshot_directory):
    os.mkdir(screenshot_directory)  # just in case

async def run_client(kiosk, via=None):
    kwargs = {
        # connection info
    }
    async with asyncssh.connect(**kwargs) as conn:
        result = await conn.run(
            CMD_SCREENSHOT,
            check=True,
            stdout=os.path.join(screenshot_directory, '%s.png' % kiosk.pk)
        )
        print(result)

asyncio.get_event_loop().run_until_complete(asyncio.gather(*(
    run_client(kiosk)
    for kiosk in Kiosk.objects.filter(...)
), return_exceptions=True))

**Comment by ronf** [comment]
You should be able to send binary data over the SSH channel. However, you need to add "encoding=None" as an argument to the command you use when you open it, which in this case is the "conn.run" call. By default, all input and output on stdin/stdout/stderr is treated as UTF-8 and automatically converted to Python strings containing Unicode characters. By specifying "encoding=None", though, all input and output will be left as a Python "bytes" object.

**Comment by oliwarner** [comment]
_Perfect_. Thank you, that's much cleaner than than what I'd actually been doing.
