### ISSUE TITLE
Key based authentication to the destination server from the tunnel 

### ISSUE THREAD

**Issue by ashokMafiree** [ronf/asyncssh#614]
We have a couple of servers to connect and fetch the server stats parallelly, so we decided to use asyncssh to achive this, we have two methods to connect the destination server from our application server, 1. direct ssh, 2.ssh to tunnel then ssh to destination via tunnel connection object.

Note : Both direct and tunnel SSH connections should be established using the client key (RSA key) since we do not use passwords.

But the problem statement is, i can connect the tunnel server using the key, because the key available in the application where we are trying to connect the tunnel, but after that while connecting to the desination server from the tunnel object, its throws an error "No such file or directory" because its again trying to find the key file in the application server instead of the tunnel server

s there any workaround for this scenario, or am I going wrong?

Attaching the code for reference 

    `from flask import Flask, jsonify
    import asyncio
    import asyncssh
    
    app = Flask(__name__)
    
    async def create_ssh_tunnel():
        tunnel_info = {
            'host': '192.168.13.11',
            'port': 22,
            'username': 'tunnel',
            'client_keys': ['/home/application_user/.ssh/webssh_key']
        }

    async with asyncssh.connect(**tunnel_info) as conn:
        tunnel = await conn.forward_local_port('', 8081, '192.168.13.55', 22)
        return tunnel

    async def connect_through_tunnel():
        destination_info = {
            'host': 'localhost',
            'port': 22,
            'username': 'destination',
            'client_keys': ['/home/tunnel_user/.ssh/key']
        }

    async with asyncssh.connect(**destination_info) as conn:
        result = await conn.run('echo "Hello, Destination Server!"', check=True)
        return result.stdout.strip()

    async def async_task():
        tunnel = await create_ssh_tunnel()
        result = await connect_through_tunnel()
        tunnel.close()
        return {'result': result}

      @app.route('/async-route')
      async def async_route():
          result = await async_task()
          print(result)
          return jsonify(result)
      
      if __name__ == '__main__':
          app.run(debug=True, port=5001)`

**Comment by ronf** [comment]
There are better ways in AsyncSSH of setting up an SSH tunnel (using the `tunnel` argument in `asyncssh.connect()` or using the `connect_ssh()` method of SSHClientConnection. However, it should be possible to do what you want with `forward_local_port()` as you're attempting here.

Looking at the code, you seem to be setting up a local listener on port 8081 which forwards to 192.168.13.55 on port 22, but the `connect_through_tunnel()` method appears to be connecting to port 22 and not port 8081. So, it would attempt to log into the SSH server on the client machine, not the one on 192.168.13.55. I think you need to set `port` to 8081 in that tunnel connect call.

**Comment by ashokMafiree** [comment]
Thank you for your response. I made modifications to the code by adding two methods, one with tunnel arguments and another without. However, I am still encountering the same error: "No such file or directory /home/tunnel_user/.ssh/key." I believe that even though we pass the tunnel argument when creating a connection object, the application is still searching for the key on the application server instead of the tunnel server.

Kindly a have a look on the below code

`
from flask import Flask, jsonify
import asyncio
import asyncssh

app = Flask(__name__)

async def connect_server_method1():
	async with asyncssh.connect("192.168.13.11", username='tunnel_user', client_keys=['/home/application_user/.ssh/key']) as tunnel_conn:
		async with tunnel_conn.connect_ssh("192.168.13.55", username='destination_user',client_keys=["/home/tunnel_user/.ssh/key"]) as conn:
			result = await conn.run('pwd')
			return f"Output from 192.168.13.55:\n{result.stdout}"

async def connect_server_method2():
	async with asyncssh.connect("192.168.13.11", username='tunnel_user', client_keys=['/home/application_user/.ssh/key']) as tunnel_conn:
		local_port = await tunnel_conn.forward_local_port('', 8081, '192.168.13.55', 22)
		async with asyncssh.connect("localhost", port=local_port, tunnel=tunnel_conn, username='destination_user',client_keys=["/home/tunnel_user/.ssh/key"]) as conn:
			result = await conn.run('pwd')
			return f"Output from 192.168.13.55:\n{result.stdout}"

async def async_task():
    result1 = await connect_server_method1()
    result2 = await connect_server_method2()
    return {"result1" : result1, "result2" : result2}

@app.route('/async-route')
async def async_route():
    result = await async_task()
    print(result)
    return jsonify(result)

if __name__ == '__main__':
    app.run(debug=True, host='192.168.13.10', port=5000)

`

**Comment by ashokMafiree** [comment]
Thanks for the clarification. As you mentioned, we can execute commands using `conn.run`. but In my case, I need to gather server statistics such as CPU usage, RAM usage, load, and disk usage. Additionally, I need to collect database statistics, and since the end server may have various databases like MySQL, MongoDB, PostgreSQL, etc., the approach needs to be dynamic.

I think `conn.run` is a costly operation for my use case, as the number of commands might increase, making it challenging to process the results efficiently.

Is there an alternative approach that better fits my use case?

**Comment by ashokMafiree** [comment]
Sorry for the delayed response. Finally, we achieved it by reading the keyfile contents via `sftp` and using the `import_private_key` options. Let's take a look at the functions below for both single and multiple tunnel connections.

`
async def single_jump():
    try:
    	start_time = datetime.now()
    	async with asyncssh.connect("192.168.13.11", username='tunnel_user', client_keys=["/home/application_user/.ssh/key"]) as tunnel_conn:
        	async with await tunnel_conn.start_sftp_client() as sftp:
        		async with await sftp.open('/home/tunnel_user/.ssh/key', 'r') as remote_file:
        			private_key = asyncssh.import_private_key(await remote_file.read())
        			async with asyncssh.connect("192.168.13.55", username='destination_user', client_keys=[private_key]) as conn:
        				result = await conn.run('pwd')
        				connection_time = datetime.now() - start_time
        				print(connection_time)
        				return f"Output from 192.168.13.55:\n{result.stdout}"
    except asyncssh.Error as e:
        return f"Error: {e}"

async def dual_jump():
	try:
		start_time = datetime.now()
		async with asyncssh.connect("192.168.13.11", username='tunnel_user', client_keys=["/home/application_user/.ssh/key"]) as tunnel_conn_1:
			async with await tunnel_conn_1.start_sftp_client() as sftp:
				async with await sftp.open('/home/tunnel_user/.ssh/key', 'r') as remote_file:
					private_key = asyncssh.import_private_key(await remote_file.read())
					async with asyncssh.connect("192.168.13.40", username='tunnel2_user', client_keys=[private_key]) as tunnel_conn_2:
						async with await tunnel_conn_2.start_sftp_client() as sftp:
							async with await sftp.open('/home/tunnel2_user/.ssh/key', 'r') as tunnel_2_file:
								tunnel_2_key = asyncssh.import_private_key(await tunnel_2_file.read())
								async with asyncssh.connect("192.168.13.55", username='destination_user', client_keys=[tunnel_2_key]) as conn:
									result = await conn.run('pwd')
									connection_time = datetime.now() - start_time
									print(connection_time)
									return f"Output from 192.168.13.55:\n{result.stdout}"
	except asyncssh.Error as e:
		return f"Error: {e}"

`

**Comment by ronf** [comment]
Yes - this looks like it should work, but you are no longer actually tunneling the later SSH connections. It looks like you are just getting the client key from the tunnel_user and then making a direct connection using that key from the original client machine.

Also, in the current single_jump() example, the line "async with await tunnel_conn.start_sftp_client() as sftp:" appears to not be indented correctly.

You can also avoid a lot of the indentation here if you like, as there's no reason to keep around the SFTP sessions after you finish reading the private key from them. So, the next connect() call could happen at the same level as the prior connect(), after the call to import_private_key(). This would close the earlier connections and associated SFTP clients before opening the next connection.

If you did want to tell through the host you are getting the keys from, you could keep open the connection to the tunnel host, but still let the SFTP close. This would look something like:

```python
    async def single_jump():
        try:
	    start_time = datetime.now()
	    async with asyncssh.connect("192.168.13.11", username='tunnel_user', client_keys=["/home/application_user/.ssh/key"]) as tunnel_conn:
    	        async with await tunnel_conn.start_sftp_client() as sftp:
    		    async with await sftp.open('/home/tunnel_user/.ssh/key', 'r') as remote_file:
                        private_key = asyncssh.import_private_key(await remote_file.read())

    		async with tunnel_conn.connect_ssh("192.168.13.55", username='destination_user', client_keys=[private_key]) as conn:
    		     result = await conn.run('pwd')
                     connection_time = datetime.now() - start_time
                     print(connection_time)
                     return f"Output from 192.168.13.55:\n{result.stdout}"
        except asyncssh.Error as e:
            return f"Error: {e}"
```

This same approach could be used for the second level of tunneling, keeping both of the original tunnel connection open but letting the SFTP sessions be cleaned up before calling the next connect_ssh().

**Comment by ashokMafiree** [comment]
Thank you so much for your support, its working as expected

**Comment by ronf** [comment]
Glad to hear it - happy to help!
