### ISSUE TITLE
Is it possible to get the hostname of SSHServerChannel connection?

### ISSUE THREAD

**Issue by rojamit** [ronf/asyncssh#640]
for example i connecting to asyncssh server with command: 
`ssh root@asyncsshserver.domain`

Is it possible to get "asyncsshserver.domain" from SSH handshake?

**Comment by ronf** [comment]
Sorry, no - the SSH protocol doesn't have anything like Server Name Indication (SNI) in SSL/TLS. The client resolves the hostname to decide what IP address to connect to, but it doesn't send the hostname anywhere in the SSH handshake. The best you can do is get the IP address that the client connected to, which could let you distinguish requests to different hosts if you give each host a unique IP address and have AsyncSSH listen on all of those addresses.
