### ISSUE TITLE
Building modules in a chroot with no SSH binaries fails

### ISSUE THREAD

**Issue by cooperlees** [ronf/asyncssh#65]
If we don't have a ssh binary in the chroot we are building the pyc files in we fail. Can we potentially have a way to specify the $(ssh -V) output so configuration / unit tests can pass and do what they need to do?

Stack Trace:
http://pastebin.com/jDqxvCW5

**Comment by cooperlees** [comment]
I see it's only to help workout what ciphers to test:
https://github.com/ronf/asyncssh/blob/master/tests/test_public_key.py#L92-L100

**Comment by ronf** [comment]
Yes, that's right. The unit tests currently depend on ssh-keygen being available in the environment to generate keys, and there was a problem with older versions of ssh-keygen failing on the GCM and Chacha tests due to a bug.

If you don't have 'ssh' in the environment, I'm guessing you won't have 'ssh-keygen' either, so I don't think you'll be able to properly run the public_key unit tests.

**Comment by cooperlees** [comment]
How do you feel about using Paramiko's native Python ssh-keygen like implementation so we could include these libs with asyncssh and use that rather than forking out to ssh and ssh-keygen?

e.g.
https://github.com/paramiko/paramiko/blob/master/demos/demo_keygen.py

**Comment by ronf** [comment]
For key generation itself, there's no reason to pull in Paramiko here. As of release 1.7.0, AsyncSSH has a complete implementation of key generation and it is already using that in its unit tests to generate both public/private key pairs and certificates.

The reason there's still a dependency on "ssh-keygen" is that I wanted tests which validated that AsyncSSH can import keys from and export keys to other SSH implementations. There's also an external dependency on "openssl" here for testing non-SSH key formats like PKCS#1 and PKCS#8.

I could possibly rewrite the tests to fall back to using only AsyncSSH's own key conversion code when "openssl" and "ssh-keygen" were not available on the system. I do that already in one case today for PKCS#1 public key tests as OpenSSL no longer supports that format. If I were to do that, though, running the tests on systems without these external binaries wouldn't be able to catch some interoperability errors.

Would that address your issue?

**Comment by ronf** [comment]
I just checked a change into the "develop" branch which should allow the public key unit tests to run on systems without openssl or openssh installed.

@cooperlees, if you're able to test this, please let me know if it solves the problem you had. If it does, I'll try to get a release which includes it out soon.

**Comment by cooperlees** [comment]
Thanks @ronf. I wasn't going to knock something up. I was only suggesting parimiko so you could test against something, but just saving known output to files is prob good enough.

I was going to knock something up, but thanks. I'll test tomorrow! Thanks.

**Comment by cooperlees** [comment]
I went to go read the diff / commit for the tests, I may be blind or a github noob - But I don't see it? Am I missing something? https://github.com/ronf/asyncssh/commits/develop

**Comment by ronf** [comment]
If you normally use "pip" to install AsyncSSH, you can run the following:

pip install git+https://github.com/ronf/asyncssh@develop

If you'd prefer to fetch it from git, there should be a "Clone or Download" button at https://github.com/ronf/asyncssh/tree/develop which you can use for that.

**Comment by cooperlees** [comment]
I tested, they still fail the same. I don't see the code diff / commit to make unit tests not fail for me, this was why I asked before. Can you point at the diff that should make me not run 'ssh -V' etc. please @ronf 

# Error:
subprocess.CalledProcessError: Command 'ssh -V' returned non-zero exit status 127

# How I tested:
- Downloaded https://github.com/ronf/asyncssh/archive/develop.zip
- Copied it to my development server and built / tested the project in isolated chroots with our (Facebook's) internal third party module system.
- Received same error above

**Comment by ronf** [comment]
My apologies! I checked in the changes, but I apparently never sync'd them back to Github. There are two commits related to this made about 4 days ago that I just pushed. You can see a diff here:

https://github.com/ronf/asyncssh/compare/develop

**Comment by cooperlees** [comment]
Now this actually shows me where it's going to compare within itself :) - Testing now. Thanks!

**Comment by cooperlees** [comment]
Seems server.py needs some love:
asyncSetUpClass(cls):
File "/home/engshare/third-party2/asyncssh/develop/src/build-gcc-4.9-glibc-2.20/build/tests/server.py", line 134, in asyncSetUpClass
  output = run('ssh-agent -a agent 2>/dev/null')
File "/home/engshare/third-party2/asyncssh/develop/src/build-gcc-4.9-glibc-2.20/build/tests/util.py", line 147, in run
    stderr=subprocess.STDOUT)

Maybe just save a fake str and try: except: around the run() to catch the CalledProcessError and fall back to using the fake saved string?

**Comment by ronf** [comment]
Ah, good point. I took care of all the references I could find to "ssh-keygen" and "openssl", but I didn't do anything to put conditions around the ssh-agent tests. I don't have my own implementation of the server to fall back on there, but I can skip those tests on systems that don't have ssh-agent available.

Unfortunately, this isn't something that can be faked out with a static string. The ssh-agent code does crypto operations for you on random data.

**Comment by ronf** [comment]
Ok - I just checked in https://github.com/ronf/asyncssh/commit/c9c4406452d92592af8da1b088cf3da26b16a58f to skip the SSH agent unit tests if the ssh-agent binary is not available. Thanks for helping to test this!

**Comment by cooperlees** [comment]
https://github.com/ronf/asyncssh/pull/66

**Comment by cooperlees** [comment]
Just tested latest develop unit tests. Failed with a UnicodeEncodeError - 'ascii' fun - Full stack trace:
http://pastebin.com/D5zPeQHs

**Comment by ronf** [comment]
Huh. It appears that your system must have 'ascii' as the default encoding for file I/O, rather than 'utf-8', so no Unicode data can be written to files without explicitly setting the encoding. Can you try replacing:

    with open('stdin', 'w') as file:

with:

    with open('stdin', 'w', encoding='utf-8') as file:

in test_split_unicode()?

There may be other places this is needed as well. I haven't run into this here because both the MacOS and Linux systems I test on all default to 'utf-8'.

**Comment by cooperlees** [comment]
#legacyFun

I set the code to run with the default encoding/decoding of 'en_US.UTF8' and we all passed. The unit tests as is should be great to ship. Many thanks for all the help here @ronf !

I'll look to change the default to 'en_US.UTF8' for Python 3 here as a whole (as I believe it should be).

**Comment by ronf** [comment]
To be on the safe side, I've gone ahead and changed this test to open the file with encoding set explicitly to UTF-8, rather than depending on that being the system default.

I also looked through all the other tests and couldn't find any that were writing non-ASCII data to files, so the lack of an explicit encoding shouldn't be a problem in any of those other places. Thanks for the report!

**Comment by cooperlees** [comment]
What's the timeline on 1.7.3?

**Comment by ronf** [comment]
I'll try to get an update out with the unit test fixes later this week.

I'm also getting close on having client-side support done for X11 forwarding, and hope to have a first cut of that in the 'develop' branch by the weekend.

**Comment by ronf** [comment]
This is now released in AsyncSSH version 1.7.3.
