### ISSUE TITLE
Is there any method avaible in asyncssh to send large packet to server so it drops ssh connection

### ISSUE THREAD

**Issue by rahulcode60** [ronf/asyncssh#650]
Hi,
I am testing one scenario where in i want send large packet to server so it drops the ssh connection. I tried using chan.write method but somehow it is not working. Is there any method or way  available to send large packet using asyncssh?

I am testing this scenario FCS_SSHC_EXT.1.3The  TSF  shall  ensure  that,  as described  in  RFC  4253,  
packets  greater than [assignment: number of bytes]bytes in  an SSH transport  connection  are dropped.

**Comment by ronf** [comment]
There's no public API for this in AsyncSSH. There's a `send_packet()` method on SSHChannel which lets you send arbitrary packets, but you'd have to import the message number constant and encoding function from internal AsyncSSH modules.

More specifically, a data packet would be sent by doing something like:

```python
from asyncssh.constants import MSG_CHANNEL_DATA
from asyncssh.packet import String
```

and then later:

```python
chan.send_packet(MSG_CHANNEL_DATA, String(data))
```

Also, note that the maximum packet size is determined during the opening of a channel, and can vary. AsyncSSH defaults to setting a max packet size of 32 KiB (32768 bytes), but callers can set larger values when they create a channel object. This maximum size can also be sent independently in the two directions, so you'd need to look at the value returned when you opened a channel to see what the maximum packet of the peer is actually set to. That shows up in debugging output in AsyncSSH, but there's no public API to query that value. AsyncSSH automatically breaks any written data down into packets which conform to the receiver's current window size and maximum packet size, so callers don't need to worry about it.

As an aside, while AsyncSSH advertises whatever max packet size the caller requests, it actually doesn't enforce that limit at the moment for packets it receives. Packets larger than that are accepted, as long as the packet length doesn't exceed the current receive window size. If that happens, the entire connection is dropped with a Protocol Error. I'm not sure offhand if other SSH implementations currently enforce this or not, or if they provide control over this value.

**Comment by rahulcode60** [comment]
Thankyou so much @ronf. That worked for me.
