### ISSUE TITLE
asyncssh raises ValueError if `SetEnv` is used in SSH config

### ISSUE THREAD

**Issue by siddhpant** [ronf/asyncssh#661]
I have `SetEnv TERM=xterm-256color` towards the top of my SSH config.

Afterwards, when I use asyncssh, it raises `ValueError: Invalid environment value`.

If I remove the `SetEnv` line, asyncssh works.

This seems to be the offending code: https://github.com/ronf/asyncssh/blob/43bcd2d4be250e91d3603a3d7cafa17f1ad294bb/asyncssh/connection.py#L4130-L4137

**Comment by ronf** [comment]
I'm not able to reproduce this here. Can you provide an example of the call you are making to AsyncSSH which triggers this?

Also, do you have any other SetEnv references in your SSH config file?

Are you passing any "env" argument directly into AsyncSSH, or is the only reference to it in your SSH config?

Have you tried printing out the value of "env" in the code you listed above? What does it look like when it fails?

**Comment by ronf** [comment]
Actually, I take it back - I am now able to reproduce it. It looks like it may be related to trying to allow '=' instead of space in other SSH config options. The code handling SetEnv requires '=', but the parser was changed to convert '=' to spaces in some cases and so it isn't finding the '=' that it is looking for when handling SetEnv.

I'll need to think about how to fix this, as I don't want to break the case where you pass in `env` directly (and the '=' to space conversion doesn't happen). I'm thinking maybe of disabling this conversion specifically for SetEnv in the config parser, so it works like it did before the parser was generalized to treat '=' as whitespace. However, I also want to see how OpenSSH handles this, and whether it allows either '=' or spaces in SetEnv. If it does, I'll want AsyncSSH to support both as well.

I'll try and get you something this evening.

**Comment by siddhpant** [comment]
The fix works! Thank you!

**Comment by ronf** [comment]
Thanks for the confirmation. A slightly updated version of this fix is now available as commit https://github.com/ronf/asyncssh/commit/9ad96886359f7505e782dad218b35835cfc6f2f7 in the "develop" branch. It corrects an issue I discovered after running the unit tests.

**Comment by siddhpant** [comment]
Hi, I had not tested the updated fix. It is broken due to `i > 1` condition.

```python
if i == 1:
    loption = args.pop(0).lower()
elif i > 1 and loption not in self._conditionals:
    args.extend(split_args[i:])
    break
```

should instead be:

```python
if i == 1:
    loption = args.pop(0).lower()

if loption not in self._conditionals:
    args.extend(split_args[i:])
```

Example: `split_args = ['SetEnv', 'TERM=xterm-256color']`

**Comment by ronf** [comment]
Yeah - this isn't quite right. It breaks in the case where you set 'Compression = yes' with spaces on both sides of the equals, or with a space on one side or the other, both of which are allowed by OpenSSH.

That said, you're right that it is breaking in the 'SetEnv A=1 B=2 C=3' case, though. I'll take another look at it.

**Comment by ronf** [comment]
Ok - I think this might do it:

```patch
diff --git a/asyncssh/config.py b/asyncssh/config.py
index f239b26..18ff3c8 100644
--- a/asyncssh/config.py
+++ b/asyncssh/config.py
@@ -321,11 +321,15 @@ class SSHConfig:

                 args = []
                 loption = ''
+                allow_equal = True

                 for i, arg in enumerate(split_args, 1):
                     if arg.startswith('='):
                         if len(arg) > 1:
                             args.append(arg[1:])
+                    elif not allow_equal:
+                        args.extend(split_args[i-1:])
+                        break
                     elif arg.endswith('='):
                         args.append(arg[:-1])
                     elif '=' in arg:
@@ -337,9 +341,7 @@ class SSHConfig:

                     if i == 1:
                         loption = args.pop(0).lower()
-                    elif i > 1 and loption not in self._conditionals:
-                        args.extend(split_args[i:])
-                        break
+                        allow_equal = loption in self._conditionals

                 if loption in self._no_split:
                     args = [line.lstrip()[len(loption):].strip()]
diff --git a/asyncssh/connection.py b/asyncssh/connection.py
index 665075f..9c05c5e 100644
--- a/asyncssh/connection.py
+++ b/asyncssh/connection.py
@@ -4232,7 +4232,7 @@ class SSHClientConnection(SSHConnection):
         if env:
             try:
                 if isinstance(env, list):
-                    new_env.update((item.split('=', 2) for item in env))
+                    new_env.update((item.split('=', 1) for item in env))
                 else:
                     new_env.update(cast(Mapping[str, str], env))
             except ValueError:
```

**Comment by ronf** [comment]
The above fix is now available as commit 68c2df7 in the "develop" branch.

**Comment by siddhpant** [comment]
Thank you! Installed develop, and it works now.

**Comment by ronf** [comment]
Thanks for catching this, and helping to test the fix! This will be included in the next release.

**Comment by tchalupnik** [comment]
Hello!
Ronf, if I take the updated portion of the code and make a function out of it:

```
def test(split_args: list[str]) -> list[str]:
    args = []
    loption = ''
    allow_equal = True

    for i, arg in enumerate(split_args, 1):
        if arg.startswith('='):
            if len(arg) > 1:
                args.append(arg[1:])
            elif not allow_equal:
                args.extend(split_args[i-1:])
                break
        elif arg.endswith('='):
            args.append(arg[:-1])
        elif '=' in arg:
            arg, val = arg.split('=', 1)
            args.append(arg)
            args.append(val)
        else:
            args.append(arg)

        if i == 1:
            loption = args.pop(0).lower()
            allow_equal = loption in {}
    return args


print(test(["SetEnv", "TERM=xterm-256color"]))
```
In a result I get:
```python
['TERM', 'xterm-256color']
```
But I should see:
```python
['TERM=xterm-256color']
```

**Comment by siddhpant** [comment]
@tchalupnik You are checking for existence in an empty dict.

**Comment by tchalupnik** [comment]
> @tchalupnik You are checking for existence in an empty dict.

Oh yeah, just for the test only.
```python
_conditionals = {'match'}
```
`_conditionals` is a dict that contains that one element 'match' that has nothing to do with `setenv`

**Comment by tchalupnik** [comment]
While copy-pasing the code I made one indentation too much. Sorry for bothering you all.
