### ISSUE TITLE
SSH connection failed: Permission denied for user 

### ISSUE THREAD

**Issue by cjh1** [ronf/asyncssh#692]
We are running into an issue with key/cert based authentication when using asyncssh. The same credentials work with the regular ssh command line.  

Here is the failing asyncssh log:
[asyncssh.txt](https://github.com/user-attachments/files/17121174/asyncssh.txt)

Here is the working ssh log:
[ssh.txt](https://github.com/user-attachments/files/17121151/ssh.txt)

Any insight would be gratefully received.

**Comment by cjh1** [comment]
I just tried with paramiko and it also works successfully

**Comment by cjh1** [comment]
Figured this out, `preferred_auth=['publickey']` resolved the issue.

**Comment by ronf** [comment]
Glad you figured out how to make it work. I'm guessing you're running into a problem with it attempting too many auth methods before running out of tries on the server side. On AsyncSSH, gssapi-keyex, gssapi-with-mic, and hostbased can be tried before publickey by default. On OpenSSH running as a server, the MaxAuthTries value defaults to 6, so you can't try very many options before that runs out, especially if you have multiple public keys to try. I'm guessing that if you specified exactly which public key/cert to use, that might also solve the problem.

In your specific case, it looks like neither of the gssapi options are tried, but AsyncSSH is trying hostbased auth, which may be just enough to push the right public key beyond the 6 tries.

It looks like it is trying public key auth first for an SSH key and key with a cert. Then it tries host-based, and then it seems to try public key again with another RSA key but never gets to trying a cert the second time. It'd make sense that this was failing if it didn't get a trying to try the second RSA key with its cert.

**Comment by cjh1** [comment]
@ronf Thanks very much for your response. We are explicitly providing the key and cert using `client_keys` ( is that the right way todo it ? ), but its seems it was still necessary to use `preferred_auth=['publickey']`. Unfortunately, I have limited visibility on the server side, but you might well be right that we are running out of tries.

**Comment by ronf** [comment]
Yes - setting client_keys would be right. Are you passing in a list containing a tuple of a private key and a certificate, to indicate you want to authenticate with the cert? If you are passing in a filename of the private key and there's a file with the same name plus '-cert.pub' containing a cert, it might also find it automatically.

Also, are you setting known_client_hosts, or implementing a custom SSHClient class with a callback method of `host_based_auth_supported`? Without one of those, I wouldn't expect host-based auth to be attempted, but there is one entry in the AsyncSSH log showing trying it that I can't explain.

**Comment by cjh1** [comment]
> Yes - setting client_keys would be right. Are you passing in a list containing a tuple of a private key and a certificate, to indicate you want to authenticate with the cert?

Yes

> Also, are you setting known_client_hosts, or implementing a custom SSHClient class with a callback method of `host_based_auth_supported`? Without one of those, I wouldn't expect host-based auth to be attempted, but there is one entry in the AsyncSSH log showing trying it that I can't explain.

No host based setting or custom client classes. 

I appreciate your help, but don't want to take anymore of your time! Thanks for a great package.

**Comment by ronf** [comment]
No problem - happy to help! Have a good day...
