### ISSUE TITLE
Different env variables when connecting with asyncssh

### ISSUE THREAD

**Issue by epg584** [ronf/asyncssh#704]
I'm getting different outputs when I connect to a server (macos, btw) with asyncssh, compared to manually ssh'ing to the server. If I connect manually, I see a bunch more variables when doing the 'env' command, and the problem is that the PATH is different then when I connect with asyncssh. Obviously using the same user credentials in both cases:
- manual connection:
__CFBundleIdentifier=com.apple.Terminal
TMPDIR=/var/folders/8j/m1hyjrzs6zggvs7cr9c5nq040000gn/T/
XPC_FLAGS=0x0
TERM=xterm-256color
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.V5bRKaH4Fe/Listeners
XPC_SERVICE_NAME=0
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=453
TERM_SESSION_ID=66340E77-AD81-4112-845D-0C46FEF408AA
SHELL=/bin/zsh
HOME=/Users/frl
LOGNAME=frl
USER=frl
PATH=/opt/homebrew/opt/node@20/bin:/opt/homebrew/opt/node@20/bin:/Users/frl/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin
SHLVL=1
PWD=/Users/frl
OLDPWD=/Users/frl
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_REPOSITORY=/opt/homebrew
MANPATH=/opt/homebrew/share/man::
INFOPATH=/opt/homebrew/share/info:
LANG=en_US.UTF-8
_=/usr/bin/env

- from asyncssh:
USER=frl
LOGNAME=frl
HOME=/Users/frl
PATH=/usr/bin:/bin:/usr/sbin:/sbin
SHELL=/bin/zsh
SSH_CLIENT=192.168.10.110 59383 22
SSH_CONNECTION=192.168.10.110 59383 192.168.10.2 22
TMPDIR=/var/folders/8j/m1hyjrzs6zggvs7cr9c5nq040000gn/T/
SHLVL=0
PWD=/Users/frl
OLDPWD=/Users/frl
_=/usr/bin/env

Why is that? How can I set the same PATH on asyncssh connections that I have on ssh connections?

**Comment by ronf** [comment]
Are you attempting to open an interactive shell, or are you just running a single command?

Also, I don't see TERM set on the asyncssh session, suggesting you are not requesting a pseudo-TTY. That can make a difference in which shell startup files get executed on the remote system, affecting what environment variables end up being set there (completely independent of what's set on the client and sent over the SSH connection).

Also, are you doing something in the SSH config to tell it to send all environment variables on the client and accept them on the server? Normally, only a small number of variables are actually accepted by the SSH server.

**Comment by epg584** [comment]
Thank you for the quick reply! I thought TERM was mandatory, isn't that the case? How do I set it?

And I'm trying to shoot commands to the mac and read back the outputs, so interactive. It works fine if I use the full path but in order to scale this, I'd need the proper path settings.

And I didn't make any changes to sshd_config, but if a normal ssh session from the same client to the same server works fine, I assume the sshd_config is good, right?

**Comment by ronf** [comment]
If you set the `term_type` argument when starting up the session, AsyncSSH will automatically request a pseudo-TTY, and set the TERM environment variable. You can also set things like the terminal size and modes.

As for path, it looks like you are using zsh here -- are you setting path in .zshrc, or some other file like .zprofile? When I run OpenSSH with a command to run on the remote system, it appears not to execute .zshrc, so the path is set to a much smaller default path like what you show above. However, when you run it with no command to drop into an interactive shell, it does run .zshrc and set the longer PATH. This is a function of the SSH server, not the client, so you should see similar behavior with both OpenSSH and AsyncSSH as the client. When you did your test, were you passing a command to run in both cases?

If you need to, you could always tell the remote system to run .zshrc explicitly before running a command. Instead of "somecommand", you could pass in a command of ". .zshrc; somecommand" and see if that helps.

**Comment by epg584** [comment]
> When you did your test, were you passing a command to run in both cases?
on asyncssh, yes, I'm just passing a command a reading the output. When I do it manually, I just connect via putty and do the exact same command. 
I tried setting term_type as xterm (which is what is set in my putty configuration) and nothing changed. Also tried running .zshrc before the command, and checked $PATH before and after running it. Nothing changed at all, the PATH is always /usr/bin:/bin:/usr/sbin:/sbin

**Comment by ronf** [comment]
When you ran .zshrc, what exactly did the command look like? If you want the pash changes to stick, you need to run it with the "." or "source" command. Without that, the changes will be made in a sub-shell which goes away before the actual command after it is run.

Also, have you confirmed that the path you want is set by .zshrc and not some other shell init file?

I believe you should see the same results between AsyncSSH and OpenSSH, if you test OpenSSH trying to run a command like you are doing with AsyncSSH. That may be easier for testing, and will rule out any issues in AsyncSSH itself. Once you get it working with OpenSSH (like doing "ssh localhost" with different versions of the command to run), you can then go back and try to replicate that with AsyncSSH.

Also, I'm still not sure what all those environment variables would have been copied over, as the SSH server on macOS is pretty strict about what it will let a client pass in. Do you know if that sshd configuration was changed on the system you are connecting to?

**Comment by epg584** [comment]
You're absolutely right, when I run .zshrc with source it works! And yes, the path I want is in .zshrc so it's all working fine now. Thank you for your help!

**Comment by ronf** [comment]
Terrific - glad you got it working!
