### ISSUE TITLE
Mixed mode over single connection

### ISSUE THREAD

**Issue by Menyadar** [ronf/asyncssh#706]
Based on SSH specs once the connection is opened it is generally symmetric and both sides can request to open a channel (or session, subsystem). This works well and asyncssh has some basic support for this in the form of `listen_reverse` and `connect_reverse`, where both sides swap roles after the connection is established. However this is _all-or-nothing_. From `asyncssh`'s point of view one side is always a client and other is always a server.

I'm working on a tool where both sides are asyncssh endpoints and both sides need to support client and server personalities over single connection. Intended usage is like this:

1. `A`lice opens (conn)ection to `B`ob.
2. `A` acts as a clinet using `writer, reader, err = conn.open_session()`, possibly using custom subsystem, creating channel 0.
3. `A` handles reads/writes as usual using channel 0.
4. `B` signals a desire to use resources from `A`.
5. `A` unlocks (or not) given session to be opened from `B` and signals readiness.
6. Now `B` calls `conn.open_session()` with custom subsystem, creating channel 1 over the same connection.
7. `B` does some work on `A` side using channel 1.
8. `B` closes own _"client"_ session (channel 1), but remains as active on channel 0.

Generally speaking:

- `B` is the server in network sense and `A` connects to it on demand.
- Connecting to and/or opening ports on `A` side is forbidden (applies also for tunelled connections).
- `B` may request resources from `A` and use them in any way it wants (within limits of what `A` allows).

Using `B` side to implement all _"server"_ side logic is possible, but quite awkward. Imagine `A` needs to control `B` while simultaneously make some files available. Without mixed mode support, `B` needs to accept sftp client connection (and act as a server for upload) and signal to `A` which file(s) it needs. `A` then uploads the files and `B` handles them after `SFTPServerFile.close()` completes (or when `A` notifies `B` when given file is uploaded).
If mixed mode was supported, `A` would just start sftp server when requested and `B` would fetch required file(s).

I have limited success with subclassing `SSHServerConnection` and `SSHClientConnection` (with respective `SSH[Server|Client]ConnectionOptions`) and augmenting them with relevant parts from the other class, but it feels wrong and error-prone (and for sure is not future-proof). Composable classes would be nice, but i wasn't brave enough (yet ;-)) to dive to all the internals to check if this is even viable.

Is there some preferred way to solve this without butchering connection classes too much?

**Comment by ronf** [comment]
What you're asking for here is explicitly against the SSH protocol as documented in RFC 4254. Specifically, see section 6.1:

```
   Client implementations SHOULD reject any session channel open
   requests to make it more difficult for a corrupt server to attack the
   client.
```

There are exceptions, such as TCP/IP forwarding where you can have channeled opened from the server to client, but only after the client has done a global request to tell the server what port it should listen on and forward. See more details in that same RFC in sections 7.1 and 7.2.

Nothing would stop you for layering your own application protocol on top of SSH, where A opens a channel to B but then waits for B to tell it that it needs something, at which point A would open a new channel to B to handle whatever request it just got. However, you wouldn't easily be able to use existing subsystems like SFTP on the channels you opened.

My suggestion is that you open two connections. The first could be a standard A->B connection with A as the client. On that connection, it could pass some kind credentials for B to use when A opens a reverse direction connection to B. At that point, you'd have two connections open, both initiated from A->B from a TCP perspective, but one would be A as the client and B as the server and the other would have the opposite, at which point either side could make requests of the other using all the standard SSH mechanisms.

**Comment by Menyadar** [comment]
As you noted, there is a SHOULD (per RFC 2119) and that means:

> 3. **SHOULD**   This word, or the adjective "RECOMMENDED", mean that there
>    may exist valid reasons in particular circumstances to ignore a
>    particular item, but the full implications must be understood and
>    carefully weighed before choosing a different course.

But thanks for reminding me a subsystem is actually a session on itself. Now back to RFC 4254 (emphasis mine):

> 6.5.  Starting a Shell or a Command
> 
>    [...]
> 
>       byte      SSH_MSG_CHANNEL_REQUEST
>       uint32    recipient channel
>       string    "subsystem"
>       boolean   want reply
>       string    subsystem name
> 
>    This last form executes a predefined subsystem.  It is expected that
>    these will include a general file transfer mechanism, and possibly
>    other features.  Implementations may also allow configuring more such
>    mechanisms.  **As the user's shell is usually used to execute the**
>    **subsystem**, it is advisable for the subsystem protocol to have a
>    "magic cookie" at the beginning of the protocol transaction to
>    distinguish it from arbitrary output generated by shell
>    initialization scripts, etc.  This spurious output from the shell may
>    be filtered out either at the server or at the client.

It is clear the intention generally was to prevent rogue servers from executing arbitrarily crafted shell commands on the client (foreshadowing ShellShock?)

In my case this precaution is unnecessary, as my code:
- is meant to be used as a communication bridge between two separate tools,
- is already using nonstandard subsystem (non-shell) for the first `A` -> `B` session,
- won't start any external command on either side,
- won't make `A`'s resources available automatically from the start (both sides must cooperate).

Why do i think it is better solution for me to mix modes over single connection?
- Rebuilding (possibly standard) blocks on top of generic channels is cumbersome, duplicates existing work and generally feels wrong.
- Opening port on `A` side and tunneling new connection there is "problematic" (opening local ports may be blocked by firewalls, policies, etc.)
- Opening second connection from `A` and reversing it's logic is also non-standard and according to your own view is explicitly against SSH protocol, as it opens session on the client, plus it creates more problems than it solves (see below). Moreover extra (and for this matter short-lived) connections could be considered as malicious by some administrative tools, may (again) be limited by firewalls, policies, etc.

Aside from probably fitting better to asyncssh logic, opening (and then reversing) second connection won't make anything easier. Quite the opposite:
- Opening new connection may fail for whatever reason.
- Magic cookie (aka _"some kind [of] credentials"_) needs to be generated and shared on both sides, plus extra logic is needed to validate it before opening the session.
- Minor hacks are needed on server `B` side to handle both "normal" and "reverse" connections.
- Extra code to synchronize state is needed.
- Will this make network client `A` more resilient against possible rogue server `B`? Nope.

So, i'm inclined to continue transplanting relevant parts between connection classes to support mixed mode connection for my case as no other option brings any real benefits. As i don't need to care for interactive sessions (i.e. all the terminal handling code) and need just the subsystem part (possibly with sftp, if i could bend it my way), are there any shortcuts i can make? What is really needed and what parts are just remnants of old APIs there?

**Comment by ronf** [comment]
The biggest challenge you're going to face here is that the classes are defined based on whether they are acting as a client or a server. While there's a bunch of shared code as well in SSHConnection and SSHChannel, anything that's client or server specific is in SSHClientConnection/SSHServerConnection or SSHClientChannel/SSHServerChannel. Even the set of message types these classes can handle is in separate `_packet_handlers` instances for each class. If you wanted to make something which could simultaneously be a client AND a server from the point of view of the SSH protocol, you'd need to merge all that code back into a single combined class, which would be a major rewrite, and you can't just inherit from both classes, as that would run into conflicts with some of the member variables (such as `_packet_handlers`).

There might be a middle ground here where you could be on an SSHServerConnection but create an SSHClientChannel associated with that or vice-versa, if you knew at the time of opening the channel that you needed something to go in the reverse direction. To do that, though, you'd still need the SSHClientConnection to handle the resulting channel request. As it turns out, the `_process_channel_open` method is already in the shared SSHConnection class. It then calls another method based on the channel type, such as `_process_session_open`. That actually exists in both SSHClientConnection and SSHServerConnection already, but the SSHClientConnectionVersion today just raises an error. If you were to override that and allow a server channel to be created (using the code in SSHServerConnection), it would probably get you part of the way. However, I think you'll run into other challenges, as some of the configuration options needed for that server method to work include options that only exist in SSHServerConnectionOptions, and so there'd be no way to specify things like the session or process factory in the SSHClientConnection instance to use when opening that server channel.

**Comment by Menyadar** [comment]
Thanks for hints. Looks complicated, but doable. Options with second connection are generally no-go for me, so i have just one possible fallback if this endeavour fails - play ping-pong between `A` and `B` and let `B` call `A` for each required step. This brings unnecessary delays, but it "works" (_okay-ish_).
