### ISSUE TITLE
Inconsistent behavior when redirecting IO

### ISSUE THREAD

**Issue by Menyadar** [ronf/asyncssh#708]
python 3.10
asyncssh: 2.18.0 (latest pypi)

```python
import asyncio, asyncssh, sys

async def run_client() -> None:
    async with asyncssh.connect("localhost") as conn:
        async with conn.create_process(
            term_type="xterm",
#            stdin=sys.stdin,
#            stdout=sys.stdout,
#            stderr=sys.stderr
        ) as process:
            print("process ready")
            process.stdin.close()
            print("stdin closed")
            await process.wait_closed()
            print("process.wait_closed finished")

try:
    asyncio.run(run_client())
    print("asyncio.run finished")
except (OSError, asyncssh.Error) as exc:
    sys.exit("SSH connection failed: " + str(exc))
```

Run as is (none of `stdin`/`stdout`/`stderr` is redirected):
```console
$ python3.10 iotest.py 
process ready
stdin closed
process.wait_closed finished
asyncio.run finished
```

Uncomment just `stdin` redirection. This runs ok in this simple example, but fails with exception in more complex cases.
```console
$ python3.10 iotest.py 
process ready
stdin closed
process.wait_closed finished
asyncio.run finished
```

Uncomment `stdin` and `stdout`:
```console
$ python3.10 iotest.py
process ready
stdin closed
Traceback (most recent call last):
  File "iotest.py", line 35, in <module>
    asyncio.run(run_client())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "iotest.py", line 31, in run_client
    print("process.wait_closed finished")
ValueError: I/O operation on closed file.
```
Redirect `stdin`, `stdout` and `stderr`:
```console
$ python3.10 iotest.py
process ready
stdin closed
```
In the last case, it just exits. When logging is enabled it shows channel received close event (`Received channel close` followed by `Channel closed`) and tasks added with `add_cleanup_task` are executed, but nothing after `wait_closed` runs. It just "cleanly" dies there.

**Comment by ronf** [comment]
Do you know where the error message "ValueError: I/O operation on closed file." is coming from? There's a message similar to that in asyncssh.sftp, but you don't seem to be using that here, and I don't see any message like that in asyncio or in your example code.

Since you are using "async with" on the process, this code will end up calling process.wait_closed() twice. There was a recently fixed problem related to that in AsyncSSH, but you should have the fix for that in 2.18.0, so that shouldn't cause a problem.

Are you doing anything unusual with std.stdin/stdout/stderr, or are those all pointing at the user's terminal? I don't really see how you could be getting the ValueError you're showing here if those are set to defaults.

Note that anything going to stderr will instead be written to stdout in ths case, since you are requesting a PTY by setting terminal type. It should be ok to redirect stderr, but it shouldn't receive any output.

Are you trying to run a command here, or just start an interactive shell? I don't see any command listed in the create_process() call.

**Comment by Menyadar** [comment]
> Since you are using "async with" on the process, this code will end up calling process.wait_closed() twice

This is just because I've tried to make it look like example on the web. Removing contex manager makes no difference.

```python
async def run_client() -> None:
    async with asyncssh.connect("localhost", 8022, username="jx") as conn:
        process = await conn.create_process(
            term_type="xterm", stdin=sys.stdin, stdout=sys.stdout  # , stderr=sys.stderr
        )
        print("process ready")
        [...]
```

`ValueError: I/O operation on closed file.` comes directly from python and i suspect that's just because `sys.stdout` is closed right before `print` tries to use it.

> There was a recently fixed problem related to that in AsyncSSH, but you should have the fix for that in 2.18.0, so that shouldn't cause a problem.

First i've experienced this with `2.15.0` where tasks added using `add_cleanup_tasks` wouldn't be executed in such situation, but they're working fine with `2.18.0`. However this abrupt exit is same in both versions and that's what i'm after.

> Are you doing anything unusual with std.stdin/stdout/stderr, or are those all pointing at the user's terminal? I don't really see how you could be getting the ValueError you're showing here if those are set to defaults.

Nothing unusual, any python version i have here (3.8, 3.9, 3.10, 3.11) behaves the same (ubuntu 22.04). Running from `xfce4-terminal`, but that shouldn't matter. Make a clean venv with just asyncssh and run this code and you should get same result. 

> Note that anything going to stderr will instead be written to stdout in ths case, since you are requesting a PTY by setting terminal type.

Yes, i know and redirecting all three is the way this should be used. I hunt this bug for quite a while now so first i've just stripped down most of my code, then (just to make sure i'm not doing anything weird) i just recreated this by modifying sample code. `process.stdin.close` is a shortcut, in real code `stdin` receives `EOF` and library code does some buffer flushing and few other things before it calls `close()` on `stdin`.

If i run this (doesn't matter if one with context manager or that above where process is directly awaited) with just `stdin` and `stdout` redirected, `ValueError` is raised. When i redirect `stderr` on the console to `/dev/null`, it behaves just like the last method (all three redirected):

```console
$ # just stdin and stdout redirected in code
$ python3.10 iotest.py 2> /dev/null
process ready
stdin closed
```

> It should be ok to redirect stderr, but it shouldn't receive any output.

I don't think i understand here. Of course it should receive output (when remote end needs to communicate some error) and yes, it should mix it to `stdout` if (and only if) it is not redirected away by some other means (i.e. by `2> /some/path` or similar when run in a shell)

> Are you trying to run a command here, or just start an interactive shell? I don't see any command listed in the create_process() call.

Interactive shell. I need a somewhat augmented ssh client to debug my (mixed-mode) ssh server code so i went to implement one. Works mostly fine (including handling of full-screen apps), but it remains a mystery how i should correctly end a connection, as it just dies when all IO is redirected. It's tricky to debug, as most debuggers tend to inject own `stdin`/`stdout`/`stderr` wrappers, so i just slap `print` everywhere (before and after any call) in both my and library code to see how far this goes and what actually get called and this is how i've discovered this.

**Comment by Menyadar** [comment]
After some more time spent with debugging this i think i finally know what happens.

With any redirection asyncssh claims those io streams and when closing ssh session it closes these streams with it. This happens somewhere between `SSHChannel.close()` and `SSHChannel.wait_closed()`. That's why when `stderr` wasn't redirected we can see python exceptions printed. When all three streams are redirected, even `stderr` is delegated to ssh session (and no errors come from that side), so python has no way to display "own" (local) errors. As there is a print after `process.wait_closed()`, this raises exception and (if `stderr` is redirected) there is just no default way to display it. Then from user side it looks like it just silently died there. Of course dumping traceback to file works and shows exactly the same thing as if `stderr` wasn't redirected.

When this was out of the way, debugging of my _real_ problem was trivial - as i need to change low level terminal setting, it was enough to call `create_process` with `recv_eof=False` and then work with _fd_ of `sys.stdout` after `process.wait_closed()` returned. Now i have fully working, well-behaving replacement for `ssh` command supporting remote `vi`, `mc` and other non line-oriented programs.

**Comment by ronf** [comment]
Ah, yes! As soon as you mentioned print(), I remembered an earlier discussion on this in #245.

In addition to the issue you mentioned with needing to dup() the file descriptors to avoid AsyncSSH closing the original, you may also run into issues with buffering on calls to print() in some cases, where mixing I/O generated via print() and redirected I/O to sys.stdout will end up out of order unless you do explicit flushes. Since these were just debugging statements in your case here, that may not be an issue for your real application code. However, I thought I would mention it just in case you ever tried to do direct output to sys.stdout/sys.stderr interspersed with redirected output from AsyncSSH.

**Comment by Menyadar** [comment]
Yeah, as soon as i've discovered what is going on and how accessing these from different places just messes everything, it was pretty much solved. I'll have to handle stdin/stdout in near future (want to implement something like hotkey-escape to set local options - just like in openssh), but that's a problem for future me :smile:
Btw i see some request for hint to support `vi` or similar in #70, if this is still unanswered, i can provide some (so far rough) sample.

**Comment by ronf** [comment]
Thanks for the offer!

I think the issues discussed in #70 related to redirection were resolved. However, if you've found that you need to do something special to make full screen apps like "vi" work, that might be something worth creating a new discussion topic around (in https://github.com/ronf/asyncssh/discussions). I've done some experimentation with that in a slightly different context where I was doing session recording with some of the sessions including full-screen apps and it generally seemed to work for me. I didn't do a lot of testing, though.
