### ISSUE TITLE
SFTP progress report

### ISSUE THREAD

**Issue by cachitas** [ronf/asyncssh#79]
Is it possible to have a reading of the progress of the file transfer?

**Comment by ronf** [comment]
Yes, good idea.

I've just checked in a change to the "develop" branch which adds new arguments block_size and progress_handler to the get, put, copy, mget, mput, and mcopy methods of the SFTPClient class.

The block_size argument controls the size used in the file read & write calls. This was previously hardcoded at 16 KB. It now defaults to 16 KB, but lets you adjust it.

The progress_handler argument defaults to None, but allows you to pass in a callback function which will get called each time a block finishes being copied. Each time it is called, this handler will be passed 4 arguments: source path, destination path, bytes copied so far, and total bytes in the file being copied. If you make a request to copy multiple files, this callback will be called consecutively on each file being copied. The frequency of these progress reports can be adjusted by changing the block size.

Let me know what you think. I'll probably be migrating these changes to "master" and putting out a new release this weekend with this and other work I've done in the last month or so.

**Comment by ronf** [comment]
This feature is now available in the 1.9.0 release.

**Comment by cachitas** [comment]
Thank you for your quick response!

That was indeed what I had in mind. I will try it as soon as I can.
