### ISSUE TITLE
set ssh connection socket to be keepalive

### ISSUE THREAD

**Issue by jiang-wanwei** [ronf/asyncssh#80]
keep ssh connection alive is very useful in some situation

**Comment by ronf** [comment]
Yes, I can add code to enable this. I'm in the middle of some other changes at the moment, but I'll add this in once I get my other changes done.

**Comment by ronf** [comment]
This change is now in the "develop" branch, and will be included in the next release.

**Comment by ronf** [comment]
This change is now available in AsyncSSH version 1.10.0.
