### ISSUE TITLE
Should IPv6 Addresses with '[]' be natively supported by asyncssh.connect()

### ISSUE THREAD

**Issue by cooperlees** [ronf/asyncssh#82]
Passing in an IPv6 address wrapped in [] to asyncssh.connect() (e.g. [2401:db00:26:3047::28]) fails as we do a DNS upgrade.

This may need to be fixed further down the stack than asyncssh. I've fixed my code to handle this, but just wanted to bring this up for discussion.

Example error:
[2017-03-11 11:39:30,272] ERROR: Failed to connect to [2401:db00:26:3047::28]: [Errno -2] Name or service not known

**Comment by cooperlees** [comment]
Intersting:
import ipaddress
ipaddress.ip_address('[69::69]')
ValueError: '[69::69]' does not appear to be an IPv4 or IPv6 address

I have a system that gives me IPs with [] - I'll just remove them. This might be a battle not worth fighting.

**Comment by ronf** [comment]
Square brackets around literal IPv6 addresses are generally only accepted in the context of something like a URL, where you are mixing together an IP address and port. These brackets should never appear in an address by itself, or where you are providing the address and port as distinct arguments (or part of a tuple, like with socket's connect() method.

There are a few places in AsyncSSH where square brackets are already allowed on IPv6 addresses (and host names). Specifically, they're allowed in the "permitopen" option in an authorized keys file, where a host:port value is accepted. They're also allowed in host patterns which can appear in known hosts entries (where again host:port is accepted). Finally, they're allowed in the X11 code, where an X11 display is being parsed, as it is of the form host:displaynum, which has a similar issue to host:port.

Stripping them off yourself when you see them in an address is probably the right thing here, or even better have whatever code is parsing out the address in the first place do this. As you can see from your tests, the standard Python libraries that take IPv6 addresses expect the brackets to already be stripped off.

**Comment by cooperlees** [comment]
Will do - just wanted a second opinion - Thanks @ronf.
