### ISSUE TITLE
enable ssh and sftp content compression

### ISSUE THREAD

**Issue by jiang-wanwei** [ronf/asyncssh#83]
When I use sftp to download a large file, the speed is too low. And now asyncssh.create_connection function only support compression during the SSH handshake   
"compression_algs (list of str) – (optional) A list of compression algorithms to use during the SSH handshake, taken from compression algorithms, or None to disable compression"

**Comment by ronf** [comment]
The compression_algs argument specifies what compression algorithms to request/offer during the handshake, but if it is accepted by the SSH peer this compression applies for the lifetime of the connection, including all of the data sent over SFTP.

You can use the get_extra_info() call on the connection to see what compression was negotiated. Take a look at the 'send_compression' and 'recv_compression' values there.
